/*
** Title:          FIXType.c
** SCCSid:         %W% %E% %U%
** CCid:           %W% %E% %U%
** Author:         Informix
** Created:        08/24/1999 11:57
** Description:    This is a generated source file for the FIXType DataBlade module.
** Comments:       Generated for project FIXType.1.1
*/

/*
**  The following is placed here to insure
**  that name "mangling" does not occur.
*/
#ifdef __cplusplus

extern "C"
{

#endif

/* Standard library includes. */
#include <ctype.h>
#include <stdio.h>
#include <string.h>
#include <stddef.h>

/* Used by Informix GLS routines. */
#include <ifxgls.h>

/* Include when accessing the Informix API. */
#include <mi.h>

/* This is the project include file. */
#include "FIXType.h"

/* {{FUNCTION(156f144c-557d-11d3-b686-00a024e37610) (MergeSection) */

/*******************************************************************************
**
** Function name:
**
**	FIXTypeSend
**
** Description:
**
**	The binary send function is used to convert an instance of a
**	data type between its internal representation on the server and
**	on the client.
**
** Special Comments:
**
**	Support routine for opaque type FIXType returns mi_sendrecv.
**
** Parameters:
**
**	FIXType *          Gen_param1;    Pointer to the input text.
**	MI_FPARAM *        Gen_fparam;    Standard info - see DBDK docs.
**
** Return value:
**
**	mi_sendrecv *                     The constructed UDT value.
**
** History:
**
**	08/24/1999 - Generated by BladeSmith Version 4.00.TC1B.
**
** Identification:
**
**	Warning: Do not remove or modify this comment:
**	    FIXTypeSend FunctionId: 156f144c-557d-11d3-b686-00a024e37610
**
********************************************************************************
*/

UDREXPORT
mi_sendrecv *
FIXTypeSend
(
FIXType *                    Gen_param1,      /* The UDT value                           */
MI_FPARAM *                  Gen_fparam       /* Standard info - see DBDK docs.          */
)
{
	MI_CONNECTION *      Gen_Con;         /* The current connection.                 */
	FIXType *            Gen_InData;      /* Pointer to the UDT value.               */
	FIXType *            Gen_OutData;     /* Pointer to the packet data.             */
	mi_sendrecv *        Gen_RetVal;      /* The return value.                       */
mi_integer           Gen_Index10;

	/* Get the current connection handle. */
	Gen_Con = mi_open( NULL, NULL, NULL );

	/* Verify that the connection has been established. */
	if( Gen_Con == 0 )
	{
		/*
		** Opening the current connection has failed
		** so issue the following message and quit.
		**
		** 	"Connection has failed in FIXTypeSend."
		*/
		DBDK_TRACE_ERROR( "FIXTypeSend", ERRORMESG1, 10 );

		/* not reached */
	}

	/* Point to the input data. */
	Gen_InData = Gen_param1;

	/* Allocate a new return value. */
	Gen_RetVal = (mi_sendrecv *)mi_new_var( sizeof( FIXType ) );
	if( Gen_RetVal == 0 )
	{
		/*
		** Memory allocation has failed so issue
		** the following message and quit.
		**
		** 	"Memory allocation has failed in FIXTypeSend."
		*/
		DBDK_TRACE_ERROR( "FIXTypeSend", ERRORMESG2, 10 );

		/* not reached */
	}

	/* Point to the output data. */
	Gen_OutData = (FIXType *)mi_get_vardata( (mi_lvarchar *)Gen_RetVal );

	/* Prepare the value for Gen_OutData->col1. */
	mi_put_integer( (mi_unsigned_char1 *)&Gen_OutData->col1, Gen_InData->col1 );
	
	/* Perform the operation on each of the array elements. */
	for( Gen_Index10 = -1; ++Gen_Index10 < 10; )
	{
		/* Prepare the value for Gen_OutData->col2[Gen_Index10]. */
		mi_put_bytes( (mi_unsigned_char1 *)&Gen_OutData->col2[Gen_Index10], (char *)&Gen_InData->col2[Gen_Index10], 1 );
	}
	

	/* Close the connection. */
	mi_close( Gen_Con );

	/* Return the UDT for transmission. */
	return Gen_RetVal;
}
/* }}FUNCTION (#KJTH) */



/* {{FUNCTION(156f144d-557d-11d3-b686-00a024e37610) (MergeSection) */

/*******************************************************************************
**
** Function name:
**
**	FIXTypeReceive
**
** Description:
**
**	The binary receive function is used to convert an instance of a
**	data type between its internal representation on the server and
**	on the client.
**
** Special Comments:
**
**	Support routine for opaque type FIXType returns FIXType.
**
** Parameters:
**
**	mi_lvarchar *      Gen_param1;    Pointer to the input text.
**	MI_FPARAM *        Gen_fparam;    Standard info - see DBDK docs.
**
** Return value:
**
**	FIXType *                         The constructed UDT value.
**
** History:
**
**	08/24/1999 - Generated by BladeSmith Version 4.00.TC1B.
**
** Identification:
**
**	Warning: Do not remove or modify this comment:
**	    FIXTypeReceive FunctionId: 156f144d-557d-11d3-b686-00a024e37610
**
********************************************************************************
*/

UDREXPORT
FIXType *
FIXTypeReceive
(
mi_sendrecv *                Gen_param1,      /* The UDT value.                          */
MI_FPARAM *                  Gen_fparam       /* Standard info - see DBDK docs.          */
)
{
	MI_CONNECTION *      Gen_Con;         /* The current connection.                 */
	FIXType *            Gen_RetVal;      /* The return value.                       */
	FIXType *            Gen_InData;      /* Packet data.                            */
	FIXType *            Gen_OutData;     /* Output UDT value.                       */
mi_integer           Gen_Index10;

	/* Get the current connection handle. */
	Gen_Con = mi_open( NULL, NULL, NULL );

	/* Verify that the connection has been established. */
	if( Gen_Con == 0 )
	{
		/*
		** Opening the current connection has failed
		** so issue the following message and quit.
		**
		** 	"Connection has failed in FIXTypeReceive."
		*/
		DBDK_TRACE_ERROR( "FIXTypeReceive", ERRORMESG1, 10 );

		/* not reached */
	}

	/* Point to the input data. */
	Gen_InData = (FIXType *)mi_get_vardata( (mi_lvarchar *)Gen_param1 );


	/* Allocate room for the UDT. */
	Gen_RetVal = (FIXType *)mi_alloc( sizeof( FIXType ) );
	if( Gen_RetVal == 0 )
	{
		/*
		** Memory allocation has failed so issue
		** the following message and quit.
		**
		** 	"Memory allocation has failed in FIXTypeReceive."
		*/
		DBDK_TRACE_ERROR( "FIXTypeReceive", ERRORMESG2, 10 );

		/* not reached */
	}

	/* Point to the output data. */
	Gen_OutData = (FIXType *)Gen_RetVal;

	/* Copy the attribute value(s) from the transmission parcel. */

	/* Prepare the value for Gen_OutData->col1. */
	mi_get_integer( (mi_unsigned_char1 *)&Gen_InData->col1, &Gen_OutData->col1 );
	
	/* Perform the operation on each of the array elements. */
	for( Gen_Index10 = -1; ++Gen_Index10 < 10; )
	{
		/* Prepare the value for Gen_OutData->col2[Gen_Index10]. */
		mi_get_bytes( (mi_unsigned_char1 *)&Gen_InData->col2[Gen_Index10], (char *)&Gen_OutData->col2[Gen_Index10], 1 );
	}
	

	/* Close the connection. */
	mi_close( Gen_Con );

	/* Return the transmitted UDT value. */
	return Gen_RetVal;
}
/* }}FUNCTION (#1KCF) */



/* {{FUNCTION(156f144f-557d-11d3-b686-00a024e37610) (MergeSection) */

/*******************************************************************************
**
** Function name:
**
**	FIXTypeImportBinary
**
** Description:
**
**	The  importbinary  function is  used to  support  bulk copy of
**	binary data. This function is the same as the import function,
**	except that it  operates  on internal  representations of  the
**	data type.  This function is  usually only  provided for large
**	object  data types and is called by the LOAD BINARY command of
**	dbaccess.
**
** Special Comments:
**
**	Support routine for opaque type FIXType returns FIXType.
**
** Parameters:
**
**	mi_bitvarying *    Gen_param1;    Pointer to the input text.
**	MI_FPARAM *        Gen_fparam;    Standard info - see DBDK docs.
**
** Return value:
**
**	FIXType *                         The constructed UDT value.
**
** History:
**
**	08/24/1999 - Generated by BladeSmith Version 4.00.TC1B.
**
** Identification:
**
**	Warning: Do not remove or modify this comment:
**	    FIXTypeImportBinary FunctionId: 156f144f-557d-11d3-b686-00a024e37610
**
********************************************************************************
*/

UDREXPORT
FIXType *
FIXTypeImportBinary
(
mi_bitvarying *              Gen_param1,      /* The input value.                        */
MI_FPARAM *                  Gen_fparam       /* Standard info - see DBDK docs.          */
)
{
	MI_CONNECTION *      Gen_Con;         /* The current connection.                 */
	FIXType *            Gen_RetVal;      /* The return result.                      */
	FIXType *            Gen_InData;      /* The UDT input value.                    */
	FIXType *            Gen_OutData;     /* The transfer data.                      */
mi_integer           Gen_Index10;

	/* Get the current connection handle. */
	Gen_Con = mi_open( NULL, NULL, NULL );

	/* Verify that the connection has been established. */
	if( Gen_Con == 0 )
	{
		/*
		** Opening the current connection has failed
		** so issue the following message and quit.
		**
		** 	"Connection has failed in FIXTypeImportBinary."
		*/
		DBDK_TRACE_ERROR( "FIXTypeImportBinary", ERRORMESG1, 10 );

		/* not reached */
	}

	/* Point to the input data. */
	Gen_InData = (FIXType *)mi_get_vardata( (mi_lvarchar *)Gen_param1 );

	/* Allocate a new UDT for the return result. */
	Gen_RetVal = (FIXType *)mi_alloc( sizeof( FIXType ) );
	if( Gen_RetVal == 0 )
	{
		/*
		** Memory allocation has failed so issue
		** the following message and quit.
		**
		** 	"Memory allocation has failed in FIXTypeImportBinary."
		*/
		DBDK_TRACE_ERROR( "FIXTypeImportBinary", ERRORMESG2, 10 );

		/* not reached */
	}

	/* Point to the output data. */
	Gen_OutData = (FIXType *)Gen_RetVal;

	/* Prepare the value for Gen_OutData->col1. */
	mi_get_integer( (mi_unsigned_char1 *)&Gen_InData->col1, &Gen_OutData->col1 );
	
	/* Perform the operation on each of the array elements. */
	for( Gen_Index10 = -1; ++Gen_Index10 < 10; )
	{
		/* Prepare the value for Gen_OutData->col2[Gen_Index10]. */
		mi_get_bytes( (mi_unsigned_char1 *)&Gen_InData->col2[Gen_Index10], (char *)&Gen_OutData->col2[Gen_Index10], 1 );
	}
	

	/* Close the connection. */
	mi_close( Gen_Con );

	return Gen_RetVal;
}
/* }}FUNCTION (#52FQ) */



/* {{FUNCTION(156f144e-557d-11d3-b686-00a024e37610) (MergeSection) */

/*******************************************************************************
**
** Function name:
**
**	FIXTypeExportBinary
**
** Description:
**
**	The  exportbinary  function  is  used  to  support  bulk  copy  of
**	binary  data.  This function is the same as  the export  function,
**	except that it  operates on  internal  representations of the data
**	type.  This  function is usually only  provided  for large  object
**	data types and is called by the UNLOAD BINARY command of dbaccess.
**
** Special Comments:
**
**	Support routine for opaque type FIXType returns mi_bitvarying.
**
** Parameters:
**
**	FIXType *          Gen_param1;    Pointer to the input text.
**	MI_FPARAM *        Gen_fparam;    Standard info - see DBDK docs.
**
** Return value:
**
**	mi_bitvarying *                   The exported UDT value.
**
** History:
**
**	08/24/1999 - Generated by BladeSmith Version 4.00.TC1B.
**
** Identification:
**
**	Warning: Do not remove or modify this comment:
**	    FIXTypeExportBinary FunctionId: 156f144e-557d-11d3-b686-00a024e37610
**
********************************************************************************
*/

UDREXPORT
mi_bitvarying *
FIXTypeExportBinary
(
FIXType *                    Gen_param1,      /* The UDT value.                          */
MI_FPARAM *                  Gen_fparam       /* Standard info - see DBDK docs.          */
)
{
	MI_CONNECTION *      Gen_Con;         /* The current connection.                 */
	mi_bitvarying *      Gen_RetVal;      /* The return value.                       */
mi_integer           Gen_Index10;
	FIXType *            Gen_InData;      /* The transfer data.                      */
	FIXType *            Gen_OutData;     /* The output data.                        */

	/* Get the current connection handle. */
	Gen_Con = mi_open( NULL, NULL, NULL );

	/* Verify that the connection has been established. */
	if( Gen_Con == 0 )
	{
		/*
		** Opening the current connection has failed
		** so issue the following message and quit.
		**
		** 	"Connection has failed in FIXTypeExportBinary."
		*/
		DBDK_TRACE_ERROR( "FIXTypeExportBinary", ERRORMESG1, 10 );

		/* not reached */
	}

	/* Point to the input data. */
	Gen_InData = Gen_param1;

	/* Allocate the output parcel. */
	Gen_RetVal = (mi_bitvarying *)mi_new_var( sizeof( FIXType ) );
	if( Gen_RetVal == 0 )
	{
		/*
		** Memory allocation has failed so issue
		** the following message and quit.
		**
		** 	"Memory allocation has failed in FIXTypeExportBinary."
		*/
		DBDK_TRACE_ERROR( "FIXTypeExportBinary", ERRORMESG2, 10 );

		/* not reached */
	}

	/* Point to the output data. */
	Gen_OutData = (FIXType *)mi_get_vardata( (mi_lvarchar *)Gen_RetVal );

	/* Prepare the value for Gen_OutData->col1. */
	mi_put_integer( (mi_unsigned_char1 *)&Gen_OutData->col1, Gen_InData->col1 );
	
	/* Perform the operation on each of the array elements. */
	for( Gen_Index10 = -1; ++Gen_Index10 < 10; )
	{
		/* Prepare the value for Gen_OutData->col2[Gen_Index10]. */
		mi_put_bytes( (mi_unsigned_char1 *)&Gen_OutData->col2[Gen_Index10], (char *)&Gen_InData->col2[Gen_Index10], 1 );
	}
	

	/* Close the connection. */
	mi_close( Gen_Con );

	/* Return the UDT value. */
	return Gen_RetVal;
}
/* }}FUNCTION (#VQVU) */



/* {{FUNCTION(156f1452-557d-11d3-b686-00a024e37610) (MergeSection) */

/*******************************************************************************
**
** Function name:
**
**	FIXTypeCompare
**
** Description:
**
**	Perform the comparison operations required to compare two
**	UDT values.
**
**	This function returns zero if the two UDT values are equal and
**	a non-zero value otherwise.
**
** Special Comments:
**
**	Compares two fixed-sized opaque types
**
** Parameters:
**
**	FIXType *          Gen_param1;    The first UDT value to compare.
**	FIXType *          Gen_param2;    The second UDT value to compare.
**	MI_FPARAM *        Gen_fparam;    Standard info - see DBDK docs.
**
** Return value:
**
**	mi_integer                        The comparison result.
**
** History:
**
**	08/24/1999 - Generated by BladeSmith Version 4.00.TC1B.
**
** Identification:
**
**	Warning: Do not remove or modify this comment:
**	    FIXTypeCompare FunctionId: 156f1452-557d-11d3-b686-00a024e37610
**
********************************************************************************
*/

UDREXPORT
mi_integer
FIXTypeCompare
(
FIXType *                    Gen_param1,      /* The first UDT value to compare.         */
FIXType *                    Gen_param2,      /* The second UDT value to compare.        */
MI_FPARAM *                  Gen_fparam       /* Standard info - see DBDK docs.          */
)
{
	MI_CONNECTION *      Gen_Con;         /* The current connection.                 */
	mi_integer           Gen_cc;          /* Numeric attribute difference.           */
mi_integer           Gen_Index10;
	FIXType *            Gen_Value1;      /* Pointer to the first value.             */
	FIXType *            Gen_Value2;      /* Pointer to the second value.            */

	/* Get the current connection handle. */
	Gen_Con = mi_open( NULL, NULL, NULL );

	/* Verify that the connection has been established. */
	if( Gen_Con == 0 )
	{
		/*
		** Opening the current connection has failed
		** so issue the following message and quit.
		**
		** 	"Connection has failed in FIXTypeCompare."
		*/
		DBDK_TRACE_ERROR( "FIXTypeCompare", ERRORMESG1, 10 );

		/* not reached */
	}

	/* Point to the data values that are to be compared. */
	Gen_Value1 = Gen_param1;
	Gen_Value2 = Gen_param2;

	/* Compare the two values. */
	Gen_cc = Gen_Value1->col1 - Gen_Value2->col1;
	if( Gen_cc )
	{
		return Gen_cc < 0 ? -1 : 1;
	}
	
	/* Perform the operation on each of the array elements. */
	for( Gen_Index10 = -1; ++Gen_Index10 < 10; )
	{
		/* Compare the two values. */
		Gen_cc = Gen_Value1->col2[Gen_Index10] - Gen_Value2->col2[Gen_Index10];
		if( Gen_cc )
		{
			return Gen_cc < 0 ? -1 : 1;
		}
	}
	

	/* Close the connection. */
	mi_close( Gen_Con );

	return 0;
}
/* }}FUNCTION (#T03F) */



/* {{FUNCTION(156f1453-557d-11d3-b686-00a024e37610) (MergeSection) */

/*******************************************************************************
**
** Function name:
**
**	FIXTypeEqual
**
** Description:
**
**	Determine if one UDT value is equal to another.
**
** Special Comments:
**
**	Compares two fixed-sized opaque types for equality
**
** Parameters:
**
**	FIXType *          Gen_param1;    The first UDT value to compare.
**	FIXType *          Gen_param2;    The second UDT value to compare.
**	MI_FPARAM *        Gen_fparam;    Standard info - see DBDK docs.
**
** Return value:
**
**	mi_boolean                        The comparison result.
**
** History:
**
**	08/24/1999 - Generated by BladeSmith Version 4.00.TC1B.
**
** Identification:
**
**	Warning: Do not remove or modify this comment:
**	    FIXTypeEqual FunctionId: 156f1453-557d-11d3-b686-00a024e37610
**
********************************************************************************
*/

UDREXPORT
mi_boolean
FIXTypeEqual
(
FIXType *                    Gen_param1,      /* The first UDT value to compare.         */
FIXType *                    Gen_param2,      /* The second UDT value to compare.        */
MI_FPARAM *                  Gen_fparam       /* Standard info - see DBDK docs.          */
)
{
	/* Call Compare to perform the comparison. */
	return (mi_boolean)(0 == FIXTypeCompare( Gen_param1,
			Gen_param2, Gen_fparam ));
}
/* }}FUNCTION (#U9OA) */



/* {{FUNCTION(156f1454-557d-11d3-b686-00a024e37610) (MergeSection) */

/*******************************************************************************
**
** Function name:
**
**	FIXTypeNotEqual
**
** Description:
**
**	Determine if one UDT value is not equal to another.
**
** Special Comments:
**
**	Compares two fixed-sized opaque types for non-equality
**
** Parameters:
**
**	FIXType *          Gen_param1;    The first UDT value to compare.
**	FIXType *          Gen_param2;    The second UDT value to compare.
**	MI_FPARAM *        Gen_fparam;    Standard info - see DBDK docs.
**
** Return value:
**
**	mi_boolean                        The comparison result.
**
** History:
**
**	08/24/1999 - Generated by BladeSmith Version 4.00.TC1B.
**
** Identification:
**
**	Warning: Do not remove or modify this comment:
**	    FIXTypeNotEqual FunctionId: 156f1454-557d-11d3-b686-00a024e37610
**
********************************************************************************
*/

UDREXPORT
mi_boolean
FIXTypeNotEqual
(
FIXType *                    Gen_param1,      /* The first UDT value to compare.         */
FIXType *                    Gen_param2,      /* The second UDT value to compare.        */
MI_FPARAM *                  Gen_fparam       /* Standard info - see DBDK docs.          */
)
{
	/* Call Compare to perform the comparison. */
	return (mi_boolean)(0 != FIXTypeCompare( Gen_param1,
			Gen_param2, Gen_fparam ));
}
/* }}FUNCTION (#I3GO) */



/* {{FUNCTION(156f1450-557d-11d3-b686-00a024e37610) (MergeSection) */

/*******************************************************************************
**
** Function name:
**
**	FIXTypeImportText
**
** Description:
**
**	The import function enables bulk copy for user-defined types.
**	When the  LOAD statement is  used from  dbaccess to copy data
**	from a file  into the database, the  server calls the  import
**	function to convert the  incoming  value  to the data  type's
**	internal format.
**
** Special Comments:
**
**	Support routine for opaque type FIXType returns FIXType.
**
** Parameters:
**
**	mi_impexp *        Gen_param1;    Pointer to the input text.
**	MI_FPARAM *        Gen_fparam;    Standard info - see DBDK docs.
**
** Return value:
**
**	FIXType *                         The constructed UDT value.
**
** History:
**
**	08/24/1999 - Generated by BladeSmith Version 4.00.TC1B.
**
** Identification:
**
**	Warning: Do not remove or modify this comment:
**	    FIXTypeImportText FunctionId: 156f1450-557d-11d3-b686-00a024e37610
**
********************************************************************************
*/

UDREXPORT
FIXType *
FIXTypeImportText
(
mi_impexp *                  Gen_param1,                                                 /* The import text.                  */
MI_FPARAM *                  Gen_fparam                                                  /* Standard info - see DBDK docs.    */
)
{
	MI_CONNECTION *      Gen_Con;         /* The current connection.                 */
	gl_mchar_t *         Gen_InData;                                                 /* Pointer to the input data.        */
	gl_mchar_t *         Gen_StartInData;                                            /* First value of Gen_InData.       */
	FIXType *            Gen_OutData;                                                /* Pointer to the output data.       */
	mi_integer           Gen_DataLen;                                                /* Length of the data in bytes.      */
	FIXType *            Gen_RetVal;                                                 /* The return value.                 */
mi_integer           Gen_Index10;

	/* Get the current connection handle. */
	Gen_Con = mi_open( NULL, NULL, NULL );

	/* Verify that the connection has been established. */
	if( Gen_Con == 0 )
	{
		/*
		** Opening the current connection has failed
		** so issue the following message and quit.
		**
		** 	"Connection has failed in FIXTypeImportText."
		*/
		DBDK_TRACE_ERROR( "FIXTypeImportText", ERRORMESG1, 10 );

		/* not reached */
	}

	/* Point to the input data. */
	Gen_InData = (gl_mchar_t *)mi_get_vardata( (mi_lvarchar *) Gen_param1 );
	Gen_StartInData = Gen_InData;

	/* Get the length of the input string. */
	Gen_DataLen = mi_get_varlen( (mi_lvarchar *)Gen_param1 );

	/* Allocate a new UDT for the return result. */
	Gen_RetVal = (FIXType *)mi_alloc( sizeof( FIXType ) );
	if( Gen_RetVal == 0 )
	{
		/*
		** Memory allocation has failed so issue
		** the following message and quit.
		**
		** 	"Memory allocation has failed in FIXTypeImportText."
		*/
		DBDK_TRACE_ERROR( "FIXTypeImportText", ERRORMESG2, 10 );

		/* not reached */
	}

	/* Point to the output data. */
	Gen_OutData = (FIXType *)Gen_RetVal;

	/* Get the mi_integer value for col1. */
	Gen_InData = Gen_sscanf( Gen_Con, "FIXTypeImportText", Gen_InData,
	                         Gen_DataLen - (Gen_InData - Gen_StartInData),
	                         0, "%d %n", (char *)&Gen_OutData->col1 );
	
	/* Perform the operation on each of the array elements. */
	for( Gen_Index10 = -1; ++Gen_Index10 < 10; )
	{
		/* Get the mi_char value for col2[Gen_Index10]. */
		Gen_InData = Gen_sscanf( Gen_Con, "FIXTypeImportText", Gen_InData,
		                         Gen_DataLen - (Gen_InData - Gen_StartInData),
		                         0, "%c %n", (char *)&Gen_OutData->col2[Gen_Index10] );
	}
	

	/* Close the connection. */
	mi_close( Gen_Con );

	/* Return the UDT value. */
	return Gen_RetVal;
}
/* }}FUNCTION (#ONRO) */



/* {{FUNCTION(156f1451-557d-11d3-b686-00a024e37610) (MergeSection) */

/*******************************************************************************
**
** Function name:
**
**	FIXTypeExportText
**
** Description:
**
**	The export function enables bulk copy for user-defined types.
**	When the UNLOAD statement is used from  dbaccess to copy data
**	from  the  database to a  file, the  server calls the  export
**	function  to convert the outcoming  value to the data  type's
**	external format.
**
** Special Comments:
**
**	Support routine for opaque type FIXType returns mi_impexp.
**
** Parameters:
**
**	FIXType *          Gen_param1;    Pointer to the input text.
**	MI_FPARAM *        Gen_fparam;    Standard info - see DBDK docs.
**
** Return value:
**
**	mi_impexp *                       The exported UDT value.
**
** History:
**
**	08/24/1999 - Generated by BladeSmith Version 4.00.TC1B.
**
** Identification:
**
**	Warning: Do not remove or modify this comment:
**	    FIXTypeExportText FunctionId: 156f1451-557d-11d3-b686-00a024e37610
**
********************************************************************************
*/

UDREXPORT
mi_impexp *
FIXTypeExportText
(
FIXType *                    Gen_param1,      /* The UDT value.                          */
MI_FPARAM *                  Gen_fparam       /* Standard info - see DBDK docs.          */
)
{
	MI_CONNECTION *      Gen_Con;         /* The current connection.                 */
	mi_integer           Gen_CharLen;     /* Estimate maximum length.                */
	FIXType *            Gen_InData;      /* Pointer to the input data.              */
	char *               Gen_OutData;     /* Pointer to the output data.             */
	mi_impexp *          Gen_RetVal;      /* The return result.                      */
mi_integer           Gen_Index10;
	mi_integer           Gen_DataLen;     /* The data length.                        */
	/* Get the current connection handle. */
	Gen_Con = mi_open( NULL, NULL, NULL );

	/* Verify that the connection has been established. */
	if( Gen_Con == 0 )
	{
		/*
		** Opening the current connection has failed
		** so issue the following message and quit.
		**
		** 	"Connection has failed in FIXTypeExportText."
		*/
		DBDK_TRACE_ERROR( "FIXTypeExportText", ERRORMESG1, 10 );

		/* not reached */
	}

	/* Point to the input data. */
	Gen_InData = Gen_param1;

	/* Compute the maximum length of the text representation. */
	Gen_CharLen         =   1              /* Leave room for the NULL terminator. */
	               + 12             /* Add the length for col1. */
	               + 10 * 2          /* Add the length for col2. */
		            ;

	/* Allocate the output parcel. */
	Gen_RetVal = (mi_impexp *)mi_new_var( Gen_CharLen );
	if( Gen_RetVal == 0 )
	{
		/*
		** Memory allocation has failed so issue
		** the following message and quit.
		**
		** 	"Memory allocation has failed in FIXTypeExportText."
		*/
		DBDK_TRACE_ERROR( "FIXTypeExportText", ERRORMESG2, 10 );

		/* not reached */
	}

	/* Point to the output data. */
	Gen_OutData = mi_get_vardata( (mi_lvarchar *)Gen_RetVal );

	/* Format the attribute value into the output string. */

	/* Format the mi_integer value for col1. */
	sprintf( Gen_OutData, "%d ", Gen_InData->col1 );
	Gen_OutData += strlen( Gen_OutData );
	
	/* Perform the operation on each of the array elements. */
	for( Gen_Index10 = -1; ++Gen_Index10 < 10; )
	{
		/* Format the mi_char value for col2[Gen_Index10]. */
		sprintf( Gen_OutData, "%c ", Gen_InData->col2[Gen_Index10] );
		Gen_OutData += strlen( Gen_OutData );
	}
	

	/*
	** Compute the length of the data and
	** place it in the return structure.
	*/
	Gen_DataLen = (mi_integer)(Gen_OutData - mi_get_vardata( (mi_lvarchar *) Gen_RetVal ));
	mi_set_varlen ( (mi_lvarchar *) Gen_RetVal, Gen_DataLen );

	/* Close the connection. */
	mi_close( Gen_Con );

	/* Return the UDT value. */
	return Gen_RetVal;
}
/* }}FUNCTION (#19I5) */



/* {{FUNCTION(156f1455-557d-11d3-b686-00a024e37610) (MergeSection) */

/*******************************************************************************
**
** Function name:
**
**	FIXTypeInput
**
** Description:
**
**	This function converts from the external representation of the
**	UDT type FIXType to its internal representation.   The external
**	representation is a blank-separated list of values and the
**	internal representation is a 'C' structure of type FIXType as
**	defined in the header file.
**
**
**	Data can be inserted into a table using an SQL insert statement:
**
**		insert into tablename values ( 'value-list' );
**
**	value-list is a space-delimited list of values.
**
**	Data for the mi_integer type is in the range
**	[-2,147,483,647, +2,147,483,647].
**
** Special Comments:
**
**	Support routine for opaque type FIXType returns FIXType.
**
** Parameters:
**
**	mi_lvarchar *      Gen_param1;    Pointer to the input text.
**	MI_FPARAM *        Gen_fparam;    Standard info - see DBDK docs.
**
** Return value:
**
**	FIXType *                         The constructed UDT value.
**
** History:
**
**	08/24/1999 - Generated by BladeSmith Version 4.00.TC1B.
**
** Identification:
**
**	Warning: Do not remove or modify this comment:
**	    FIXTypeInput FunctionId: 156f1455-557d-11d3-b686-00a024e37610
**
********************************************************************************
*/

UDREXPORT
FIXType *
FIXTypeInput
(
mi_lvarchar *                Gen_param1,                                                 /* Pointer to the input text.        */
MI_FPARAM *                  Gen_fparam                                                  /* Standard info - see DBDK docs.    */
)
{
	MI_CONNECTION *      Gen_Con;         /* The current connection.                 */
	gl_mchar_t *         Gen_InData;                                                 /* Pointer to the input data.        */
	gl_mchar_t *         Gen_StartInData;                                            /* First value of Gen_InData.       */
	FIXType *            Gen_OutData;                                                /* Pointer to the output data.       */
	mi_integer           Gen_DataLen;                                                /* Length of the data in bytes.      */
	FIXType *            Gen_RetVal;                                                 /* The return value.                 */
mi_integer           Gen_Index10;

	/* Get the current connection handle. */
	Gen_Con = mi_open( NULL, NULL, NULL );

	/* Verify that the connection has been established. */
	if( Gen_Con == 0 )
	{
		/*
		** Opening the current connection has failed
		** so issue the following message and quit.
		**
		** 	"Connection has failed in FIXTypeInput."
		*/
		DBDK_TRACE_ERROR( "FIXTypeInput", ERRORMESG1, 10 );

		/* not reached */
	}

	/* Point to the input data. */
	Gen_InData = (gl_mchar_t *)mi_get_vardata( (mi_lvarchar *) Gen_param1 );
	Gen_StartInData = Gen_InData;

	/* Get the length of the input string. */
	Gen_DataLen = mi_get_varlen( Gen_param1 );

	/* Allocate a new UDT for the return result. */
	Gen_RetVal = (FIXType *)mi_alloc( sizeof( FIXType ) );
	if( Gen_RetVal == 0 )
	{
		/*
		** Memory allocation has failed so issue
		** the following message and quit.
		**
		** 	"Memory allocation has failed in FIXTypeInput."
		*/
		DBDK_TRACE_ERROR( "FIXTypeInput", ERRORMESG2, 10 );

		/* not reached */
	}

	/* Point to the output data. */
	Gen_OutData = (FIXType *)Gen_RetVal;

	/* Get the mi_integer value for col1. */
	Gen_InData = Gen_sscanf( Gen_Con, "FIXTypeInput", Gen_InData,
	                         Gen_DataLen - (Gen_InData - Gen_StartInData),
	                         0, "%d %n", (char *)&Gen_OutData->col1 );
	
	/* Perform the operation on each of the array elements. */
	for( Gen_Index10 = -1; ++Gen_Index10 < 10; )
	{
		/* Get the mi_char value for col2[Gen_Index10]. */
		Gen_InData = Gen_sscanf( Gen_Con, "FIXTypeInput", Gen_InData,
		                         Gen_DataLen - (Gen_InData - Gen_StartInData),
		                         0, "%c %n", (char *)&Gen_OutData->col2[Gen_Index10] );
	}
	

	/* Close the connection. */
	mi_close( Gen_Con );

	/* Return the UDT value. */
	return Gen_RetVal;
}
/* }}FUNCTION (#RMUE) */



/* {{FUNCTION(156f144b-557d-11d3-b686-00a024e37610) (MergeSection) */

/*******************************************************************************
**
** Function name:
**
**	FIXTypeOutput
**
** Description:
**
**	This function converts from the internal representation of the
**	UDT type FIXType to its external representation.   The external
**	representation is a blank-separated list of values and the
**	internal representation is a 'C' structure of type FIXType as
**	defined in the header file.
**
**	Data can be retrieved from a table using an SQL select statement:
**
**		select * from tablename;
**
**	Data for the mi_integer type is in the range
**	[-2,147,483,647, +2,147,483,647].
**
** Special Comments:
**
**	Support routine for opaque type FIXType returns mi_lvarchar.
**
** Parameters:
**
**	FIXType *          Gen_param1;    Pointer to the input text.
**	MI_FPARAM *        Gen_fparam;    Standard info - see DBDK docs.
**
** Return value:
**
**	mi_lvarchar *                     The constructed UDT value.
**
** History:
**
**	08/24/1999 - Generated by BladeSmith Version 4.00.TC1B.
**
** Identification:
**
**	Warning: Do not remove or modify this comment:
**	    FIXTypeOutput FunctionId: 156f144b-557d-11d3-b686-00a024e37610
**
********************************************************************************
*/

UDREXPORT
mi_lvarchar *
FIXTypeOutput
(
FIXType *                    Gen_param1,    /* The UDT value.                */
MI_FPARAM *                  Gen_fparam     /* Standard info - see DBDK docs.*/
)
{
        MI_CONNECTION * Gen_Con;           /* The current connection.        */
        mi_integer      Gen_CharLen;       /* Estimate maximum length.       */
        FIXType *       Gen_InData;        /* Pointer to the input data.     */
        char *          Gen_OutData;       /* Pointer to the output data.    */
        mi_lvarchar *   Gen_RetVal;        /* The return result.             */
        mi_integer      Gen_DataLen;       /* The data length.               */
        mi_integer      Gen_Index1;        /* Array index.                   */
 
        /* Get the current connection handle. */
        Gen_Con = mi_open( NULL, NULL, NULL );
        /* Verify that the connection has been established. */
        if( Gen_Con == 0 )
        {
                /*
                ** Opening the current connection has failed
                ** so issue the following message and quit.
                **
                **      "Connection has failed in FIXTypeOutput."
                */
                mi_db_error_raise( Gen_Con, MI_SQL, ERRORMESG1,
                        "FUNCTION%s", "FIXTypeOutput", (char *)NULL );
 
                /* not reached */
        }
 
        /* Compute the maximum length of the text representation. */
        Gen_CharLen =    1;      /* Leave room for the NULL terminator.      */
        Gen_CharLen +=  10;      /* Add the length for Gen_OutData->col1.    */
        Gen_CharLen += 10 *   2; /* Add the length for Gen_OutData->col2[].  */
 
        /* Allocate room for the output string. */
        Gen_RetVal = mi_new_var( Gen_CharLen );
        if( Gen_RetVal == 0 )
        {
                /*
                ** Memory allocation has failed so issue
                ** the following message and quit.
                **
                **      "Memory allocation has failed in FIXTypeOutput."
                */
                mi_db_error_raise( Gen_Con, MI_SQL, ERRORMESG2,
                        "FUNCTION%s", "FIXTypeOutput", (char *)NULL );
 
                /* not reached */
        }
 
        /* Point to the input data. */
        Gen_InData = Gen_param1;
 
        /* Point to the output data. */
        Gen_OutData = mi_get_vardata( Gen_RetVal );
 
        /* Format the attribute value into the output string. */
 
        /* Format the value for Gen_InData.*/
        if (sprintf( Gen_OutData, "%d\t%s", Gen_InData->col1,
                Gen_InData->col2 ) < 0)
        {
                mi_db_error_raise( Gen_Con, MI_SQL, ERRORMESG11,
                        "FUNCTION%s", "FIXOutPut", (char *)NULL );
        }
        /*
        ** Compute the length of the data and
        ** place it in the return structure.
        */
        Gen_DataLen = (mi_integer)(strlen(Gen_OutData));
        mi_set_varlen ( Gen_RetVal, Gen_DataLen );
        mi_set_vardata ( Gen_RetVal, Gen_OutData );
 
        /* Close the connection. */
        mi_close( Gen_Con );
 
        return Gen_RetVal;
}
/* }}FUNCTION (#PNNA) */



#ifdef __cplusplus

}

#endif
