-- Generated by BladeSmith 4.00.TC2  DO NOT MODIFY. --

execute procedure ifx_allow_newline('t');

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "SblobStatSize (blob)",
	"%SYSBLDUSER%", 0,
	"create function SblobStatSize (blob)
returns int8
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/sblob_info.bld(SblobStatSize)"" language c;

",
	"f",
	"drop function SblobStatSize (blob);

",
	"f"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-SblobStatSize (blob)",
	"%SYSBLDUSER%", 0,
	"alter function SblobStatSize (blob)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/sblob_info.bld(SblobStatSize)"");

",
	"f",
	"alter function SblobStatSize (blob)
	with (Modify External Name = ""SblobStatSize"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-SblobStatSize (blob)",
	"%SYSBLDUSER%",
	5, "SblobStatSize (blob)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "SblobStatSize (blob)",
	"%SYSBLDUSER%", 0,
	"grant execute on function SblobStatSize (blob) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "SblobStatSize (blob)",
	"%SYSBLDUSER%",
	5, "SblobStatSize (blob)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 6, "SblobDebug (integer)",
	"%SYSBLDUSER%", 0,
	"create procedure SblobDebug (integer)
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/sblob_info.bld(SblobDebug)"" language c;

",
	"f",
	"drop procedure SblobDebug (integer);

",
	"f"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 182, "Alter-ExternalName-SblobDebug (integer)",
	"%SYSBLDUSER%", 0,
	"alter procedure SblobDebug (integer)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/sblob_info.bld(SblobDebug)"");

",
	"f",
	"alter procedure SblobDebug (integer)
	with (Modify External Name = ""SblobDebug"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	182, "Alter-ExternalName-SblobDebug (integer)",
	"%SYSBLDUSER%",
	6, "SblobDebug (integer)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 70, "SblobDebug (integer)",
	"%SYSBLDUSER%", 0,
	"grant execute on procedure SblobDebug (integer) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	70, "SblobDebug (integer)",
	"%SYSBLDUSER%",
	6, "SblobDebug (integer)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "SblobSbspace (blob)",
	"%SYSBLDUSER%", 0,
	"create function SblobSbspace (blob)
returns lvarchar
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/sblob_info.bld(SblobSbspace)"" language c;

",
	"f",
	"drop function SblobSbspace (blob);

",
	"f"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-SblobSbspace (blob)",
	"%SYSBLDUSER%", 0,
	"alter function SblobSbspace (blob)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/sblob_info.bld(SblobSbspace)"");

",
	"f",
	"alter function SblobSbspace (blob)
	with (Modify External Name = ""SblobSbspace"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-SblobSbspace (blob)",
	"%SYSBLDUSER%",
	5, "SblobSbspace (blob)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "SblobSbspace (blob)",
	"%SYSBLDUSER%", 0,
	"grant execute on function SblobSbspace (blob) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "SblobSbspace (blob)",
	"%SYSBLDUSER%",
	5, "SblobSbspace (blob)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "SblobMaxSize (blob)",
	"%SYSBLDUSER%", 0,
	"create function SblobMaxSize (blob)
returns int8
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/sblob_info.bld(SblobMaxSize)"" language c;

",
	"f",
	"drop function SblobMaxSize (blob);

",
	"f"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-SblobMaxSize (blob)",
	"%SYSBLDUSER%", 0,
	"alter function SblobMaxSize (blob)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/sblob_info.bld(SblobMaxSize)"");

",
	"f",
	"alter function SblobMaxSize (blob)
	with (Modify External Name = ""SblobMaxSize"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-SblobMaxSize (blob)",
	"%SYSBLDUSER%",
	5, "SblobMaxSize (blob)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "SblobMaxSize (blob)",
	"%SYSBLDUSER%", 0,
	"grant execute on function SblobMaxSize (blob) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "SblobMaxSize (blob)",
	"%SYSBLDUSER%",
	5, "SblobMaxSize (blob)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "SblobEstSize (blob)",
	"%SYSBLDUSER%", 0,
	"create function SblobEstSize (blob)
returns int8
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/sblob_info.bld(SblobEstSize)"" language c;

",
	"f",
	"drop function SblobEstSize (blob);

",
	"f"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-SblobEstSize (blob)",
	"%SYSBLDUSER%", 0,
	"alter function SblobEstSize (blob)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/sblob_info.bld(SblobEstSize)"");

",
	"f",
	"alter function SblobEstSize (blob)
	with (Modify External Name = ""SblobEstSize"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-SblobEstSize (blob)",
	"%SYSBLDUSER%",
	5, "SblobEstSize (blob)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "SblobEstSize (blob)",
	"%SYSBLDUSER%", 0,
	"grant execute on function SblobEstSize (blob) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "SblobEstSize (blob)",
	"%SYSBLDUSER%",
	5, "SblobEstSize (blob)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "SblobExtSize (blob)",
	"%SYSBLDUSER%", 0,
	"create function SblobExtSize (blob)
returns integer
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/sblob_info.bld(SblobExtSize)"" language c;

",
	"f",
	"drop function SblobExtSize (blob);

",
	"f"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-SblobExtSize (blob)",
	"%SYSBLDUSER%", 0,
	"alter function SblobExtSize (blob)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/sblob_info.bld(SblobExtSize)"");

",
	"f",
	"alter function SblobExtSize (blob)
	with (Modify External Name = ""SblobExtSize"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-SblobExtSize (blob)",
	"%SYSBLDUSER%",
	5, "SblobExtSize (blob)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "SblobExtSize (blob)",
	"%SYSBLDUSER%", 0,
	"grant execute on function SblobExtSize (blob) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "SblobExtSize (blob)",
	"%SYSBLDUSER%",
	5, "SblobExtSize (blob)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "SblobCreate (lvarchar,int8,lvarchar,int8,int8)",
	"%SYSBLDUSER%", 0,
	"create function SblobCreate (lvarchar,int8,lvarchar,int8,int8)
returns blob
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/sblob_info.bld(SblobCreate_5args)"" language c;

",
	"f",
	"drop function SblobCreate (lvarchar,int8,lvarchar,int8,int8);

",
	"f"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-SblobCreate (lvarchar,int8,lvarchar,int8,int8)",
	"%SYSBLDUSER%", 0,
	"alter function SblobCreate (lvarchar,int8,lvarchar,int8,int8)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/sblob_info.bld(SblobCreate_5args)"");

",
	"f",
	"alter function SblobCreate (lvarchar,int8,lvarchar,int8,int8)
	with (Modify External Name = ""SblobCreate_5args"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-SblobCreate (lvarchar,int8,lvarchar,int8,int8)",
	"%SYSBLDUSER%",
	5, "SblobCreate (lvarchar,int8,lvarchar,int8,int8)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "SblobCreate (lvarchar,int8,lvarchar,int8,int8)",
	"%SYSBLDUSER%", 0,
	"grant execute on function SblobCreate (lvarchar,int8,lvarchar,int8,int8) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "SblobCreate (lvarchar,int8,lvarchar,int8,int8)",
	"%SYSBLDUSER%",
	5, "SblobCreate (lvarchar,int8,lvarchar,int8,int8)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "SblobUpdate (blob,int8,lvarchar)",
	"%SYSBLDUSER%", 0,
	"create function SblobUpdate (blob,int8,lvarchar)
returns integer
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/sblob_info.bld(SblobUpdate_3args)"" language c;

",
	"f",
	"drop function SblobUpdate (blob,int8,lvarchar);

",
	"f"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-SblobUpdate (blob,int8,lvarchar)",
	"%SYSBLDUSER%", 0,
	"alter function SblobUpdate (blob,int8,lvarchar)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/sblob_info.bld(SblobUpdate_3args)"");

",
	"f",
	"alter function SblobUpdate (blob,int8,lvarchar)
	with (Modify External Name = ""SblobUpdate_3args"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-SblobUpdate (blob,int8,lvarchar)",
	"%SYSBLDUSER%",
	5, "SblobUpdate (blob,int8,lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "SblobUpdate (blob,int8,lvarchar)",
	"%SYSBLDUSER%", 0,
	"grant execute on function SblobUpdate (blob,int8,lvarchar) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "SblobUpdate (blob,int8,lvarchar)",
	"%SYSBLDUSER%",
	5, "SblobUpdate (blob,int8,lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "SblobLog (blob)",
	"%SYSBLDUSER%", 0,
	"create function SblobLog (blob)
returns boolean
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/sblob_info.bld(SblobLog)"" language c;

",
	"f",
	"drop function SblobLog (blob);

",
	"f"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-SblobLog (blob)",
	"%SYSBLDUSER%", 0,
	"alter function SblobLog (blob)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/sblob_info.bld(SblobLog)"");

",
	"f",
	"alter function SblobLog (blob)
	with (Modify External Name = ""SblobLog"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-SblobLog (blob)",
	"%SYSBLDUSER%",
	5, "SblobLog (blob)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "SblobLog (blob)",
	"%SYSBLDUSER%", 0,
	"grant execute on function SblobLog (blob) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "SblobLog (blob)",
	"%SYSBLDUSER%",
	5, "SblobLog (blob)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "SblobRefCount (blob)",
	"%SYSBLDUSER%", 0,
	"create function SblobRefCount (blob)
returns integer
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/sblob_info.bld(SblobRefCount)"" language c;

",
	"f",
	"drop function SblobRefCount (blob);

",
	"f"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-SblobRefCount (blob)",
	"%SYSBLDUSER%", 0,
	"alter function SblobRefCount (blob)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/sblob_info.bld(SblobRefCount)"");

",
	"f",
	"alter function SblobRefCount (blob)
	with (Modify External Name = ""SblobRefCount"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-SblobRefCount (blob)",
	"%SYSBLDUSER%",
	5, "SblobRefCount (blob)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "SblobRefCount (blob)",
	"%SYSBLDUSER%", 0,
	"grant execute on function SblobRefCount (blob) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "SblobRefCount (blob)",
	"%SYSBLDUSER%",
	5, "SblobRefCount (blob)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 0, "sysbldregistered",
	"%SYSBLDUSER%", 0,
	"insert into sysbldregistered
	(bld_id)
values
(
	""%SYSBLDNAME%""
);

",
	"f",
	"delete from sysbldregistered
	where bld_id = ""%SYSBLDNAME%"";

",
	"f"
);

