-- Generated by BladeSmith 4.00.TC1B2DO NOT MODIFY. --

execute procedure ifx_allow_newline('t');

insert into sysblddescription
	(bld_id, blocale_id, bdesc_format, bvendor_id, bdesc_desc, bdesc_copyright)
values
(
	"%SYSBLDNAME%",
	"en_us.1252",
	0,
	"informix",
	"Implements a simple variable-length data type that will be used to demonstrate how to
send a large chunk of binary data from a client application to a server routine.",
	"Copyright (c) Informix Software"
);

delete from sysbldvendors
	where bvendor_id = "informix" and
	bvendor_format = 0 and
	blocale_id = "en_us.1252";

insert into sysbldvendors
	(bvendor_id, bvendor_name, blocale_id, bvendor_format, bvendor_desc)
values
(
	"informix",
	"Informix",
	"en_us.1252",
	0,
	""
);

