/*
** Title:          support.c
** SCCSid:         %W% %E% %U%
** CCid:           %W% %E% %U%
** Author:         Informix
** Created:        08/19/1999 11:04
** Description:    This is the generated support 'C' file.
** Comments:     
**                 This file contains all the support routines needed for the
**                 DataBlade.
**                 Changes should not be made to this file since this file is
**                 always regenerated.
*/

/*
**  The following is placed here to insure
**  that name "mangling" does not occur.
*/
#ifdef __cplusplus

extern "C"
{

#endif

/* Standard library includes. */
#include <ctype.h>
#include <stdio.h>
#include <string.h>
#include <stddef.h>

/* Used by Informix GLS routines. */
#include <ifxgls.h>

/* Include when accessing the Informix API. */
#include <mi.h>

/* This is the project include file. */
#include "TraceDemo.h"


/* {{FUNCTION(11190130-cf56-11d1-9ce6-080015e6b366) (CopySection) */
/*******************************************************************************
**
** Function name:
**
**	Gen_nstrwords
**
** Description:
**
**	This function counts the number of values in a formatted string.
**
** Parameters:
**
**	gl_mchar_t *       Gen_InData                   The data to scan.
**	mi_integer         Gen_InDataLen                Length of the data.
**
** Return value:
**
**	mi_integer                                      The new scan position.
**
** History:
**
**	08/19/1999 - Generated by BladeSmith Version 4.00.TC1B.
**
** Identification:
**
**	Warning: Do not remove or modify this comment:
**	    Gen_nstrwords FunctionId: 3AC0E361-5A81-11d0-A2E7-00AA0009BF87
**
********************************************************************************
*/
mi_integer
Gen_nstrwords
(
gl_mchar_t *               Gen_InData,                  /* The data to scan.                      */
mi_integer                 Gen_InDataLen                /* Length of the data.                    */
)
{
	mi_integer         Gen_WordCount;               /* The number of words present.           */
	gl_mchar_t *       Gen_In;                      /* Scanning pointer.                      */
	char *             Gen_DataCopy;                /* A NULL terminated copy.                */
	enum
	{
		DBDK_QUOTE,
		DBDK_ESCAPE,
		DBDK_WORD,
		DBDK_SPACE
	} Gen_state;       /* Parsing state.	*/

	/* Copy the data and NULL terminate it. */
	Gen_DataCopy = (char *)mi_alloc(Gen_InDataLen + 1);
	memcpy(Gen_DataCopy, Gen_InData, Gen_InDataLen);
	Gen_DataCopy[Gen_InDataLen] = (char)'\0';
	Gen_InData = (gl_mchar_t *)Gen_DataCopy;

	/* Begin counting the words. */
	Gen_WordCount = 0;

	/* Set the initial state. */
	Gen_state = DBDK_SPACE;

	/* Point to the beginning of the input text. */
	Gen_In = Gen_InData;

	do
	{
		switch ( Gen_state )
		{
			case DBDK_ESCAPE:
				Gen_state = DBDK_QUOTE;
				break;

			case DBDK_QUOTE:
				if( '\"' == *Gen_In )
				{
					Gen_state = DBDK_SPACE;
				}
				break;

			case DBDK_WORD:
				if( '\"' == *Gen_In )
				{
					Gen_WordCount++, Gen_state = DBDK_QUOTE;
				}
				else if( ifx_gl_ismspace( Gen_In, 4 ) )
				{
					Gen_state = DBDK_SPACE;
				}
				break;

			case DBDK_SPACE:
				if( '\"' == *Gen_In )
				{
					Gen_WordCount++, Gen_state = DBDK_QUOTE;
				}
				else if( !ifx_gl_ismspace( Gen_In, 4 ) )
				{
					Gen_WordCount++, Gen_state = DBDK_WORD;
				}
				break;
		}

		/* Advance the pointer. */
		Gen_In = ifx_gl_mbsnext( Gen_In, 4 );
	}
	while( *Gen_In != '\0' );

	/* Free the copy of the data. */
	mi_free(Gen_DataCopy);

	return Gen_WordCount;
}
/* }}FUNCTION (#DJUM) */


/* {{FUNCTION(11190130-cf56-11d1-9ce6-080025e6b366) (CopySection) */
/*******************************************************************************
**
** Function name:
**
**	Gen_Trace
**
** Description:
**
**	This function writes trace information to the trace file.
**
**	Complete information about tracing may be found in
**	the INFORMIX-DataBlade API, User's Guide, Version 9.0.
**
**	To enable tracing, you must first create a trace class
**	by inserting a record into the systraceclasses system
**	catalog:
**
**		insert into informix.systraceclasses(name)
**		values('TraceDemo');
**
**	The name of the trace file must be set. If the file name
**	is not set, the server uses a default file name:
**	the session id followed by ".trc" in the /tmp directory.
**	Use "onstat -g ses" to get the session id.
**
**	The following code snippet may be used to set the name
**	of the output trace file from within your code.
**
**		mi_tracefile_set( "/yourpath/yourfile.trc" );
**
**	Alternately, the TraceSet_TraceDemo procedure may be
**	used from SQL to set the trace file name and trace threshold
**	level.  See this procedure for more details.
**
**	To insure that tracing text  actually  appears in the
**	output trace file, SERVER_LOCALE, CLIENT_LOCALE,  and
**	DB_LOCALE must be set in the environment to the
**	appropriate locale (e.g., "en_us.1252").
**
** Parameters:
**
**	MI_CONNECTION *    Gen_Con        The database connection.
**	char *             Gen_Caller     Call originated from this routine.
**	char *             Gen_FileName   Call originated in this file.
**	mi_integer         Gen_LineNo     Call originated on this line.
**	char *             Gen_MsgNo      ERRORMESG number.
**	char *             Gen_Class      Tracing class.
**	mi_integer         Gen_Threshold  Tracing threshold.
**	mi_integer         Gen_MsgType    MI_SQL | MI_MESSAGE | DBDK_TRACE.
**
** Return value:
**
**	None.
**
** History:
**
**	08/19/1999 - Generated by BladeSmith Version 4.00.TC1B.
**
** Identification:
**
**	Warning: Do not remove or modify this comment:
**	    Gen_Trace FunctionId: 59DEDB71-760B-11d0-A2EC-00AA0009BF87
**
********************************************************************************
*/
void
Gen_Trace
(
MI_CONNECTION *            Gen_Con,                     /* The database connection.               */
char *                     Gen_Caller,                  /* Call originated from this routine.     */
char *                     Gen_FileName,                /* Call originated in this file.          */
mi_integer                 Gen_LineNo,                  /* Call originated on this line.          */
char *                     Gen_MsgNo,                   /* ERRORMESG number.                      */
char *                     Gen_Class,                   /* Tracing class.                         */
mi_integer                 Gen_Threshold,               /* Tracing threshold.                     */
mi_integer                 Gen_MsgType                  /* MI_SQL | MI_MESSAGE | DBDK_TRACE.      */
)
{
	MI_CONNECTION *    Gen_TraceCon;  /* The database connection.           */

	/* Route the message to the trace file? */
	if( Gen_MsgType & DBDK_TRACE )
	{
		/* Write the message to the trace file. */
		GL_DPRINTF( Gen_Class,
			    Gen_Threshold,
			    (
			        Gen_MsgNo,
			        "FUNCTION%s", Gen_Caller,      /* Substitute the caller here.    */
			        "FILENAME%s", Gen_FileName,    /* Substitute the file name here. */
			        "LINENO%d",   Gen_LineNo,      /* Substitute the line info here. */
			        MI_LIST_END                    /* Terminate the list!!           */
			    )
			  );
	}

	/* Mask off the mi_db_error_raise flags. */
	Gen_MsgType &= 0xffff;

	/* Route the message back to the user? */
	if( Gen_MsgType )
	{
		/*
		** Obtain a connection for mi_db_error_raise.
		** If available, use the connection that  has
		** already been established.
		*/
		if( Gen_Con == NULL )
		{
			/* No connection is available so open a new one. */
			Gen_TraceCon = mi_open( NULL, NULL, NULL );
		}
		else
		{
			Gen_TraceCon = Gen_Con;
		}

		/* If requested, also write the message to the user. */
		mi_db_error_raise( Gen_TraceCon,               /* This is the connection handle. */
			           Gen_MsgType,                /* Route to the user.             */
			           Gen_MsgNo,                  /* Print this message.            */
			           "FUNCTION%s", Gen_Caller,   /* Substitute the caller here.    */
			           (char *)NULL );             /* Terminator.                    */

		/*
		** mi_db_error_raise may not return
		** and this line may not be reached.
		*/
	}
}
/* }}FUNCTION (#Q4FA) */


/* {{FUNCTION(11190130-cf56-11d1-9ce6-080050e6b366) (CopySection) */
/*******************************************************************************
**
** Function name:
**
**	TraceSet_TraceDemo
**
** Description:
**
**	This function may be called from  SQL  to set the name of the trace
**	output file and the trace  threshold  level.  Tracing  is  disabled
**	until the tracing  threshold level is set to a value that  is >= 0.
**	The default name of the trace output file is /tmp/<session_id>.trc.
**	The session id may be determined by running "onstat -g ses".
**
**	Normally, this  function is not registered by  the scripts  created
**	by  BladeSmith.  This  effectively hides  this  debugging  function
**	from end-users. To register and make this function  available,  use
**	the following SQL:
**
**		CREATE PROCEDURE TraceSet_TraceDemo
**		(
**			lvarchar,
**			int
**		)
**		WITH
**		(
**			NOT VARIANT
**		)
**		EXTERNAL NAME "/path/.../TraceDemo.bld(TraceSet_TraceDemo)"
**		LANGUAGE C
**		END PROCEDURE;
**
**	Once registered, call this function by using the following SQL:
**
**		EXECUTE PROCEDURE TraceSet_TraceDemo( "/mypath/myfile", 20 );
**
**	If the file name is empty, the trace file name is not changed.
**	Thus, the following SQL will only modify the trace threshold level:
**
**		EXECUTE PROCEDURE TraceSet_TraceDemo( "", 10 );
**
**	Similarly, the trace threshold level is not  modified if  negative.
**	You should be aware that the trace threshold level is automatically
**	reset to 0 each time a new session is started.
**
**	The EnableTracing.sh and DisableTracing.sh shell scripts can be used
**	to enable and disable tracing.  The MKS Toolkit is required when
**	operating under NT.
**
** Parameters:
**
**	mi_lvarchar *      Gen_TraceFile;               The name of the trace output file.
**	mi_integer         Gen_TraceLevel;              This is the trace level threshold.
**	MI_FPARAM *        Gen_fparam;                  Standard info - see DBDK docs.
**
** Return value:
**
**	void
**
** History:
**
**	08/19/1999 - Generated by BladeSmith Version 4.00.TC1B.
**
** Identification:
**
**	Warning: Do not remove or modify this comment:
**	    TraceSet_TraceDemo FunctionId: 11190130-cf56-11d1-9ce6-080040e6b366
**
********************************************************************************
*/

void TraceSet_TraceDemo
(
mi_lvarchar *                Gen_param,                                                  /* The trace file name.           */
mi_integer                   Gen_TraceLevel,                                             /* Trace level threshold.         */
MI_FPARAM *                  Gen_fparam                                                  /* Standard info - see DBDK docs. */
)
{
	gl_mchar_t *         Gen_TraceFile;                                              /* Trace file name.               */
	char                 Gen_TraceStr[50];                                           /* Tracing level.                 */
	MI_CONNECTION *      Gen_Con = NULL;                                             /* No connection required.        */

	/*
	** Set the name and location  of the  output
	** trace file. If not set, the name defaults
	** to <session id>.trc in the /tmp directory.
	*/
	if( mi_get_varlen( Gen_param ) != 0 )
	{
		/* Point to the NULL-terminated input file name. */
		Gen_TraceFile = (gl_mchar_t *)mi_lvarchar_to_string( Gen_param );

		/* Set the name of the trace file. */
		if( mi_tracefile_set( (char *)Gen_TraceFile ) == -1 )
		{
			/*
			** Opening the trace file has failed
			** so issue the following message and quit.
			**
			** 	"Opening the trace file has failed."
			*/
			DBDK_TRACE_ERROR( "", ERRORMESG18, 10 );

			/* not reached */
		}

		/* Free the allocated memory. */
		mi_free( Gen_TraceFile );
	}

	/*
	** Set the tracing level.  The
	** default tracing level is 0.
	*/
	if( Gen_TraceLevel >= 0 )
	{
		sprintf( Gen_TraceStr, "TraceDemo %d", Gen_TraceLevel );
		if( mi_tracelevel_set( Gen_TraceStr ) == -1 )
		{
			/*
			** Setting the trace threshold has failed
			** so issue the following message and quit.
			**
			** 	"Setting the trace threshold has failed."
			*/
			DBDK_TRACE_ERROR( "", ERRORMESG19, 10 );

			/* not reached */
		}
	}
}
/* }}FUNCTION (#VDQR) */


#ifdef __cplusplus

}

#endif


