-- ---------------------------------------------------------------
-- 
-- Module          : Functional Test for UDT BWA
-- Filename        : cleanup.sql
-- Author          : generated by DBDK
-- PURPOSE
--    Removes test table
-- 
-- ---------------------------------------------------------------

-- start transaction
begin work;


-- drop test table
drop table tst_BWA;


-- end transaction
commit work;

-- ---------------------------------------------------------------
-- EOF                                                            
-- ---------------------------------------------------------------
