-- ---------------------------------------------------------------
-- 
-- Module          : Functional Test for UDT BWA
-- Filename        : greaterthan.sql
-- Author          : generated by DBDK
-- PURPOSE
--    Tests btree support routine 'greaterthan' for UDT BWA
-- 
-- ---------------------------------------------------------------

-- start transaction
begin work;


select	a.id, a.value, 
	b.id, b.value,
	a.value > b.value	greaterthan
  from	tst_BWA a, tst_BWA b
     ;
  

-- end transaction
commit work;

-- ---------------------------------------------------------------
-- EOF                                                            
-- ---------------------------------------------------------------
