-- ---------------------------------------------------------------
-- 
-- Module          : Functional Test for UDT BWA
-- Filename        : setup.sql
-- Author          : generated by DBDK
-- PURPOSE
--    Creates test table for UDT BWA and populates it 
--    with test data.
-- 
-- ---------------------------------------------------------------

-- begin transaction
begin work;


-- create test table
create table tst_BWA
(
	id	integer,
	input	lvarchar,
	output	lvarchar,
	error	lvarchar,
	value	BWA
);


--
-- insert valid test data
--

-- valid text input
insert into tst_BWA(id,input,output)
     values (0, 
	     "one.two.three.four", 
	     "one.two.three.four")
          ;

-- valid text input
insert into tst_BWA(id,input,output)
     values (1, 
	     "one..three.four", 
	     "one..three.four")
          ;

-- valid text input
insert into tst_BWA(id,input,output)
     values (2, 
	     "one...four", 
	     "one...four")
          ;

-- valid text input
insert into tst_BWA(id,input,output)
     values (3, 
	     "one...", 
	     "one...")
          ;

-- valid text input
insert into tst_BWA(id,input,output)
     values (4, 
	     "...", 
	     "...")
          ;

-- valid text input
insert into tst_BWA(id,input,output)
     values (5, 
	     "one..three.", 
	     "one..three.")
          ;

-- valid text input
insert into tst_BWA(id,input,output)
     values (6, 
	     ".two..four", 
	     ".two..four")
          ;


--
-- insert invalid test data
--

-- invalid text input
insert into tst_BWA(id,input,output,error)
     values (7, 
	     "only.three.parts", 
	     NULL, 
	     "UBWA1")
          ;

-- invalid text input
insert into tst_BWA(id,input,output,error)
     values (8, 
	     "five.parts.one.too.many", 
	     NULL, 
	     "UBWA1")
          ;

-- invalid text input
insert into tst_BWA(id,input,output,error)
     values (9, 
	     "part1_has_thirty_three_characters...", 
	     NULL, 
	     "UBWA0")
          ;

-- invalid text input
insert into tst_BWA(id,input,output,error)
     values (10, 
	     ".part2_has_thirty_three_characters..", 
	     NULL, 
	     "UBWA0")
          ;

-- invalid text input
insert into tst_BWA(id,input,output,error)
     values (11, 
	     "..part3_has_thirty_three_characters.", 
	     NULL, 
	     "UBWA0")
          ;

-- invalid text input
insert into tst_BWA(id,input,output,error)
     values (12, 
	     "...part4_has_thirty_three_characters", 
	     NULL, 
	     "UBWA0")
          ;



-- end transaction
commit work;


-- ---------------------------------------------------------------
-- EOF                                                            
-- ---------------------------------------------------------------
