-- Generated by BladeSmith 3.70.TC1  DO NOT MODIFY. --

execute procedure ifx_allow_newline('t');

insert into sysblddescription
	(bld_id, blocale_id, bdesc_format, bvendor_id, bdesc_desc, bdesc_copyright)
values
(
	"%SYSBLDNAME%",
	"en_us.1252",
	0,
	"",
	"",
	""
);

delete from sysbldvendors
	where bvendor_id = "" and
	bvendor_format = 0 and
	blocale_id = "en_us.1252";

insert into sysbldvendors
	(bvendor_id, bvendor_name, blocale_id, bvendor_format, bvendor_desc)
values
(
	"",
	"Informix Software, Inc.",
	"en_us.1252",
	0,
	""
);

