/*
** Title:          BinaryType.c
** SCCSid:         %W% %E% %U%
** CCid:           %W% %E% %U%
** Author:         Informix
** Created:        08/23/1999 10:26
** Description:    This is a generated source file for the BinaryData DataBlade module.
** Comments:       Generated for project BinaryData.1.1
*/

/*
**  The following is placed here to insure
**  that name "mangling" does not occur.
*/
#ifdef __cplusplus

extern "C"
{

#endif

/* Standard library includes. */
#include <ctype.h>
#include <stdio.h>
#include <string.h>
#include <stddef.h>

/* Used by Informix GLS routines. */
#include <ifxgls.h>

/* Include when accessing the Informix API. */
#include <mi.h>

/* This is the project include file. */
#include "BinaryData.h"


/* {{FUNCTION(40a768a1-50d7-11d3-b680-00a024e37610) (MergeSection) */

/*******************************************************************************
**
** Function name:
**
**	BinaryTypeSend
**
** Description:
**
**	The binary send function is used to convert an instance of a
**	data type between its internal representation on the server and
**	on the client.
**
** Special Comments:
**
**	Support routine for opaque type BinaryType returns mi_sendrecv.
**
** Parameters:
**
**	mi_bitvarying *    Gen_param1;    Pointer to the input text.
**	MI_FPARAM *        Gen_fparam;    Standard info - see DBDK docs.
**
** Return value:
**
**	mi_sendrecv *                     The constructed UDT value.
**
** History:
**
**	08/23/1999 - Generated by BladeSmith Version 4.00.TC1B.
**
** Identification:
**
**	Warning: Do not remove or modify this comment:
**	    BinaryTypeSend FunctionId: 40a768a1-50d7-11d3-b680-00a024e37610
**
********************************************************************************
*/

UDREXPORT
mi_sendrecv *
BinaryTypeSend
(
mi_bitvarying *              Gen_param1,      /* The UDT value                           */
MI_FPARAM *                  Gen_fparam       /* Standard info - see DBDK docs.          */
)
{
	MI_CONNECTION *      Gen_Con;         /* The current connection.                 */
	BinaryType *         Gen_InData;      /* Pointer to the UDT value.               */
	BinaryType *         Gen_OutData;     /* Pointer to the packet data.             */
	mi_sendrecv *        Gen_RetVal;      /* The return value.                       */
	mi_integer           Gen_vl_nitems;   /* Number of items.                        */

	mi_integer           Gen_vl_itemno;   /* Dummy index.                            */
	mi_integer           Gen_vl_len;      /* The length.                             */

	/* Get the current connection handle. */
	Gen_Con = mi_open( NULL, NULL, NULL );

	/* Verify that the connection has been established. */
	if( Gen_Con == 0 )
	{
		/*
		** Opening the current connection has failed
		** so issue the following message and quit.
		**
		** 	"Connection has failed in BinaryTypeSend."
		*/
		DBDK_TRACE_ERROR( "BinaryTypeSend", ERRORMESG1, 10 );

		/* not reached */
	}

	/* Point to the input data. */
	Gen_InData = (BinaryType *)mi_get_vardata( (mi_lvarchar *)Gen_param1 );

	/* Get the length of the data to follow. */
	Gen_vl_len = mi_get_varlen( (mi_lvarchar *)Gen_param1 );

	/* Compute the number of variable length items. */
	Gen_vl_nitems = (Gen_vl_len - offsetof( BinaryType, data ))
			 / sizeof( Gen_InData->data );

	/* Allocate a new return value. */
	Gen_RetVal = (mi_sendrecv *)mi_new_var(
			sizeof( BinaryType )
		        + (Gen_vl_nitems - 1)
			  * sizeof( Gen_InData->data ));
	if( Gen_RetVal == 0 )
	{
		/*
		** Memory allocation has failed so issue
		** the following message and quit.
		**
		** 	"Memory allocation has failed in BinaryTypeSend."
		*/
		DBDK_TRACE_ERROR( "BinaryTypeSend", ERRORMESG2, 10 );

		/* not reached */
	}

	/* Point to the output data. */
	Gen_OutData = (BinaryType *)mi_get_vardata( (mi_lvarchar *)Gen_RetVal );

	
	/*
	** Handle the variable elements of the UDT.
	*/
	for( Gen_vl_itemno = 0; Gen_vl_itemno < Gen_vl_nitems; Gen_vl_itemno++ )
	{
		/* Prepare the value for Gen_OutData->data. */
		mi_put_bytes( (mi_unsigned_char1 *)&Gen_OutData->data[Gen_vl_itemno], (char *)&Gen_InData->data[Gen_vl_itemno], 1 );
	}

	/* Close the connection. */
	mi_close( Gen_Con );

	/* Return the UDT for transmission. */
	return Gen_RetVal;
}
/* }}FUNCTION (#56V9) */




/* {{FUNCTION(40a768a2-50d7-11d3-b680-00a024e37610) (MergeSection) */

/*******************************************************************************
**
** Function name:
**
**	BinaryTypeReceive
**
** Description:
**
**	The binary receive function is used to convert an instance of a
**	data type between its internal representation on the server and
**	on the client.
**
** Special Comments:
**
**	Support routine for opaque type BinaryType returns mi_bitvarying.
**
** Parameters:
**
**	mi_lvarchar *      Gen_param1;    Pointer to the input text.
**	MI_FPARAM *        Gen_fparam;    Standard info - see DBDK docs.
**
** Return value:
**
**	mi_bitvarying *                   The constructed UDT value.
**
** History:
**
**	08/23/1999 - Generated by BladeSmith Version 4.00.TC1B.
**
** Identification:
**
**	Warning: Do not remove or modify this comment:
**	    BinaryTypeReceive FunctionId: 40a768a2-50d7-11d3-b680-00a024e37610
**
********************************************************************************
*/

UDREXPORT
mi_bitvarying *
BinaryTypeReceive
(
mi_sendrecv *                Gen_param1,      /* The UDT value.                          */
MI_FPARAM *                  Gen_fparam       /* Standard info - see DBDK docs.          */
)
{
	MI_CONNECTION *      Gen_Con;         /* The current connection.                 */
	mi_bitvarying *      Gen_RetVal;      /* The return value.                       */
	BinaryType *         Gen_InData;      /* Packet data.                            */
	BinaryType *         Gen_OutData;     /* Output UDT value.                       */
	mi_integer           Gen_vl_nitems;   /* Number of data items.                   */

	mi_integer           Gen_vl_itemno;   /* Index thru the items.                   */
	mi_integer           Gen_vl_len;      /* The length.                             */

	/* Get the current connection handle. */
	Gen_Con = mi_open( NULL, NULL, NULL );

	/* Verify that the connection has been established. */
	if( Gen_Con == 0 )
	{
		/*
		** Opening the current connection has failed
		** so issue the following message and quit.
		**
		** 	"Connection has failed in BinaryTypeReceive."
		*/
		DBDK_TRACE_ERROR( "BinaryTypeReceive", ERRORMESG1, 10 );

		/* not reached */
	}

	/* Point to the input data. */
	Gen_InData = (BinaryType *)mi_get_vardata( (mi_lvarchar *)Gen_param1 );

	/* Get the length of the data to follow. */
	Gen_vl_len = mi_get_varlen( (mi_lvarchar *)Gen_param1 );

	/* Compute the number of items in the variable length list. */
	Gen_vl_nitems = (Gen_vl_len
			  - offsetof( BinaryType, data ))
			 / sizeof( Gen_OutData->data );

	/* Allocate room for the UDT. */
	Gen_RetVal = (mi_bitvarying *)mi_new_var( sizeof( BinaryType )
		      +	(Gen_vl_nitems - 1)
			* sizeof( Gen_OutData->data ));
	if( Gen_RetVal == 0 )
	{
		/*
		** Memory allocation has failed so issue
		** the following message and quit.
		**
		** 	"Memory allocation has failed in BinaryTypeReceive."
		*/
		DBDK_TRACE_ERROR( "BinaryTypeReceive", ERRORMESG2, 10 );

		/* not reached */
	}

	/* Point to the output data. */
	Gen_OutData = (BinaryType *)mi_get_vardata( (mi_lvarchar *)Gen_RetVal );

	/* Copy the attribute value(s) from the transmission parcel. */

	
	/*
	** Handle the variable elements of the UDT.
	*/
	for( Gen_vl_itemno = 0; Gen_vl_itemno < Gen_vl_nitems; Gen_vl_itemno++ )
	{
		/* Prepare the value for Gen_OutData->data. */
		mi_get_bytes( (mi_unsigned_char1 *)&Gen_InData->data[Gen_vl_itemno], (char *)&Gen_OutData->data[Gen_vl_itemno], 1 );
	}

	/* Close the connection. */
	mi_close( Gen_Con );

	/* Return the transmitted UDT value. */
	return Gen_RetVal;
}
/* }}FUNCTION (#KJQV) */




/* {{FUNCTION(40a768a7-50d7-11d3-b680-00a024e37610) (MergeSection) */

/*******************************************************************************
**
** Function name:
**
**	BinaryTypeImportBinary
**
** Description:
**
**	The  importbinary  function is  used to  support  bulk copy of
**	binary data. This function is the same as the import function,
**	except that it  operates  on internal  representations of  the
**	data type.  This function is  usually only  provided for large
**	object  data types and is called by the LOAD BINARY command of
**	dbaccess.
**
** Special Comments:
**
**	Support routine for opaque type BinaryType returns mi_bitvarying.
**
** Parameters:
**
**	mi_bitvarying *    Gen_param1;    Pointer to the input text.
**	MI_FPARAM *        Gen_fparam;    Standard info - see DBDK docs.
**
** Return value:
**
**	mi_bitvarying *                   The constructed UDT value.
**
** History:
**
**	08/23/1999 - Generated by BladeSmith Version 4.00.TC1B.
**
** Identification:
**
**	Warning: Do not remove or modify this comment:
**	    BinaryTypeImportBinary FunctionId: 40a768a7-50d7-11d3-b680-00a024e37610
**
********************************************************************************
*/

UDREXPORT
mi_bitvarying *
BinaryTypeImportBinary
(
mi_bitvarying *              Gen_param1,      /* The input value.                        */
MI_FPARAM *                  Gen_fparam       /* Standard info - see DBDK docs.          */
)
{
	MI_CONNECTION *      Gen_Con;         /* The current connection.                 */
	mi_bitvarying *      Gen_RetVal;      /* The return result.                      */
	BinaryType *         Gen_InData;      /* The UDT input value.                    */
	BinaryType *         Gen_OutData;     /* The transfer data.                      */
	mi_integer           Gen_vl_nitems;   /* The number of items.                    */

	mi_integer           Gen_vl_itemno;   /* Index thru the items.                   */
	mi_integer           Gen_vl_len;      /* The length.                             */

	/* Get the current connection handle. */
	Gen_Con = mi_open( NULL, NULL, NULL );

	/* Verify that the connection has been established. */
	if( Gen_Con == 0 )
	{
		/*
		** Opening the current connection has failed
		** so issue the following message and quit.
		**
		** 	"Connection has failed in BinaryTypeImportBinary."
		*/
		DBDK_TRACE_ERROR( "BinaryTypeImportBinary", ERRORMESG1, 10 );

		/* not reached */
	}

	/* Point to the input data. */
	Gen_InData = (BinaryType *)mi_get_vardata( (mi_lvarchar *)Gen_param1 );

	/* Get the length of the data to follow. */
	Gen_vl_len = mi_get_varlen( (mi_lvarchar *)Gen_param1 );

	/* Compute the number of items in the variable length list. */
	Gen_vl_nitems = (Gen_vl_len
			  - offsetof( BinaryType, data ))
			 / sizeof( Gen_OutData->data );

	/* Allocate a new UDT for the return result. */
	Gen_RetVal = (mi_bitvarying *)mi_new_var(
			sizeof( BinaryType )
		        + (Gen_vl_nitems - 1)
			  * sizeof( Gen_OutData->data ));
	if( Gen_RetVal == 0 )
	{
		/*
		** Memory allocation has failed so issue
		** the following message and quit.
		**
		** 	"Memory allocation has failed in BinaryTypeImportBinary."
		*/
		DBDK_TRACE_ERROR( "BinaryTypeImportBinary", ERRORMESG2, 10 );

		/* not reached */
	}

	/* Point to the output data. */
	Gen_OutData = (BinaryType *)mi_get_vardata( (mi_lvarchar *)Gen_RetVal );

	
	/*
	** Handle the variable elements of the UDT.
	*/
	for( Gen_vl_itemno = 0; Gen_vl_itemno < Gen_vl_nitems; Gen_vl_itemno++ )
	{
		/* Prepare the value for Gen_OutData->data. */
		mi_get_bytes( (mi_unsigned_char1 *)&Gen_InData->data[Gen_vl_itemno], (char *)&Gen_OutData->data[Gen_vl_itemno], 1 );
	}

	/* Close the connection. */
	mi_close( Gen_Con );

	return Gen_RetVal;
}
/* }}FUNCTION (#D20G) */




/* {{FUNCTION(40a768a8-50d7-11d3-b680-00a024e37610) (MergeSection) */

/*******************************************************************************
**
** Function name:
**
**	BinaryTypeExportBinary
**
** Description:
**
**	The  exportbinary  function  is  used  to  support  bulk  copy  of
**	binary  data.  This function is the same as  the export  function,
**	except that it  operates on  internal  representations of the data
**	type.  This  function is usually only  provided  for large  object
**	data types and is called by the UNLOAD BINARY command of dbaccess.
**
** Special Comments:
**
**	Support routine for opaque type BinaryType returns mi_bitvarying.
**
** Parameters:
**
**	mi_bitvarying *    Gen_param1;    Pointer to the input text.
**	MI_FPARAM *        Gen_fparam;    Standard info - see DBDK docs.
**
** Return value:
**
**	mi_bitvarying *                   The exported UDT value.
**
** History:
**
**	08/23/1999 - Generated by BladeSmith Version 4.00.TC1B.
**
** Identification:
**
**	Warning: Do not remove or modify this comment:
**	    BinaryTypeExportBinary FunctionId: 40a768a8-50d7-11d3-b680-00a024e37610
**
********************************************************************************
*/

UDREXPORT
mi_bitvarying *
BinaryTypeExportBinary
(
mi_bitvarying *              Gen_param1,      /* The UDT value.                          */
MI_FPARAM *                  Gen_fparam       /* Standard info - see DBDK docs.          */
)
{
	MI_CONNECTION *      Gen_Con;         /* The current connection.                 */
	mi_bitvarying *      Gen_RetVal;      /* The return value.                       */
	BinaryType *         Gen_InData;      /* The transfer data.                      */
	BinaryType *         Gen_OutData;     /* The output data.                        */
	mi_integer           Gen_vl_nitems;   /* The number of items.                    */

	mi_integer           Gen_vl_itemno;   /* Index thru the items.                   */
	mi_integer           Gen_vl_len;      /* The length.                             */

	/* Get the current connection handle. */
	Gen_Con = mi_open( NULL, NULL, NULL );

	/* Verify that the connection has been established. */
	if( Gen_Con == 0 )
	{
		/*
		** Opening the current connection has failed
		** so issue the following message and quit.
		**
		** 	"Connection has failed in BinaryTypeExportBinary."
		*/
		DBDK_TRACE_ERROR( "BinaryTypeExportBinary", ERRORMESG1, 10 );

		/* not reached */
	}

	/* Point to the input data. */
	Gen_InData = (BinaryType *)mi_get_vardata( (mi_lvarchar *)Gen_param1 );

	/* Get the length of the data to follow. */
	Gen_vl_len = mi_get_varlen( (mi_lvarchar *)Gen_param1 );

	/* Compute the number of variable length items. */
	Gen_vl_nitems = (Gen_vl_len
			  - offsetof( BinaryType, data ))
			 / sizeof( Gen_InData->data );

	/* Allocate the output parcel. */
	Gen_RetVal = (mi_bitvarying *)mi_new_var(
			sizeof( BinaryType )
		        + (Gen_vl_nitems - 1)
			  * sizeof( Gen_InData->data ));
	if( Gen_RetVal == 0 )
	{
		/*
		** Memory allocation has failed so issue
		** the following message and quit.
		**
		** 	"Memory allocation has failed in BinaryTypeExportBinary."
		*/
		DBDK_TRACE_ERROR( "BinaryTypeExportBinary", ERRORMESG2, 10 );

		/* not reached */
	}

	/* Point to the output data. */
	Gen_OutData = (BinaryType *)mi_get_vardata( (mi_lvarchar *)Gen_RetVal );

	
	/*
	** Handle the variable elements of the UDT.
	*/
	for( Gen_vl_itemno = 0; Gen_vl_itemno < Gen_vl_nitems; Gen_vl_itemno++ )
	{
		/* Prepare the value for Gen_OutData->data. */
		mi_put_bytes( (mi_unsigned_char1 *)&Gen_OutData->data[Gen_vl_itemno], (char *)&Gen_InData->data[Gen_vl_itemno], 1 );
	}

	/* Close the connection. */
	mi_close( Gen_Con );

	/* Return the UDT value. */
	return Gen_RetVal;
}
/* }}FUNCTION (#4CQJ) */




/* {{FUNCTION(40a768a9-50d7-11d3-b680-00a024e37610) (MergeSection) */

/*******************************************************************************
**
** Function name:
**
**	BinaryTypeCompare
**
** Description:
**
**	Perform the comparison operations required to compare two
**	UDT values.
**
**	This function returns zero if the two UDT values are equal and
**	a non-zero value otherwise.
**
** Special Comments:
**
**	Compares two variable-length opaque types
**
** Parameters:
**
**	mi_bitvarying *    Gen_param1;    The first UDT value to compare.
**	mi_bitvarying *    Gen_param2;    The second UDT value to compare.
**	MI_FPARAM *        Gen_fparam;    Standard info - see DBDK docs.
**
** Return value:
**
**	mi_integer                        The comparison result.
**
** History:
**
**	08/23/1999 - Generated by BladeSmith Version 4.00.TC1B.
**
** Identification:
**
**	Warning: Do not remove or modify this comment:
**	    BinaryTypeCompare FunctionId: 40a768a9-50d7-11d3-b680-00a024e37610
**
********************************************************************************
*/

UDREXPORT
mi_integer
BinaryTypeCompare
(
mi_bitvarying *              Gen_param1,      /* The first UDT value to compare.         */
mi_bitvarying *              Gen_param2,      /* The second UDT value to compare.        */
MI_FPARAM *                  Gen_fparam       /* Standard info - see DBDK docs.          */
)
{
	MI_CONNECTION *      Gen_Con;         /* The current connection.                 */
	mi_integer           Gen_cc;          /* Numeric attribute difference.           */
	BinaryType *         Gen_Value1;      /* Pointer to the first value.             */
	BinaryType *         Gen_Value2;      /* Pointer to the second value.            */
	mi_integer           Gen_vl_nitems;   /* The number of items.                    */

	mi_integer           Gen_vl_itemno;   /* Index thru the items.                   */
	mi_integer           Gen_vl_len_diff;                                            /* Data length difference.        */

	/* Get the current connection handle. */
	Gen_Con = mi_open( NULL, NULL, NULL );

	/* Verify that the connection has been established. */
	if( Gen_Con == 0 )
	{
		/*
		** Opening the current connection has failed
		** so issue the following message and quit.
		**
		** 	"Connection has failed in BinaryTypeCompare."
		*/
		DBDK_TRACE_ERROR( "BinaryTypeCompare", ERRORMESG1, 10 );

		/* not reached */
	}

	/* Point to the data values that are to be compared. */
	Gen_Value1 = (BinaryType *)mi_get_vardata( (mi_lvarchar *)Gen_param1 );
	Gen_Value2 = (BinaryType *)mi_get_vardata( (mi_lvarchar *)Gen_param2 );

	/* Compute the difference of the lengths of the two UDTs. */
	Gen_vl_len_diff = mi_get_varlen( (mi_lvarchar *)Gen_param1 )
		         - mi_get_varlen( (mi_lvarchar *)Gen_param1 );

	/* Compute the number of variable length items. */
	Gen_vl_nitems =
		(Gen_vl_len_diff <= 0
		? ( mi_get_varlen( (mi_lvarchar *)Gen_param1)
		    - offsetof( BinaryType, data ))
		  / sizeof( Gen_Value1->data )
		: ( mi_get_varlen( (mi_lvarchar *)Gen_param2 )
		    - offsetof( BinaryType, data ))
		  / sizeof( Gen_Value1->data )
		);

	
	/*
	** Handle the variable elements of the UDT.
	*/
	for( Gen_vl_itemno = 0; Gen_vl_itemno < Gen_vl_nitems; Gen_vl_itemno++ )
	{
		/* Compare the two values. */
		Gen_cc = Gen_Value1->data[Gen_vl_itemno] - Gen_Value2->data[Gen_vl_itemno];
		if( Gen_cc )
		{
			return Gen_cc < 0 ? -1 : 1;
		}
	}

	/* Close the connection. */
	mi_close( Gen_Con );

	return Gen_vl_len_diff < 0 ? -1 : !Gen_vl_len_diff ? 0 : 1;
}
/* }}FUNCTION (#TGC8) */




/* {{FUNCTION(40a768aa-50d7-11d3-b680-00a024e37610) (MergeSection) */

/*******************************************************************************
**
** Function name:
**
**	BinaryTypeEqual
**
** Description:
**
**	Determine if one UDT value is equal to another.
**
** Special Comments:
**
**	Compares two variable-length opaque types for equality
**
** Parameters:
**
**	mi_bitvarying *    Gen_param1;    The first UDT value to compare.
**	mi_bitvarying *    Gen_param2;    The second UDT value to compare.
**	MI_FPARAM *        Gen_fparam;    Standard info - see DBDK docs.
**
** Return value:
**
**	mi_boolean                        The comparison result.
**
** History:
**
**	08/23/1999 - Generated by BladeSmith Version 4.00.TC1B.
**
** Identification:
**
**	Warning: Do not remove or modify this comment:
**	    BinaryTypeEqual FunctionId: 40a768aa-50d7-11d3-b680-00a024e37610
**
********************************************************************************
*/

UDREXPORT
mi_boolean
BinaryTypeEqual
(
mi_bitvarying *              Gen_param1,      /* The first UDT value to compare.         */
mi_bitvarying *              Gen_param2,      /* The second UDT value to compare.        */
MI_FPARAM *                  Gen_fparam       /* Standard info - see DBDK docs.          */
)
{
	/* Call Compare to perform the comparison. */
	return (mi_boolean)(0 == BinaryTypeCompare( Gen_param1,
			Gen_param2, Gen_fparam ));
}
/* }}FUNCTION (#F5KF) */




/* {{FUNCTION(40a768ab-50d7-11d3-b680-00a024e37610) (MergeSection) */

/*******************************************************************************
**
** Function name:
**
**	BinaryTypeNotEqual
**
** Description:
**
**	Determine if one UDT value is not equal to another.
**
** Special Comments:
**
**	Compares two variable-length opaque types for non-equality
**
** Parameters:
**
**	mi_bitvarying *    Gen_param1;    The first UDT value to compare.
**	mi_bitvarying *    Gen_param2;    The second UDT value to compare.
**	MI_FPARAM *        Gen_fparam;    Standard info - see DBDK docs.
**
** Return value:
**
**	mi_boolean                        The comparison result.
**
** History:
**
**	08/23/1999 - Generated by BladeSmith Version 4.00.TC1B.
**
** Identification:
**
**	Warning: Do not remove or modify this comment:
**	    BinaryTypeNotEqual FunctionId: 40a768ab-50d7-11d3-b680-00a024e37610
**
********************************************************************************
*/

UDREXPORT
mi_boolean
BinaryTypeNotEqual
(
mi_bitvarying *              Gen_param1,      /* The first UDT value to compare.         */
mi_bitvarying *              Gen_param2,      /* The second UDT value to compare.        */
MI_FPARAM *                  Gen_fparam       /* Standard info - see DBDK docs.          */
)
{
	/* Call Compare to perform the comparison. */
	return (mi_boolean)(0 != BinaryTypeCompare( Gen_param1,
			Gen_param2, Gen_fparam ));
}
/* }}FUNCTION (#5NTT) */




/* {{FUNCTION(40a768a5-50d7-11d3-b680-00a024e37610) (MergeSection) */

/*******************************************************************************
**
** Function name:
**
**	BinaryTypeImportText
**
** Description:
**
**	The import function enables bulk copy for user-defined types.
**	When the  LOAD statement is  used from  dbaccess to copy data
**	from a file  into the database, the  server calls the  import
**	function to convert the  incoming  value  to the data  type's
**	internal format.
**
** Special Comments:
**
**	Support routine for opaque type BinaryType returns mi_bitvarying.
**
** Parameters:
**
**	mi_impexp *        Gen_param1;    Pointer to the input text.
**	MI_FPARAM *        Gen_fparam;    Standard info - see DBDK docs.
**
** Return value:
**
**	mi_bitvarying *                   The constructed UDT value.
**
** History:
**
**	08/23/1999 - Generated by BladeSmith Version 4.00.TC1B.
**
** Identification:
**
**	Warning: Do not remove or modify this comment:
**	    BinaryTypeImportText FunctionId: 40a768a5-50d7-11d3-b680-00a024e37610
**
********************************************************************************
*/

UDREXPORT
mi_bitvarying *
BinaryTypeImportText
(
mi_impexp *                  Gen_param1,                                                 /* The import text.                  */
MI_FPARAM *                  Gen_fparam                                                  /* Standard info - see DBDK docs.    */
)
{
	MI_CONNECTION *      Gen_Con;         /* The current connection.                 */
	gl_mchar_t *         Gen_InData;                                                 /* Pointer to the input data.        */
	gl_mchar_t *         Gen_StartInData;                                            /* First value of Gen_InData.       */
	BinaryType *         Gen_OutData;                                                /* Pointer to the output data.       */
	mi_integer           Gen_DataLen;                                                /* Length of the data in bytes.      */
	mi_integer           Gen_UDTSize;                                                /* Size of the UDT in bytes.         */
	mi_integer           Gen_vl_nitems;                                              /* Number of variable length items.  */

	mi_integer           Gen_vl_itemno;                                              /* Index through the items.          */
	mi_bitvarying *      Gen_RetVal;                                                 /* The return value.                 */
	mi_int1              Gen_temp_int1;                                              /* Store byte value here temporarily.*/

	/* Get the current connection handle. */
	Gen_Con = mi_open( NULL, NULL, NULL );

	/* Verify that the connection has been established. */
	if( Gen_Con == 0 )
	{
		/*
		** Opening the current connection has failed
		** so issue the following message and quit.
		**
		** 	"Connection has failed in BinaryTypeImportText."
		*/
		DBDK_TRACE_ERROR( "BinaryTypeImportText", ERRORMESG1, 10 );

		/* not reached */
	}

	/* Point to the input data. */
	Gen_InData = (gl_mchar_t *)mi_get_vardata( (mi_lvarchar *) Gen_param1 );
	Gen_StartInData = Gen_InData;

	/* Get the length of the input string. */
	Gen_DataLen = mi_get_varlen( (mi_lvarchar *)Gen_param1 );

	/* Compute the number of items in the variable length list. */
	Gen_vl_nitems = (Gen_nstrwords( Gen_InData,
				          mi_get_varlen( (mi_lvarchar *)Gen_param1 ) )
			  - 0 )
			 / 1;

	/* Compute the amount of memory required for the data. */
	Gen_UDTSize = sizeof( BinaryType )
		       + (Gen_vl_nitems - 1) * sizeof( Gen_OutData->data );

	/* Allocate a new UDT for the return result. */
	Gen_RetVal = (mi_bitvarying *)mi_new_var( Gen_UDTSize );
	if( Gen_RetVal == 0 )
	{
		/*
		** Memory allocation has failed so issue
		** the following message and quit.
		**
		** 	"Memory allocation has failed in BinaryTypeImportText."
		*/
		DBDK_TRACE_ERROR( "BinaryTypeImportText", ERRORMESG2, 10 );

		/* not reached */
	}

	/* Point to the output data. */
	Gen_OutData = (BinaryType *)mi_get_vardata( (mi_lvarchar *)Gen_RetVal );

	
	/*
	** Handle the variable elements of the UDT.
	*/
	for( Gen_vl_itemno = 0; Gen_vl_itemno < Gen_vl_nitems; Gen_vl_itemno++ )
	{
		/* Get the mi_int1 value for data[Gen_vl_itemno]. */
		Gen_InData = Gen_sscanf( Gen_Con, "BinaryTypeImportText", Gen_InData,
		                         Gen_DataLen - (Gen_InData - Gen_StartInData),
		                         0, "%u1 %n", (char *)&Gen_temp_int1 );
		Gen_OutData->data[Gen_vl_itemno] = Gen_temp_int1;
	}

	/* Close the connection. */
	mi_close( Gen_Con );

	/* Return the UDT value. */
	return Gen_RetVal;
}
/* }}FUNCTION (#9KCL) */




/* {{FUNCTION(40a768a6-50d7-11d3-b680-00a024e37610) (MergeSection) */

/*******************************************************************************
**
** Function name:
**
**	BinaryTypeExportText
**
** Description:
**
**	The export function enables bulk copy for user-defined types.
**	When the UNLOAD statement is used from  dbaccess to copy data
**	from  the  database to a  file, the  server calls the  export
**	function  to convert the outcoming  value to the data  type's
**	external format.
**
** Special Comments:
**
**	Support routine for opaque type BinaryType returns mi_impexp.
**
** Parameters:
**
**	mi_bitvarying *    Gen_param1;    Pointer to the input text.
**	MI_FPARAM *        Gen_fparam;    Standard info - see DBDK docs.
**
** Return value:
**
**	mi_impexp *                       The exported UDT value.
**
** History:
**
**	08/23/1999 - Generated by BladeSmith Version 4.00.TC1B.
**
** Identification:
**
**	Warning: Do not remove or modify this comment:
**	    BinaryTypeExportText FunctionId: 40a768a6-50d7-11d3-b680-00a024e37610
**
********************************************************************************
*/

UDREXPORT
mi_impexp *
BinaryTypeExportText
(
mi_bitvarying *              Gen_param1,      /* The UDT value.                          */
MI_FPARAM *                  Gen_fparam       /* Standard info - see DBDK docs.          */
)
{
	MI_CONNECTION *      Gen_Con;         /* The current connection.                 */
	mi_integer           Gen_CharLen;     /* Estimate maximum length.                */
	BinaryType *         Gen_InData;      /* Pointer to the input data.              */
	char *               Gen_OutData;     /* Pointer to the output data.             */
	mi_impexp *          Gen_RetVal;      /* The return result.                      */
	mi_integer           Gen_DataLen;     /* The data length.                        */
	mi_integer           Gen_vl_nitems;   /* The number of items.                    */

	mi_integer           Gen_vl_itemno;   /* Index thru the items.                   */
	mi_integer           Gen_vl_len;      /* The length.                             */
	/* Get the current connection handle. */
	Gen_Con = mi_open( NULL, NULL, NULL );

	/* Verify that the connection has been established. */
	if( Gen_Con == 0 )
	{
		/*
		** Opening the current connection has failed
		** so issue the following message and quit.
		**
		** 	"Connection has failed in BinaryTypeExportText."
		*/
		DBDK_TRACE_ERROR( "BinaryTypeExportText", ERRORMESG1, 10 );

		/* not reached */
	}

	/* Point to the input data. */
	Gen_InData = (BinaryType *)mi_get_vardata( (mi_lvarchar *)Gen_param1 );

	/* Get the length of the data to follow. */
	Gen_vl_len = mi_get_varlen( (mi_lvarchar *)Gen_param1 );

	/* Compute the number of variable length items. */
	Gen_vl_nitems = (Gen_vl_len - sizeof( BinaryType ) + sizeof( Gen_InData->data ))
			 / sizeof( mi_int1 );

	/* Compute the maximum length of the text representation. */
	Gen_CharLen         =   1              /* Leave room for the NULL terminator. */
	               +                  Gen_vl_nitems * 4                           /* Add the length for data. */
		            ;

	/* Allocate the output parcel. */
	Gen_RetVal = (mi_impexp *)mi_new_var( Gen_CharLen );
	if( Gen_RetVal == 0 )
	{
		/*
		** Memory allocation has failed so issue
		** the following message and quit.
		**
		** 	"Memory allocation has failed in BinaryTypeExportText."
		*/
		DBDK_TRACE_ERROR( "BinaryTypeExportText", ERRORMESG2, 10 );

		/* not reached */
	}

	/* Point to the output data. */
	Gen_OutData = mi_get_vardata( (mi_lvarchar *)Gen_RetVal );

	/* Format the attribute value into the output string. */

	
	/*
	** Handle the variable elements of the UDT.
	*/
	for( Gen_vl_itemno = 0; Gen_vl_itemno < Gen_vl_nitems; Gen_vl_itemno++ )
	{
		/* Format the mi_int1 value for data. */
		sprintf( Gen_OutData, "%d ", Gen_InData->data[Gen_vl_itemno] );
		Gen_OutData += strlen( Gen_OutData );
	}

	/*
	** Compute the length of the data and
	** place it in the return structure.
	*/
	Gen_DataLen = (mi_integer)(Gen_OutData - mi_get_vardata( (mi_lvarchar *) Gen_RetVal ));
	mi_set_varlen ( (mi_lvarchar *) Gen_RetVal, Gen_DataLen );

	/* Close the connection. */
	mi_close( Gen_Con );

	/* Return the UDT value. */
	return Gen_RetVal;
}
/* }}FUNCTION (#74JB) */




/* {{FUNCTION(40a768a3-50d7-11d3-b680-00a024e37610) (MergeSection) */

/*******************************************************************************
**
** Function name:
**
**	BinaryTypeInput
**
** Description:
**
**	This function converts from the external representation of the
**	UDT type BinaryType to its internal representation.   The external
**	representation is a blank-separated list of values and the
**	internal representation is a 'C' structure of type BinaryType as
**	defined in the header file.
**
**
**	Data can be inserted into a table using an SQL insert statement:
**
**		insert into tablename values ( 'value-list' );
**
**	value-list is a space-delimited list of values.
**
**	Data for the mi_int1 data type is in the range [0, 255].
**
** Special Comments:
**
**	Support routine for opaque type BinaryType returns mi_lvarchar.
**
** Parameters:
**
**	mi_lvarchar *      Gen_param1;    Pointer to the input text.
**	MI_FPARAM *        Gen_fparam;    Standard info - see DBDK docs.
**
** Return value:
**
**	mi_lvarchar *                     The constructed UDT value.
**
** History:
**
**	08/23/1999 - Generated by BladeSmith Version 4.00.TC1B.
**
** Identification:
**
**	Warning: Do not remove or modify this comment:
**	    BinaryTypeInput FunctionId: 40a768a3-50d7-11d3-b680-00a024e37610
**
********************************************************************************
*/

UDREXPORT
mi_lvarchar *
BinaryTypeInput
(
mi_lvarchar *                Gen_param1,                                                 /* Pointer to the input text.        */
MI_FPARAM *                  Gen_fparam                                                  /* Standard info - see DBDK docs.    */
)
{
	MI_CONNECTION *      Gen_Con;         /* The current connection.                 */
	gl_mchar_t *         Gen_InData;                                                 /* Pointer to the input data.        */
	gl_mchar_t *         Gen_StartInData;                                            /* First value of Gen_InData.       */
	BinaryType *         Gen_OutData;                                                /* Pointer to the output data.       */
	mi_integer           Gen_DataLen;                                                /* Length of the data in bytes.      */
	mi_integer           Gen_UDTSize;                                                /* Size of the UDT in bytes.         */
	mi_integer           Gen_vl_nitems;                                              /* Number of variable length items.  */

	mi_integer           Gen_vl_itemno;                                              /* Index through the items.          */
	mi_lvarchar *        Gen_RetVal;                                                 /* The return value.                 */
	mi_int1              Gen_temp_int1;                                              /* Store byte value here temporarily.*/

	/* Get the current connection handle. */
	Gen_Con = mi_open( NULL, NULL, NULL );

	/* Verify that the connection has been established. */
	if( Gen_Con == 0 )
	{
		/*
		** Opening the current connection has failed
		** so issue the following message and quit.
		**
		** 	"Connection has failed in BinaryTypeInput."
		*/
		DBDK_TRACE_ERROR( "BinaryTypeInput", ERRORMESG1, 10 );

		/* not reached */
	}

	/* Point to the input data. */
	Gen_InData = (gl_mchar_t *)mi_get_vardata( Gen_param1 );
	Gen_StartInData = Gen_InData;

	/* Get the length of the input string. */
	Gen_DataLen = mi_get_varlen( Gen_param1 );

	/* Compute the number of items in the variable length list. */
	Gen_vl_nitems = (Gen_nstrwords( Gen_InData,
				          mi_get_varlen( (mi_lvarchar *)Gen_param1 ) )
			  - 0 )
			 / 1;

	/* Compute the amount of memory required for the data. */
	Gen_UDTSize = sizeof( BinaryType )
		       + (Gen_vl_nitems - 1) * sizeof( Gen_OutData->data );

	/* Allocate a new UDT for the return result. */
	Gen_RetVal = mi_new_var( Gen_UDTSize );
	if( Gen_RetVal == 0 )
	{
		/*
		** Memory allocation has failed so issue
		** the following message and quit.
		**
		** 	"Memory allocation has failed in BinaryTypeInput."
		*/
		DBDK_TRACE_ERROR( "BinaryTypeInput", ERRORMESG2, 10 );

		/* not reached */
	}

	/* Point to the output data. */
	Gen_OutData = (BinaryType *)mi_get_vardata( Gen_RetVal );

	
	/*
	** Handle the variable elements of the UDT.
	*/
	for( Gen_vl_itemno = 0; Gen_vl_itemno < Gen_vl_nitems; Gen_vl_itemno++ )
	{
		/* Get the mi_int1 value for data[Gen_vl_itemno]. */
		Gen_InData = Gen_sscanf( Gen_Con, "BinaryTypeInput", Gen_InData,
		                         Gen_DataLen - (Gen_InData - Gen_StartInData),
		                         0, "%u1 %n", (char *)&Gen_temp_int1 );
		Gen_OutData->data[Gen_vl_itemno] = Gen_temp_int1;
	}

	/* Close the connection. */
	mi_close( Gen_Con );

	/* Return the UDT value. */
	return Gen_RetVal;
}
/* }}FUNCTION (#LCAU) */




/* {{FUNCTION(40a768a4-50d7-11d3-b680-00a024e37610) (MergeSection) */

/*******************************************************************************
**
** Function name:
**
**	BinaryTypeOutput
**
** Description:
**
**	This function converts from the internal representation of the
**	UDT type BinaryType to its external representation.   The external
**	representation is a blank-separated list of values and the
**	internal representation is a 'C' structure of type BinaryType as
**	defined in the header file.
**
**	Data can be retrieved from a table using an SQL select statement:
**
**		select * from tablename;
**
**	Data for the mi_int1 data type is in the range [0, 255].
**
** Special Comments:
**
**	Support routine for opaque type BinaryType returns mi_lvarchar.
**
** Parameters:
**
**	mi_lvarchar *      Gen_param1;    Pointer to the input text.
**	MI_FPARAM *        Gen_fparam;    Standard info - see DBDK docs.
**
** Return value:
**
**	mi_lvarchar *                     The constructed UDT value.
**
** History:
**
**	08/23/1999 - Generated by BladeSmith Version 4.00.TC1B.
**
** Identification:
**
**	Warning: Do not remove or modify this comment:
**	    BinaryTypeOutput FunctionId: 40a768a4-50d7-11d3-b680-00a024e37610
**
********************************************************************************
*/

UDREXPORT
mi_lvarchar *
BinaryTypeOutput
(
mi_lvarchar *                Gen_param1,                                                 /* The UDT value.                    */
MI_FPARAM *                  Gen_fparam                                                  /* Standard info - see DBDK docs.    */
)
{
	MI_CONNECTION *      Gen_Con;         /* The current connection.                 */
	mi_integer           Gen_CharLen;                                                /* Estimate maximum length.          */
	BinaryType *         Gen_InData;                                                 /* Pointer to the input data.        */
	char *               Gen_OutData;                                                /* Pointer to the output data.       */
	mi_lvarchar *        Gen_RetVal;                                                 /* The return result.                */
	mi_integer           Gen_DataLen;                                                /* The data length.                  */
	mi_integer           Gen_vl_nitems;                                              /* The number of items.              */

	mi_integer           Gen_vl_itemno;                                              /* Index thru the items.             */
	mi_integer           Gen_vl_len;                                                 /* The length.                       */

	/* Get the current connection handle. */
	Gen_Con = mi_open( NULL, NULL, NULL );

	/* Verify that the connection has been established. */
	if( Gen_Con == 0 )
	{
		/*
		** Opening the current connection has failed
		** so issue the following message and quit.
		**
		** 	"Connection has failed in BinaryTypeOutput."
		*/
		DBDK_TRACE_ERROR( "BinaryTypeOutput", ERRORMESG1, 10 );

		/* not reached */
	}

	/* Point to the input data. */
	Gen_InData = (BinaryType *)mi_get_vardata( Gen_param1 );

	/* Get the length of the data to follow. */
	Gen_vl_len = mi_get_varlen( (mi_lvarchar *)Gen_param1 );

	/* Compute the number of variable length items. */
	Gen_vl_nitems = (Gen_vl_len - sizeof( BinaryType ) + sizeof( Gen_InData->data ))
			 / sizeof( mi_int1 );

	/* Compute the maximum length of the text representation. */
	Gen_CharLen         =   1              /* Leave room for the NULL terminator. */
	               +                  Gen_vl_nitems * 4                           /* Add the length for data. */
		            ;

	/* Allocate room for the output string. */
	Gen_RetVal = mi_new_var( Gen_CharLen );
	if( Gen_RetVal == 0 )
	{
		/*
		** Memory allocation has failed so issue
		** the following message and quit.
		**
		** 	"Memory allocation has failed in BinaryTypeOutput."
		*/
		DBDK_TRACE_ERROR( "BinaryTypeOutput", ERRORMESG2, 10 );

		/* not reached */
	}

	/* Point to the output data. */
	Gen_OutData = mi_get_vardata( Gen_RetVal );

	/* Format the attribute value into the output string. */

	
	/*
	** Handle the variable elements of the UDT.
	*/
	for( Gen_vl_itemno = 0; Gen_vl_itemno < Gen_vl_nitems; Gen_vl_itemno++ )
	{
		/* Format the mi_int1 value for data. */
		sprintf( Gen_OutData, "%d ", Gen_InData->data[Gen_vl_itemno] );
		Gen_OutData += strlen( Gen_OutData );
	}

	/*
	** Compute the length of the data and
	** place it in the return structure.
	*/
	Gen_DataLen = (mi_integer)(Gen_OutData - mi_get_vardata( Gen_RetVal ));
	mi_set_varlen ( Gen_RetVal, Gen_DataLen );

	/* Close the connection. */
	mi_close( Gen_Con );

	/* Return the UDT value. */
	return Gen_RetVal;
}
/* }}FUNCTION (#UU8L) */



#ifdef __cplusplus

}

#endif
