--
--  File:  Random.sql
--
-- About:
--
--   This file defines the new functions that implement the
--  Random Number datablade.
--
-- DROP FUNCTION SeededRand( INTEGER );
--
CREATE FUNCTION SeededRand( INTEGER )
RETURNING REAL
EXTERNAL NAME "$INFORMIXDIR/extend/Rand/bin/Random.bld(RandomWithSeed)"
LANGUAGE C;
--
GRANT EXECUTE ON FUNCTION SeededRand ( INTEGER ) TO PUBLIC;
--
-- DROP FUNCTION SeededRand( INTEGER, INTEGER );
--
CREATE FUNCTION SeededRand( INTEGER , INTEGER )
RETURNING INTEGER
EXTERNAL NAME "$INFORMIXDIR/extend/Rand/bin/Random.bld(RandomWithSeedMax)"
LANGUAGE C;
--
GRANT EXECUTE ON FUNCTION SeededRand ( INTEGER, INTEGER ) TO PUBLIC;
--
-- DROP FUNCTION Rand();
--
CREATE FUNCTION Rand( )
RETURNING REAL
EXTERNAL NAME "$INFORMIXDIR/extend/Rand/bin/Random.bld(RandomNoSeed)"
LANGUAGE C;
--
GRANT EXECUTE ON FUNCTION Rand () TO PUBLIC;
--
-- DROP FUNCTION Rand(INTEGER);
--
CREATE FUNCTION Rand(INTEGER)
RETURNING INTEGER
EXTERNAL NAME "$INFORMIXDIR/extend/Rand/bin/Random.bld(RandomWithMax)"
LANGUAGE C;
--
GRANT EXECUTE ON FUNCTION Rand (INTEGER) TO PUBLIC;
--
-- DROP FUNCTION SeededBinomial( INTEGER, REAL, INTEGER );
--
CREATE FUNCTION SeededBinomial( INTEGER, REAL, INTEGER )
RETURNING REAL
EXTERNAL NAME "$INFORMIXDIR/extend/Rand/bin/Random.bld(BinomialWithSeed)"
LANGUAGE C;
--
GRANT EXECUTE ON FUNCTION SeededBinomial ( INTEGER , REAL, INTEGER ) TO PUBLIC;
--
-- DROP FUNCTION Binomial( INTEGER, REAL );
--
CREATE FUNCTION Binomial( INTEGER, REAL )
RETURNING REAL
EXTERNAL NAME "$INFORMIXDIR/extend/Rand/bin/Random.bld(BinomialNoSeed)"
LANGUAGE C;
--
GRANT EXECUTE ON FUNCTION Binomial ( INTEGER, REAL ) TO PUBLIC;
--
CREATE FUNCTION SeededNormal( INTEGER )
RETURNING REAL
EXTERNAL NAME "$INFORMIXDIR/extend/Rand/bin/Random.bld(NormalWithSeed)"
LANGUAGE C;
--
GRANT EXECUTE ON FUNCTION SeededNormal ( INTEGER ) TO PUBLIC;
--
CREATE FUNCTION Normal()
RETURNING REAL
EXTERNAL NAME "$INFORMIXDIR/extend/Rand/bin/Random.bld(NormalNoSeed)"
LANGUAGE C;
--
GRANT EXECUTE ON FUNCTION Normal () TO PUBLIC;
--
CREATE FUNCTION Normal( REAL, REAL )
RETURNING REAL
EXTERNAL NAME "$INFORMIXDIR/extend/Rand/bin/Random.bld(NormalMeanDev)"
LANGUAGE C;
--
GRANT EXECUTE ON FUNCTION Normal ( REAL, REAL ) TO PUBLIC;
--
CREATE FUNCTION SeededNormal( REAL, REAL, INTEGER )
RETURNING REAL
EXTERNAL NAME "$INFORMIXDIR/extend/Rand/bin/Random.bld(NormalMeanDevSeed)"
LANGUAGE C;
--
GRANT EXECUTE ON FUNCTION SeededNormal ( REAL, REAL, INTEGER ) TO PUBLIC;
--
EXECUTE FUNCTION Rand();
