CREATE FUNCTION AncestorsSet( Arg1 NODE )
RETURNS SET(NODE NOT NULL)
	DEFINE 	setRetVal	SET(NODE NOT NULL);
	DEFINE  nNode		NODE;
	
	FOREACH EXECUTE FUNCTION Ancestors(Arg1) INTO nNode
		INSERT INTO TABLE(setRetVal) VALUES ( nNode );
	END FOREACH;

	RETURN setRetVal;

END FUNCTION;
