-- Generated by BladeSmith 4.00.TC1B2DO NOT MODIFY. --

execute procedure ifx_allow_newline('t');

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "idnCallFIFO (lvarchar)",
	"%SYSBLDUSER%", 0,
	"create function idnCallFIFO (lvarchar)
returns lvarchar
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/idn_fifo.bld(idnCallFIFO)"" language c;

",
	"f",
	"drop function idnCallFIFO (lvarchar);

",
	"f"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-idnCallFIFO (lvarchar)",
	"%SYSBLDUSER%", 0,
	"alter function idnCallFIFO (lvarchar)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/idn_fifo.bld(idnCallFIFO)"");

",
	"f",
	"alter function idnCallFIFO (lvarchar)
	with (Modify External Name = ""idnCallFIFO"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-idnCallFIFO (lvarchar)",
	"%SYSBLDUSER%",
	5, "idnCallFIFO (lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 151, "Alter-Class-idnCallFIFO (lvarchar)",
	"%SYSBLDUSER%", 0,
	"alter function idnCallFIFO (lvarchar)
	with (add class=""IDN"");

",
	"f",
	"alter function idnCallFIFO (lvarchar)
	with (drop class);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	151, "Alter-Class-idnCallFIFO (lvarchar)",
	"%SYSBLDUSER%",
	5, "idnCallFIFO (lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "idnCallFIFO (lvarchar)",
	"%SYSBLDUSER%", 0,
	"grant execute on function idnCallFIFO (lvarchar) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "idnCallFIFO (lvarchar)",
	"%SYSBLDUSER%",
	5, "idnCallFIFO (lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 0, "sysbldregistered",
	"%SYSBLDUSER%", 0,
	"insert into sysbldregistered
	(bld_id)
values
(
	""%SYSBLDNAME%""
);

",
	"f",
	"delete from sysbldregistered
	where bld_id = ""%SYSBLDNAME%"";

",
	"f"
);

