-- Generated by BladeSmith 4.00.TC1B2DO NOT MODIFY. --

execute procedure ifx_allow_newline('t');

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "cppRoutine (integer)",
	"%SYSBLDUSER%", 0,
	"create function cppRoutine (integer)
returns lvarchar
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/idn_LegacyCPP.bld(cppRoutine)"" language c;

",
	"f",
	"drop function cppRoutine (integer);

",
	"f"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-cppRoutine (integer)",
	"%SYSBLDUSER%", 0,
	"alter function cppRoutine (integer)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/idn_LegacyCPP.bld(cppRoutine)"");

",
	"f",
	"alter function cppRoutine (integer)
	with (Modify External Name = ""cppRoutine"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-cppRoutine (integer)",
	"%SYSBLDUSER%",
	5, "cppRoutine (integer)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "cppRoutine (integer)",
	"%SYSBLDUSER%", 0,
	"grant execute on function cppRoutine (integer) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "cppRoutine (integer)",
	"%SYSBLDUSER%",
	5, "cppRoutine (integer)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "cppTraceOn ()",
	"%SYSBLDUSER%", 0,
	"create function cppTraceOn ()
returns integer
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/idn_LegacyCPP.bld(cppTraceOn)"" language c;

",
	"f",
	"drop function cppTraceOn ();

",
	"f"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-cppTraceOn ()",
	"%SYSBLDUSER%", 0,
	"alter function cppTraceOn ()
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/idn_LegacyCPP.bld(cppTraceOn)"");

",
	"f",
	"alter function cppTraceOn ()
	with (Modify External Name = ""cppTraceOn"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-cppTraceOn ()",
	"%SYSBLDUSER%",
	5, "cppTraceOn ()",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "cppTraceOn ()",
	"%SYSBLDUSER%", 0,
	"grant execute on function cppTraceOn () to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "cppTraceOn ()",
	"%SYSBLDUSER%",
	5, "cppTraceOn ()",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 0, "sysbldregistered",
	"%SYSBLDUSER%", 0,
	"insert into sysbldregistered
	(bld_id)
values
(
	""%SYSBLDNAME%""
);

",
	"f",
	"delete from sysbldregistered
	where bld_id = ""%SYSBLDNAME%"";

",
	"f"
);

