-- Generated by BladeSmith 4.00.TC2  DO NOT MODIFY. --

execute procedure ifx_allow_newline('t');

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 0, "Tracing",
	"%SYSBLDUSER%", 0,
	"--
-- Add statements for supporting Tracing.
--
insert into systraceclasses (name) values ('SqlLibC');

insert into systracemsgs (name, locale, message)
values
(""SqlLibC_UDR_ENTER"", ""en_us.8859-1"",
""%UDRNAME%: function entry.""
);

insert into systracemsgs (name, locale, message)
values
(""SqlLibC_UDR_EXIT"", ""en_us.8859-1"",
""%UDRNAME%: function exit.""
);
",
	"f",
	"delete from systraceclasses where  name='SqlLibC';

delete from systracemsgs where name='SqlLibC_UDR_ENTER';
delete from systracemsgs where name='SqlLibC_UDR_EXIT';
",
	"f"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 0, "SqlLibC_raise_err",
	"%SYSBLDUSER%", 0,
	"create function sqllibc_raise_err(error_code integer)
returning integer;
        raise exception error_code;
         return error_code;
end function;                         
",
	"f",
	"drop function sqllibc_raise_err(integer);
",
	"f"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "ascii (char)",
	"%SYSBLDUSER%", 0,
	"create function ascii (char)
returns integer
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/SqlLibC.bld(SqlLibC_ascii)"" language c;

",
	"f",
	"drop function ascii (char);

",
	"f"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-ascii (char)",
	"%SYSBLDUSER%", 0,
	"alter function ascii (char)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/SqlLibC.bld(SqlLibC_ascii)"");

",
	"f",
	"alter function ascii (char)
	with (Modify External Name = ""SqlLibC_ascii"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-ascii (char)",
	"%SYSBLDUSER%",
	5, "ascii (char)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 37, "Alter-Parallelize-ascii (char)",
	"%SYSBLDUSER%", 0,
	"alter function ascii (char)
	with (add parallelizable);

",
	"f",
	"alter function ascii (char)
	with (drop parallelizable);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	37, "Alter-Parallelize-ascii (char)",
	"%SYSBLDUSER%",
	5, "ascii (char)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 85, "Alter-Variant-ascii (char)",
	"%SYSBLDUSER%", 0,
	"alter function ascii (char)
	with (add not variant);

",
	"f",
	"alter function ascii (char)
	with (drop not variant);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	85, "Alter-Variant-ascii (char)",
	"%SYSBLDUSER%",
	5, "ascii (char)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "ascii (char)",
	"%SYSBLDUSER%", 0,
	"grant execute on function ascii (char) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "ascii (char)",
	"%SYSBLDUSER%",
	5, "ascii (char)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "ceil (double precision)",
	"%SYSBLDUSER%", 0,
	"create function ceil (double precision)
returns integer
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/SqlLibC.bld(SqlLibC_ceil)"" language c;

",
	"f",
	"drop function ceil (double precision);

",
	"f"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-ceil (double precision)",
	"%SYSBLDUSER%", 0,
	"alter function ceil (double precision)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/SqlLibC.bld(SqlLibC_ceil)"");

",
	"f",
	"alter function ceil (double precision)
	with (Modify External Name = ""SqlLibC_ceil"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-ceil (double precision)",
	"%SYSBLDUSER%",
	5, "ceil (double precision)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 37, "Alter-Parallelize-ceil (double precision)",
	"%SYSBLDUSER%", 0,
	"alter function ceil (double precision)
	with (add parallelizable);

",
	"f",
	"alter function ceil (double precision)
	with (drop parallelizable);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	37, "Alter-Parallelize-ceil (double precision)",
	"%SYSBLDUSER%",
	5, "ceil (double precision)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 85, "Alter-Variant-ceil (double precision)",
	"%SYSBLDUSER%", 0,
	"alter function ceil (double precision)
	with (add not variant);

",
	"f",
	"alter function ceil (double precision)
	with (drop not variant);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	85, "Alter-Variant-ceil (double precision)",
	"%SYSBLDUSER%",
	5, "ceil (double precision)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "ceil (double precision)",
	"%SYSBLDUSER%", 0,
	"grant execute on function ceil (double precision) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "ceil (double precision)",
	"%SYSBLDUSER%",
	5, "ceil (double precision)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "chr (integer)",
	"%SYSBLDUSER%", 0,
	"create function chr (integer)
returns char
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/SqlLibC.bld(SqlLibC_chr)"" language c;

",
	"f",
	"drop function chr (integer);

",
	"f"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-chr (integer)",
	"%SYSBLDUSER%", 0,
	"alter function chr (integer)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/SqlLibC.bld(SqlLibC_chr)"");

",
	"f",
	"alter function chr (integer)
	with (Modify External Name = ""SqlLibC_chr"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-chr (integer)",
	"%SYSBLDUSER%",
	5, "chr (integer)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 37, "Alter-Parallelize-chr (integer)",
	"%SYSBLDUSER%", 0,
	"alter function chr (integer)
	with (add parallelizable);

",
	"f",
	"alter function chr (integer)
	with (drop parallelizable);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	37, "Alter-Parallelize-chr (integer)",
	"%SYSBLDUSER%",
	5, "chr (integer)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 85, "Alter-Variant-chr (integer)",
	"%SYSBLDUSER%", 0,
	"alter function chr (integer)
	with (add not variant);

",
	"f",
	"alter function chr (integer)
	with (drop not variant);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	85, "Alter-Variant-chr (integer)",
	"%SYSBLDUSER%",
	5, "chr (integer)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "chr (integer)",
	"%SYSBLDUSER%", 0,
	"grant execute on function chr (integer) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "chr (integer)",
	"%SYSBLDUSER%",
	5, "chr (integer)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "instr (lvarchar,lvarchar)",
	"%SYSBLDUSER%", 0,
	"create function instr (lvarchar,lvarchar)
returns integer
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/SqlLibC.bld(SqlLibC_instr_2)"" language c;

",
	"f",
	"drop function instr (lvarchar,lvarchar);

",
	"f"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-instr (lvarchar,lvarchar)",
	"%SYSBLDUSER%", 0,
	"alter function instr (lvarchar,lvarchar)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/SqlLibC.bld(SqlLibC_instr_2)"");

",
	"f",
	"alter function instr (lvarchar,lvarchar)
	with (Modify External Name = ""SqlLibC_instr_2"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-instr (lvarchar,lvarchar)",
	"%SYSBLDUSER%",
	5, "instr (lvarchar,lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 37, "Alter-Parallelize-instr (lvarchar,lvarchar)",
	"%SYSBLDUSER%", 0,
	"alter function instr (lvarchar,lvarchar)
	with (add parallelizable);

",
	"f",
	"alter function instr (lvarchar,lvarchar)
	with (drop parallelizable);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	37, "Alter-Parallelize-instr (lvarchar,lvarchar)",
	"%SYSBLDUSER%",
	5, "instr (lvarchar,lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 85, "Alter-Variant-instr (lvarchar,lvarchar)",
	"%SYSBLDUSER%", 0,
	"alter function instr (lvarchar,lvarchar)
	with (add not variant);

",
	"f",
	"alter function instr (lvarchar,lvarchar)
	with (drop not variant);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	85, "Alter-Variant-instr (lvarchar,lvarchar)",
	"%SYSBLDUSER%",
	5, "instr (lvarchar,lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "instr (lvarchar,lvarchar)",
	"%SYSBLDUSER%", 0,
	"grant execute on function instr (lvarchar,lvarchar) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "instr (lvarchar,lvarchar)",
	"%SYSBLDUSER%",
	5, "instr (lvarchar,lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "instr (lvarchar,lvarchar,integer)",
	"%SYSBLDUSER%", 0,
	"create function instr (lvarchar,lvarchar,integer)
returns integer
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/SqlLibC.bld(SqlLibC_instr_3)"" language c;

",
	"f",
	"drop function instr (lvarchar,lvarchar,integer);

",
	"f"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-instr (lvarchar,lvarchar,integer)",
	"%SYSBLDUSER%", 0,
	"alter function instr (lvarchar,lvarchar,integer)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/SqlLibC.bld(SqlLibC_instr_3)"");

",
	"f",
	"alter function instr (lvarchar,lvarchar,integer)
	with (Modify External Name = ""SqlLibC_instr_3"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-instr (lvarchar,lvarchar,integer)",
	"%SYSBLDUSER%",
	5, "instr (lvarchar,lvarchar,integer)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 37, "Alter-Parallelize-instr (lvarchar,lvarchar,integer)",
	"%SYSBLDUSER%", 0,
	"alter function instr (lvarchar,lvarchar,integer)
	with (add parallelizable);

",
	"f",
	"alter function instr (lvarchar,lvarchar,integer)
	with (drop parallelizable);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	37, "Alter-Parallelize-instr (lvarchar,lvarchar,integer)",
	"%SYSBLDUSER%",
	5, "instr (lvarchar,lvarchar,integer)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 85, "Alter-Variant-instr (lvarchar,lvarchar,integer)",
	"%SYSBLDUSER%", 0,
	"alter function instr (lvarchar,lvarchar,integer)
	with (add not variant);

",
	"f",
	"alter function instr (lvarchar,lvarchar,integer)
	with (drop not variant);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	85, "Alter-Variant-instr (lvarchar,lvarchar,integer)",
	"%SYSBLDUSER%",
	5, "instr (lvarchar,lvarchar,integer)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "instr (lvarchar,lvarchar,integer)",
	"%SYSBLDUSER%", 0,
	"grant execute on function instr (lvarchar,lvarchar,integer) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "instr (lvarchar,lvarchar,integer)",
	"%SYSBLDUSER%",
	5, "instr (lvarchar,lvarchar,integer)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "instr (lvarchar,lvarchar,integer,integer)",
	"%SYSBLDUSER%", 0,
	"create function instr (lvarchar,lvarchar,integer,integer)
returns integer
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/SqlLibC.bld(SqlLibC_instr_4)"" language c;

",
	"f",
	"drop function instr (lvarchar,lvarchar,integer,integer);

",
	"f"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-instr (lvarchar,lvarchar,integer,integer)",
	"%SYSBLDUSER%", 0,
	"alter function instr (lvarchar,lvarchar,integer,integer)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/SqlLibC.bld(SqlLibC_instr_4)"");

",
	"f",
	"alter function instr (lvarchar,lvarchar,integer,integer)
	with (Modify External Name = ""SqlLibC_instr_4"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-instr (lvarchar,lvarchar,integer,integer)",
	"%SYSBLDUSER%",
	5, "instr (lvarchar,lvarchar,integer,integer)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 37, "Alter-Parallelize-instr (lvarchar,lvarchar,integer,integer)",
	"%SYSBLDUSER%", 0,
	"alter function instr (lvarchar,lvarchar,integer,integer)
	with (add parallelizable);

",
	"f",
	"alter function instr (lvarchar,lvarchar,integer,integer)
	with (drop parallelizable);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	37, "Alter-Parallelize-instr (lvarchar,lvarchar,integer,integer)",
	"%SYSBLDUSER%",
	5, "instr (lvarchar,lvarchar,integer,integer)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 85, "Alter-Variant-instr (lvarchar,lvarchar,integer,integer)",
	"%SYSBLDUSER%", 0,
	"alter function instr (lvarchar,lvarchar,integer,integer)
	with (add not variant);

",
	"f",
	"alter function instr (lvarchar,lvarchar,integer,integer)
	with (drop not variant);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	85, "Alter-Variant-instr (lvarchar,lvarchar,integer,integer)",
	"%SYSBLDUSER%",
	5, "instr (lvarchar,lvarchar,integer,integer)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "instr (lvarchar,lvarchar,integer,integer)",
	"%SYSBLDUSER%", 0,
	"grant execute on function instr (lvarchar,lvarchar,integer,integer) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "instr (lvarchar,lvarchar,integer,integer)",
	"%SYSBLDUSER%",
	5, "instr (lvarchar,lvarchar,integer,integer)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "instrb (lvarchar,lvarchar)",
	"%SYSBLDUSER%", 0,
	"create function instrb (lvarchar,lvarchar)
returns integer
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/SqlLibC.bld(SqlLibC_instrb_2)"" language c;

",
	"f",
	"drop function instrb (lvarchar,lvarchar);

",
	"f"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-instrb (lvarchar,lvarchar)",
	"%SYSBLDUSER%", 0,
	"alter function instrb (lvarchar,lvarchar)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/SqlLibC.bld(SqlLibC_instrb_2)"");

",
	"f",
	"alter function instrb (lvarchar,lvarchar)
	with (Modify External Name = ""SqlLibC_instrb_2"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-instrb (lvarchar,lvarchar)",
	"%SYSBLDUSER%",
	5, "instrb (lvarchar,lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 37, "Alter-Parallelize-instrb (lvarchar,lvarchar)",
	"%SYSBLDUSER%", 0,
	"alter function instrb (lvarchar,lvarchar)
	with (add parallelizable);

",
	"f",
	"alter function instrb (lvarchar,lvarchar)
	with (drop parallelizable);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	37, "Alter-Parallelize-instrb (lvarchar,lvarchar)",
	"%SYSBLDUSER%",
	5, "instrb (lvarchar,lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 85, "Alter-Variant-instrb (lvarchar,lvarchar)",
	"%SYSBLDUSER%", 0,
	"alter function instrb (lvarchar,lvarchar)
	with (add not variant);

",
	"f",
	"alter function instrb (lvarchar,lvarchar)
	with (drop not variant);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	85, "Alter-Variant-instrb (lvarchar,lvarchar)",
	"%SYSBLDUSER%",
	5, "instrb (lvarchar,lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "instrb (lvarchar,lvarchar)",
	"%SYSBLDUSER%", 0,
	"grant execute on function instrb (lvarchar,lvarchar) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "instrb (lvarchar,lvarchar)",
	"%SYSBLDUSER%",
	5, "instrb (lvarchar,lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "instrb (lvarchar,lvarchar,integer)",
	"%SYSBLDUSER%", 0,
	"create function instrb (lvarchar,lvarchar,integer)
returns integer
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/SqlLibC.bld(SqlLibC_instrb_3)"" language c;

",
	"f",
	"drop function instrb (lvarchar,lvarchar,integer);

",
	"f"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-instrb (lvarchar,lvarchar,integer)",
	"%SYSBLDUSER%", 0,
	"alter function instrb (lvarchar,lvarchar,integer)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/SqlLibC.bld(SqlLibC_instrb_3)"");

",
	"f",
	"alter function instrb (lvarchar,lvarchar,integer)
	with (Modify External Name = ""SqlLibC_instrb_3"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-instrb (lvarchar,lvarchar,integer)",
	"%SYSBLDUSER%",
	5, "instrb (lvarchar,lvarchar,integer)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 37, "Alter-Parallelize-instrb (lvarchar,lvarchar,integer)",
	"%SYSBLDUSER%", 0,
	"alter function instrb (lvarchar,lvarchar,integer)
	with (add parallelizable);

",
	"f",
	"alter function instrb (lvarchar,lvarchar,integer)
	with (drop parallelizable);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	37, "Alter-Parallelize-instrb (lvarchar,lvarchar,integer)",
	"%SYSBLDUSER%",
	5, "instrb (lvarchar,lvarchar,integer)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 85, "Alter-Variant-instrb (lvarchar,lvarchar,integer)",
	"%SYSBLDUSER%", 0,
	"alter function instrb (lvarchar,lvarchar,integer)
	with (add not variant);

",
	"f",
	"alter function instrb (lvarchar,lvarchar,integer)
	with (drop not variant);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	85, "Alter-Variant-instrb (lvarchar,lvarchar,integer)",
	"%SYSBLDUSER%",
	5, "instrb (lvarchar,lvarchar,integer)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "instrb (lvarchar,lvarchar,integer)",
	"%SYSBLDUSER%", 0,
	"grant execute on function instrb (lvarchar,lvarchar,integer) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "instrb (lvarchar,lvarchar,integer)",
	"%SYSBLDUSER%",
	5, "instrb (lvarchar,lvarchar,integer)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "instrb (lvarchar,lvarchar,integer,integer)",
	"%SYSBLDUSER%", 0,
	"create function instrb (lvarchar,lvarchar,integer,integer)
returns integer
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/SqlLibC.bld(SqlLibC_instrb_4)"" language c;

",
	"f",
	"drop function instrb (lvarchar,lvarchar,integer,integer);

",
	"f"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-instrb (lvarchar,lvarchar,integer,integer)",
	"%SYSBLDUSER%", 0,
	"alter function instrb (lvarchar,lvarchar,integer,integer)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/SqlLibC.bld(SqlLibC_instrb_4)"");

",
	"f",
	"alter function instrb (lvarchar,lvarchar,integer,integer)
	with (Modify External Name = ""SqlLibC_instrb_4"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-instrb (lvarchar,lvarchar,integer,integer)",
	"%SYSBLDUSER%",
	5, "instrb (lvarchar,lvarchar,integer,integer)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 37, "Alter-Parallelize-instrb (lvarchar,lvarchar,integer,integer)",
	"%SYSBLDUSER%", 0,
	"alter function instrb (lvarchar,lvarchar,integer,integer)
	with (add parallelizable);

",
	"f",
	"alter function instrb (lvarchar,lvarchar,integer,integer)
	with (drop parallelizable);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	37, "Alter-Parallelize-instrb (lvarchar,lvarchar,integer,integer)",
	"%SYSBLDUSER%",
	5, "instrb (lvarchar,lvarchar,integer,integer)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 85, "Alter-Variant-instrb (lvarchar,lvarchar,integer,integer)",
	"%SYSBLDUSER%", 0,
	"alter function instrb (lvarchar,lvarchar,integer,integer)
	with (add not variant);

",
	"f",
	"alter function instrb (lvarchar,lvarchar,integer,integer)
	with (drop not variant);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	85, "Alter-Variant-instrb (lvarchar,lvarchar,integer,integer)",
	"%SYSBLDUSER%",
	5, "instrb (lvarchar,lvarchar,integer,integer)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "instrb (lvarchar,lvarchar,integer,integer)",
	"%SYSBLDUSER%", 0,
	"grant execute on function instrb (lvarchar,lvarchar,integer,integer) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "instrb (lvarchar,lvarchar,integer,integer)",
	"%SYSBLDUSER%",
	5, "instrb (lvarchar,lvarchar,integer,integer)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "sign (double precision)",
	"%SYSBLDUSER%", 0,
	"create function sign (double precision)
returns integer
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/SqlLibC.bld(SqlLibC_sign)"" language c;

",
	"f",
	"drop function sign (double precision);

",
	"f"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-sign (double precision)",
	"%SYSBLDUSER%", 0,
	"alter function sign (double precision)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/SqlLibC.bld(SqlLibC_sign)"");

",
	"f",
	"alter function sign (double precision)
	with (Modify External Name = ""SqlLibC_sign"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-sign (double precision)",
	"%SYSBLDUSER%",
	5, "sign (double precision)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 37, "Alter-Parallelize-sign (double precision)",
	"%SYSBLDUSER%", 0,
	"alter function sign (double precision)
	with (add parallelizable);

",
	"f",
	"alter function sign (double precision)
	with (drop parallelizable);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	37, "Alter-Parallelize-sign (double precision)",
	"%SYSBLDUSER%",
	5, "sign (double precision)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 85, "Alter-Variant-sign (double precision)",
	"%SYSBLDUSER%", 0,
	"alter function sign (double precision)
	with (add not variant);

",
	"f",
	"alter function sign (double precision)
	with (drop not variant);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	85, "Alter-Variant-sign (double precision)",
	"%SYSBLDUSER%",
	5, "sign (double precision)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "sign (double precision)",
	"%SYSBLDUSER%", 0,
	"grant execute on function sign (double precision) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "sign (double precision)",
	"%SYSBLDUSER%",
	5, "sign (double precision)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 6, "SqlLibC_Trace (lvarchar,integer)",
	"%SYSBLDUSER%", 0,
	"create procedure SqlLibC_Trace (lvarchar,integer)
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/SqlLibC.bld(TraceSet_SqlLibC)"" language c;

",
	"f",
	"drop procedure SqlLibC_Trace (lvarchar,integer);

",
	"f"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 182, "Alter-ExternalName-SqlLibC_Trace (lvarchar,integer)",
	"%SYSBLDUSER%", 0,
	"alter procedure SqlLibC_Trace (lvarchar,integer)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/SqlLibC.bld(TraceSet_SqlLibC)"");

",
	"f",
	"alter procedure SqlLibC_Trace (lvarchar,integer)
	with (Modify External Name = ""TraceSet_SqlLibC"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	182, "Alter-ExternalName-SqlLibC_Trace (lvarchar,integer)",
	"%SYSBLDUSER%",
	6, "SqlLibC_Trace (lvarchar,integer)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 70, "SqlLibC_Trace (lvarchar,integer)",
	"%SYSBLDUSER%", 0,
	"grant execute on procedure SqlLibC_Trace (lvarchar,integer) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	70, "SqlLibC_Trace (lvarchar,integer)",
	"%SYSBLDUSER%",
	6, "SqlLibC_Trace (lvarchar,integer)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "to_integer (lvarchar)",
	"%SYSBLDUSER%", 0,
	"create function to_integer (lvarchar)
returns integer
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/SqlLibC.bld(SqlLibC_to_integer)"" language c;

",
	"f",
	"drop function to_integer (lvarchar);

",
	"f"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-to_integer (lvarchar)",
	"%SYSBLDUSER%", 0,
	"alter function to_integer (lvarchar)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/SqlLibC.bld(SqlLibC_to_integer)"");

",
	"f",
	"alter function to_integer (lvarchar)
	with (Modify External Name = ""SqlLibC_to_integer"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-to_integer (lvarchar)",
	"%SYSBLDUSER%",
	5, "to_integer (lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 37, "Alter-Parallelize-to_integer (lvarchar)",
	"%SYSBLDUSER%", 0,
	"alter function to_integer (lvarchar)
	with (add parallelizable);

",
	"f",
	"alter function to_integer (lvarchar)
	with (drop parallelizable);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	37, "Alter-Parallelize-to_integer (lvarchar)",
	"%SYSBLDUSER%",
	5, "to_integer (lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 85, "Alter-Variant-to_integer (lvarchar)",
	"%SYSBLDUSER%", 0,
	"alter function to_integer (lvarchar)
	with (add not variant);

",
	"f",
	"alter function to_integer (lvarchar)
	with (drop not variant);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	85, "Alter-Variant-to_integer (lvarchar)",
	"%SYSBLDUSER%",
	5, "to_integer (lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "to_integer (lvarchar)",
	"%SYSBLDUSER%", 0,
	"grant execute on function to_integer (lvarchar) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "to_integer (lvarchar)",
	"%SYSBLDUSER%",
	5, "to_integer (lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "to_float (lvarchar)",
	"%SYSBLDUSER%", 0,
	"create function to_float (lvarchar)
returns float
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/SqlLibC.bld(SqlLibC_to_float)"" language c;

",
	"f",
	"drop function to_float (lvarchar);

",
	"f"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-to_float (lvarchar)",
	"%SYSBLDUSER%", 0,
	"alter function to_float (lvarchar)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/SqlLibC.bld(SqlLibC_to_float)"");

",
	"f",
	"alter function to_float (lvarchar)
	with (Modify External Name = ""SqlLibC_to_float"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-to_float (lvarchar)",
	"%SYSBLDUSER%",
	5, "to_float (lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 37, "Alter-Parallelize-to_float (lvarchar)",
	"%SYSBLDUSER%", 0,
	"alter function to_float (lvarchar)
	with (add parallelizable);

",
	"f",
	"alter function to_float (lvarchar)
	with (drop parallelizable);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	37, "Alter-Parallelize-to_float (lvarchar)",
	"%SYSBLDUSER%",
	5, "to_float (lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 85, "Alter-Variant-to_float (lvarchar)",
	"%SYSBLDUSER%", 0,
	"alter function to_float (lvarchar)
	with (add not variant);

",
	"f",
	"alter function to_float (lvarchar)
	with (drop not variant);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	85, "Alter-Variant-to_float (lvarchar)",
	"%SYSBLDUSER%",
	5, "to_float (lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "to_float (lvarchar)",
	"%SYSBLDUSER%", 0,
	"grant execute on function to_float (lvarchar) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "to_float (lvarchar)",
	"%SYSBLDUSER%",
	5, "to_float (lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "to_decimal (lvarchar)",
	"%SYSBLDUSER%", 0,
	"create function to_decimal (lvarchar)
returns decimal
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/SqlLibC.bld(SqlLibC_to_decimal)"" language c;

",
	"f",
	"drop function to_decimal (lvarchar);

",
	"f"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-to_decimal (lvarchar)",
	"%SYSBLDUSER%", 0,
	"alter function to_decimal (lvarchar)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/SqlLibC.bld(SqlLibC_to_decimal)"");

",
	"f",
	"alter function to_decimal (lvarchar)
	with (Modify External Name = ""SqlLibC_to_decimal"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-to_decimal (lvarchar)",
	"%SYSBLDUSER%",
	5, "to_decimal (lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 37, "Alter-Parallelize-to_decimal (lvarchar)",
	"%SYSBLDUSER%", 0,
	"alter function to_decimal (lvarchar)
	with (add parallelizable);

",
	"f",
	"alter function to_decimal (lvarchar)
	with (drop parallelizable);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	37, "Alter-Parallelize-to_decimal (lvarchar)",
	"%SYSBLDUSER%",
	5, "to_decimal (lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 85, "Alter-Variant-to_decimal (lvarchar)",
	"%SYSBLDUSER%", 0,
	"alter function to_decimal (lvarchar)
	with (add not variant);

",
	"f",
	"alter function to_decimal (lvarchar)
	with (drop not variant);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	85, "Alter-Variant-to_decimal (lvarchar)",
	"%SYSBLDUSER%",
	5, "to_decimal (lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "to_decimal (lvarchar)",
	"%SYSBLDUSER%", 0,
	"grant execute on function to_decimal (lvarchar) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "to_decimal (lvarchar)",
	"%SYSBLDUSER%",
	5, "to_decimal (lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "to_decimal (lvarchar,lvarchar)",
	"%SYSBLDUSER%", 0,
	"create function to_decimal (lvarchar,lvarchar)
returns decimal
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/SqlLibC.bld(SqlLibC_to_decimal_fmt)"" language c;

",
	"f",
	"drop function to_decimal (lvarchar,lvarchar);

",
	"f"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-to_decimal (lvarchar,lvarchar)",
	"%SYSBLDUSER%", 0,
	"alter function to_decimal (lvarchar,lvarchar)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/SqlLibC.bld(SqlLibC_to_decimal_fmt)"");

",
	"f",
	"alter function to_decimal (lvarchar,lvarchar)
	with (Modify External Name = ""SqlLibC_to_decimal_fmt"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-to_decimal (lvarchar,lvarchar)",
	"%SYSBLDUSER%",
	5, "to_decimal (lvarchar,lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 37, "Alter-Parallelize-to_decimal (lvarchar,lvarchar)",
	"%SYSBLDUSER%", 0,
	"alter function to_decimal (lvarchar,lvarchar)
	with (add parallelizable);

",
	"f",
	"alter function to_decimal (lvarchar,lvarchar)
	with (drop parallelizable);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	37, "Alter-Parallelize-to_decimal (lvarchar,lvarchar)",
	"%SYSBLDUSER%",
	5, "to_decimal (lvarchar,lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 55, "Alter-HandleNul-to_decimal (lvarchar,lvarchar)",
	"%SYSBLDUSER%", 0,
	"alter function to_decimal (lvarchar,lvarchar)
	with (add handlesnulls);

",
	"f",
	"alter function to_decimal (lvarchar,lvarchar)
	with (drop handlesnulls);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	55, "Alter-HandleNul-to_decimal (lvarchar,lvarchar)",
	"%SYSBLDUSER%",
	5, "to_decimal (lvarchar,lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 85, "Alter-Variant-to_decimal (lvarchar,lvarchar)",
	"%SYSBLDUSER%", 0,
	"alter function to_decimal (lvarchar,lvarchar)
	with (add not variant);

",
	"f",
	"alter function to_decimal (lvarchar,lvarchar)
	with (drop not variant);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	85, "Alter-Variant-to_decimal (lvarchar,lvarchar)",
	"%SYSBLDUSER%",
	5, "to_decimal (lvarchar,lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "to_decimal (lvarchar,lvarchar)",
	"%SYSBLDUSER%", 0,
	"grant execute on function to_decimal (lvarchar,lvarchar) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "to_decimal (lvarchar,lvarchar)",
	"%SYSBLDUSER%",
	5, "to_decimal (lvarchar,lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "to_float (lvarchar,lvarchar)",
	"%SYSBLDUSER%", 0,
	"create function to_float (lvarchar,lvarchar)
returns float
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/SqlLibC.bld(SqlLibC_to_float_fmt)"" language c;

",
	"f",
	"drop function to_float (lvarchar,lvarchar);

",
	"f"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-to_float (lvarchar,lvarchar)",
	"%SYSBLDUSER%", 0,
	"alter function to_float (lvarchar,lvarchar)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/SqlLibC.bld(SqlLibC_to_float_fmt)"");

",
	"f",
	"alter function to_float (lvarchar,lvarchar)
	with (Modify External Name = ""SqlLibC_to_float_fmt"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-to_float (lvarchar,lvarchar)",
	"%SYSBLDUSER%",
	5, "to_float (lvarchar,lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 37, "Alter-Parallelize-to_float (lvarchar,lvarchar)",
	"%SYSBLDUSER%", 0,
	"alter function to_float (lvarchar,lvarchar)
	with (add parallelizable);

",
	"f",
	"alter function to_float (lvarchar,lvarchar)
	with (drop parallelizable);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	37, "Alter-Parallelize-to_float (lvarchar,lvarchar)",
	"%SYSBLDUSER%",
	5, "to_float (lvarchar,lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 55, "Alter-HandleNul-to_float (lvarchar,lvarchar)",
	"%SYSBLDUSER%", 0,
	"alter function to_float (lvarchar,lvarchar)
	with (add handlesnulls);

",
	"f",
	"alter function to_float (lvarchar,lvarchar)
	with (drop handlesnulls);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	55, "Alter-HandleNul-to_float (lvarchar,lvarchar)",
	"%SYSBLDUSER%",
	5, "to_float (lvarchar,lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 85, "Alter-Variant-to_float (lvarchar,lvarchar)",
	"%SYSBLDUSER%", 0,
	"alter function to_float (lvarchar,lvarchar)
	with (add not variant);

",
	"f",
	"alter function to_float (lvarchar,lvarchar)
	with (drop not variant);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	85, "Alter-Variant-to_float (lvarchar,lvarchar)",
	"%SYSBLDUSER%",
	5, "to_float (lvarchar,lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "to_float (lvarchar,lvarchar)",
	"%SYSBLDUSER%", 0,
	"grant execute on function to_float (lvarchar,lvarchar) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "to_float (lvarchar,lvarchar)",
	"%SYSBLDUSER%",
	5, "to_float (lvarchar,lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "to_integer (lvarchar,lvarchar)",
	"%SYSBLDUSER%", 0,
	"create function to_integer (lvarchar,lvarchar)
returns integer
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/SqlLibC.bld(SqlLibC_to_integer_fmt)"" language c;

",
	"f",
	"drop function to_integer (lvarchar,lvarchar);

",
	"f"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-to_integer (lvarchar,lvarchar)",
	"%SYSBLDUSER%", 0,
	"alter function to_integer (lvarchar,lvarchar)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/SqlLibC.bld(SqlLibC_to_integer_fmt)"");

",
	"f",
	"alter function to_integer (lvarchar,lvarchar)
	with (Modify External Name = ""SqlLibC_to_integer_fmt"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-to_integer (lvarchar,lvarchar)",
	"%SYSBLDUSER%",
	5, "to_integer (lvarchar,lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 37, "Alter-Parallelize-to_integer (lvarchar,lvarchar)",
	"%SYSBLDUSER%", 0,
	"alter function to_integer (lvarchar,lvarchar)
	with (add parallelizable);

",
	"f",
	"alter function to_integer (lvarchar,lvarchar)
	with (drop parallelizable);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	37, "Alter-Parallelize-to_integer (lvarchar,lvarchar)",
	"%SYSBLDUSER%",
	5, "to_integer (lvarchar,lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 55, "Alter-HandleNul-to_integer (lvarchar,lvarchar)",
	"%SYSBLDUSER%", 0,
	"alter function to_integer (lvarchar,lvarchar)
	with (add handlesnulls);

",
	"f",
	"alter function to_integer (lvarchar,lvarchar)
	with (drop handlesnulls);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	55, "Alter-HandleNul-to_integer (lvarchar,lvarchar)",
	"%SYSBLDUSER%",
	5, "to_integer (lvarchar,lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 85, "Alter-Variant-to_integer (lvarchar,lvarchar)",
	"%SYSBLDUSER%", 0,
	"alter function to_integer (lvarchar,lvarchar)
	with (add not variant);

",
	"f",
	"alter function to_integer (lvarchar,lvarchar)
	with (drop not variant);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	85, "Alter-Variant-to_integer (lvarchar,lvarchar)",
	"%SYSBLDUSER%",
	5, "to_integer (lvarchar,lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "to_integer (lvarchar,lvarchar)",
	"%SYSBLDUSER%", 0,
	"grant execute on function to_integer (lvarchar,lvarchar) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "to_integer (lvarchar,lvarchar)",
	"%SYSBLDUSER%",
	5, "to_integer (lvarchar,lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 0, "sysbldregistered",
	"%SYSBLDUSER%", 0,
	"insert into sysbldregistered
	(bld_id)
values
(
	""%SYSBLDNAME%""
);

",
	"f",
	"delete from sysbldregistered
	where bld_id = ""%SYSBLDNAME%"";

",
	"f"
);

