-- Generated by BladeSmith 4.00.TC1B2DO NOT MODIFY. --

execute procedure ifx_allow_newline('t');

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 7, "FIXType",
	"%SYSBLDUSER%", 0,
	"create opaque type FIXType(
	internallength = 16,
	alignment = 4
);

",
	"f",
	"drop type FIXType restrict;

",
	"f"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 71, "FIXType",
	"%SYSBLDUSER%", 0,
	"grant usage on type FIXType to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	71, "FIXType",
	"%SYSBLDUSER%",
	7, "FIXType",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "FIXTypeIn (lvarchar)",
	"%SYSBLDUSER%", 0,
	"create function FIXTypeIn (lvarchar)
returns FIXType
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/FIXType.bld(FIXTypeInput)"" language c;

",
	"f",
	"drop function FIXTypeIn (lvarchar);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	5, "FIXTypeIn (lvarchar)",
	"%SYSBLDUSER%",
	7, "FIXType",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-FIXTypeIn (lvarchar)",
	"%SYSBLDUSER%", 0,
	"alter function FIXTypeIn (lvarchar)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/FIXType.bld(FIXTypeInput)"");

",
	"f",
	"alter function FIXTypeIn (lvarchar)
	with (Modify External Name = ""FIXTypeInput"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-FIXTypeIn (lvarchar)",
	"%SYSBLDUSER%",
	5, "FIXTypeIn (lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "FIXTypeIn (lvarchar)",
	"%SYSBLDUSER%", 0,
	"grant execute on function FIXTypeIn (lvarchar) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "FIXTypeIn (lvarchar)",
	"%SYSBLDUSER%",
	5, "FIXTypeIn (lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 3, "lvarchar->FIXType",
	"%SYSBLDUSER%", 0,
	"create implicit cast
	(
		lvarchar as FIXType
		with  FIXTypeIn
	);

",
	"f",
	"drop cast (lvarchar as FIXType);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	3, "lvarchar->FIXType",
	"%SYSBLDUSER%",
	7, "FIXType",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "FIXTypeOut (FIXType)",
	"%SYSBLDUSER%", 0,
	"create function FIXTypeOut (FIXType)
returns lvarchar
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/FIXType.bld(FIXTypeOutput)"" language c;

",
	"f",
	"drop function FIXTypeOut (FIXType);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	5, "FIXTypeOut (FIXType)",
	"%SYSBLDUSER%",
	7, "FIXType",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-FIXTypeOut (FIXType)",
	"%SYSBLDUSER%", 0,
	"alter function FIXTypeOut (FIXType)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/FIXType.bld(FIXTypeOutput)"");

",
	"f",
	"alter function FIXTypeOut (FIXType)
	with (Modify External Name = ""FIXTypeOutput"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-FIXTypeOut (FIXType)",
	"%SYSBLDUSER%",
	5, "FIXTypeOut (FIXType)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "FIXTypeOut (FIXType)",
	"%SYSBLDUSER%", 0,
	"grant execute on function FIXTypeOut (FIXType) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "FIXTypeOut (FIXType)",
	"%SYSBLDUSER%",
	5, "FIXTypeOut (FIXType)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 3, "FIXType->lvarchar",
	"%SYSBLDUSER%", 0,
	"create cast
	(
		FIXType as lvarchar
		with  FIXTypeOut
	);

",
	"f",
	"drop cast (FIXType as lvarchar);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	3, "FIXType->lvarchar",
	"%SYSBLDUSER%",
	7, "FIXType",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "FIXTypeSend (FIXType)",
	"%SYSBLDUSER%", 0,
	"create function FIXTypeSend (FIXType)
returns sendrecv
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/FIXType.bld(FIXTypeSend)"" language c;

",
	"f",
	"drop function FIXTypeSend (FIXType);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	5, "FIXTypeSend (FIXType)",
	"%SYSBLDUSER%",
	7, "FIXType",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-FIXTypeSend (FIXType)",
	"%SYSBLDUSER%", 0,
	"alter function FIXTypeSend (FIXType)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/FIXType.bld(FIXTypeSend)"");

",
	"f",
	"alter function FIXTypeSend (FIXType)
	with (Modify External Name = ""FIXTypeSend"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-FIXTypeSend (FIXType)",
	"%SYSBLDUSER%",
	5, "FIXTypeSend (FIXType)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "FIXTypeSend (FIXType)",
	"%SYSBLDUSER%", 0,
	"grant execute on function FIXTypeSend (FIXType) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "FIXTypeSend (FIXType)",
	"%SYSBLDUSER%",
	5, "FIXTypeSend (FIXType)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 3, "FIXType->sendrecv",
	"%SYSBLDUSER%", 0,
	"create cast
	(
		FIXType as sendrecv
		with  FIXTypeSend
	);

",
	"f",
	"drop cast (FIXType as sendrecv);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	3, "FIXType->sendrecv",
	"%SYSBLDUSER%",
	7, "FIXType",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "FIXTypeRecv (sendrecv)",
	"%SYSBLDUSER%", 0,
	"create function FIXTypeRecv (sendrecv)
returns FIXType
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/FIXType.bld(FIXTypeReceive)"" language c;

",
	"f",
	"drop function FIXTypeRecv (sendrecv);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	5, "FIXTypeRecv (sendrecv)",
	"%SYSBLDUSER%",
	7, "FIXType",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-FIXTypeRecv (sendrecv)",
	"%SYSBLDUSER%", 0,
	"alter function FIXTypeRecv (sendrecv)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/FIXType.bld(FIXTypeReceive)"");

",
	"f",
	"alter function FIXTypeRecv (sendrecv)
	with (Modify External Name = ""FIXTypeReceive"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-FIXTypeRecv (sendrecv)",
	"%SYSBLDUSER%",
	5, "FIXTypeRecv (sendrecv)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "FIXTypeRecv (sendrecv)",
	"%SYSBLDUSER%", 0,
	"grant execute on function FIXTypeRecv (sendrecv) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "FIXTypeRecv (sendrecv)",
	"%SYSBLDUSER%",
	5, "FIXTypeRecv (sendrecv)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 3, "sendrecv->FIXType",
	"%SYSBLDUSER%", 0,
	"create implicit cast
	(
		sendrecv as FIXType
		with  FIXTypeRecv
	);

",
	"f",
	"drop cast (sendrecv as FIXType);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	3, "sendrecv->FIXType",
	"%SYSBLDUSER%",
	7, "FIXType",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "FIXTypeImpT (impexp)",
	"%SYSBLDUSER%", 0,
	"create function FIXTypeImpT (impexp)
returns FIXType
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/FIXType.bld(FIXTypeImportText)"" language c;

",
	"f",
	"drop function FIXTypeImpT (impexp);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	5, "FIXTypeImpT (impexp)",
	"%SYSBLDUSER%",
	7, "FIXType",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-FIXTypeImpT (impexp)",
	"%SYSBLDUSER%", 0,
	"alter function FIXTypeImpT (impexp)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/FIXType.bld(FIXTypeImportText)"");

",
	"f",
	"alter function FIXTypeImpT (impexp)
	with (Modify External Name = ""FIXTypeImportText"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-FIXTypeImpT (impexp)",
	"%SYSBLDUSER%",
	5, "FIXTypeImpT (impexp)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "FIXTypeImpT (impexp)",
	"%SYSBLDUSER%", 0,
	"grant execute on function FIXTypeImpT (impexp) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "FIXTypeImpT (impexp)",
	"%SYSBLDUSER%",
	5, "FIXTypeImpT (impexp)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 3, "impexp->FIXType",
	"%SYSBLDUSER%", 0,
	"create implicit cast
	(
		impexp as FIXType
		with  FIXTypeImpT
	);

",
	"f",
	"drop cast (impexp as FIXType);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	3, "impexp->FIXType",
	"%SYSBLDUSER%",
	7, "FIXType",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "FIXTypeExpT (FIXType)",
	"%SYSBLDUSER%", 0,
	"create function FIXTypeExpT (FIXType)
returns impexp
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/FIXType.bld(FIXTypeExportText)"" language c;

",
	"f",
	"drop function FIXTypeExpT (FIXType);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	5, "FIXTypeExpT (FIXType)",
	"%SYSBLDUSER%",
	7, "FIXType",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-FIXTypeExpT (FIXType)",
	"%SYSBLDUSER%", 0,
	"alter function FIXTypeExpT (FIXType)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/FIXType.bld(FIXTypeExportText)"");

",
	"f",
	"alter function FIXTypeExpT (FIXType)
	with (Modify External Name = ""FIXTypeExportText"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-FIXTypeExpT (FIXType)",
	"%SYSBLDUSER%",
	5, "FIXTypeExpT (FIXType)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "FIXTypeExpT (FIXType)",
	"%SYSBLDUSER%", 0,
	"grant execute on function FIXTypeExpT (FIXType) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "FIXTypeExpT (FIXType)",
	"%SYSBLDUSER%",
	5, "FIXTypeExpT (FIXType)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 3, "FIXType->impexp",
	"%SYSBLDUSER%", 0,
	"create cast
	(
		FIXType as impexp
		with  FIXTypeExpT
	);

",
	"f",
	"drop cast (FIXType as impexp);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	3, "FIXType->impexp",
	"%SYSBLDUSER%",
	7, "FIXType",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "FIXTypeImpB (impexpbin)",
	"%SYSBLDUSER%", 0,
	"create function FIXTypeImpB (impexpbin)
returns FIXType
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/FIXType.bld(FIXTypeImportBinary)"" language c;

",
	"f",
	"drop function FIXTypeImpB (impexpbin);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	5, "FIXTypeImpB (impexpbin)",
	"%SYSBLDUSER%",
	7, "FIXType",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-FIXTypeImpB (impexpbin)",
	"%SYSBLDUSER%", 0,
	"alter function FIXTypeImpB (impexpbin)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/FIXType.bld(FIXTypeImportBinary)"");

",
	"f",
	"alter function FIXTypeImpB (impexpbin)
	with (Modify External Name = ""FIXTypeImportBinary"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-FIXTypeImpB (impexpbin)",
	"%SYSBLDUSER%",
	5, "FIXTypeImpB (impexpbin)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "FIXTypeImpB (impexpbin)",
	"%SYSBLDUSER%", 0,
	"grant execute on function FIXTypeImpB (impexpbin) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "FIXTypeImpB (impexpbin)",
	"%SYSBLDUSER%",
	5, "FIXTypeImpB (impexpbin)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 3, "impexpbin->FIXType",
	"%SYSBLDUSER%", 0,
	"create implicit cast
	(
		impexpbin as FIXType
		with  FIXTypeImpB
	);

",
	"f",
	"drop cast (impexpbin as FIXType);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	3, "impexpbin->FIXType",
	"%SYSBLDUSER%",
	7, "FIXType",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "FIXTypeExpB (FIXType)",
	"%SYSBLDUSER%", 0,
	"create function FIXTypeExpB (FIXType)
returns impexpbin
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/FIXType.bld(FIXTypeExportBinary)"" language c;

",
	"f",
	"drop function FIXTypeExpB (FIXType);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	5, "FIXTypeExpB (FIXType)",
	"%SYSBLDUSER%",
	7, "FIXType",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-FIXTypeExpB (FIXType)",
	"%SYSBLDUSER%", 0,
	"alter function FIXTypeExpB (FIXType)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/FIXType.bld(FIXTypeExportBinary)"");

",
	"f",
	"alter function FIXTypeExpB (FIXType)
	with (Modify External Name = ""FIXTypeExportBinary"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-FIXTypeExpB (FIXType)",
	"%SYSBLDUSER%",
	5, "FIXTypeExpB (FIXType)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "FIXTypeExpB (FIXType)",
	"%SYSBLDUSER%", 0,
	"grant execute on function FIXTypeExpB (FIXType) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "FIXTypeExpB (FIXType)",
	"%SYSBLDUSER%",
	5, "FIXTypeExpB (FIXType)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 3, "FIXType->impexpbin",
	"%SYSBLDUSER%", 0,
	"create cast
	(
		FIXType as impexpbin
		with  FIXTypeExpB
	);

",
	"f",
	"drop cast (FIXType as impexpbin);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	3, "FIXType->impexpbin",
	"%SYSBLDUSER%",
	7, "FIXType",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "Compare (FIXType,FIXType)",
	"%SYSBLDUSER%", 0,
	"create function Compare (FIXType,FIXType)
returns integer
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/FIXType.bld(FIXTypeCompare)"" language c;

",
	"f",
	"drop function Compare (FIXType,FIXType);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	5, "Compare (FIXType,FIXType)",
	"%SYSBLDUSER%",
	7, "FIXType",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-Compare (FIXType,FIXType)",
	"%SYSBLDUSER%", 0,
	"alter function Compare (FIXType,FIXType)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/FIXType.bld(FIXTypeCompare)"");

",
	"f",
	"alter function Compare (FIXType,FIXType)
	with (Modify External Name = ""FIXTypeCompare"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-Compare (FIXType,FIXType)",
	"%SYSBLDUSER%",
	5, "Compare (FIXType,FIXType)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 85, "Alter-Variant-Compare (FIXType,FIXType)",
	"%SYSBLDUSER%", 0,
	"alter function Compare (FIXType,FIXType)
	with (add not variant);

",
	"f",
	"alter function Compare (FIXType,FIXType)
	with (drop not variant);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	85, "Alter-Variant-Compare (FIXType,FIXType)",
	"%SYSBLDUSER%",
	5, "Compare (FIXType,FIXType)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "Compare (FIXType,FIXType)",
	"%SYSBLDUSER%", 0,
	"grant execute on function Compare (FIXType,FIXType) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "Compare (FIXType,FIXType)",
	"%SYSBLDUSER%",
	5, "Compare (FIXType,FIXType)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "Equal (FIXType,FIXType)",
	"%SYSBLDUSER%", 0,
	"create function Equal (FIXType,FIXType)
returns boolean
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/FIXType.bld(FIXTypeEqual)"" language c;

",
	"f",
	"drop function Equal (FIXType,FIXType);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	5, "Equal (FIXType,FIXType)",
	"%SYSBLDUSER%",
	7, "FIXType",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-Equal (FIXType,FIXType)",
	"%SYSBLDUSER%", 0,
	"alter function Equal (FIXType,FIXType)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/FIXType.bld(FIXTypeEqual)"");

",
	"f",
	"alter function Equal (FIXType,FIXType)
	with (Modify External Name = ""FIXTypeEqual"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-Equal (FIXType,FIXType)",
	"%SYSBLDUSER%",
	5, "Equal (FIXType,FIXType)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 85, "Alter-Variant-Equal (FIXType,FIXType)",
	"%SYSBLDUSER%", 0,
	"alter function Equal (FIXType,FIXType)
	with (add not variant);

",
	"f",
	"alter function Equal (FIXType,FIXType)
	with (drop not variant);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	85, "Alter-Variant-Equal (FIXType,FIXType)",
	"%SYSBLDUSER%",
	5, "Equal (FIXType,FIXType)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "Equal (FIXType,FIXType)",
	"%SYSBLDUSER%", 0,
	"grant execute on function Equal (FIXType,FIXType) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "Equal (FIXType,FIXType)",
	"%SYSBLDUSER%",
	5, "Equal (FIXType,FIXType)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "NotEqual (FIXType,FIXType)",
	"%SYSBLDUSER%", 0,
	"create function NotEqual (FIXType,FIXType)
returns boolean
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/FIXType.bld(FIXTypeNotEqual)"" language c;

",
	"f",
	"drop function NotEqual (FIXType,FIXType);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	5, "NotEqual (FIXType,FIXType)",
	"%SYSBLDUSER%",
	7, "FIXType",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-NotEqual (FIXType,FIXType)",
	"%SYSBLDUSER%", 0,
	"alter function NotEqual (FIXType,FIXType)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/FIXType.bld(FIXTypeNotEqual)"");

",
	"f",
	"alter function NotEqual (FIXType,FIXType)
	with (Modify External Name = ""FIXTypeNotEqual"");

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-NotEqual (FIXType,FIXType)",
	"%SYSBLDUSER%",
	5, "NotEqual (FIXType,FIXType)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 85, "Alter-Variant-NotEqual (FIXType,FIXType)",
	"%SYSBLDUSER%", 0,
	"alter function NotEqual (FIXType,FIXType)
	with (add not variant);

",
	"f",
	"alter function NotEqual (FIXType,FIXType)
	with (drop not variant);

",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	85, "Alter-Variant-NotEqual (FIXType,FIXType)",
	"%SYSBLDUSER%",
	5, "NotEqual (FIXType,FIXType)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "NotEqual (FIXType,FIXType)",
	"%SYSBLDUSER%", 0,
	"grant execute on function NotEqual (FIXType,FIXType) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
(
	bld_id,
	obj_kind,
	obj_signature,
	obj_owner,
	need_obj_kind,
	need_obj_signature,
	need_obj_owner)
	values
(
	"%SYSBLDNAME%",
	69, "NotEqual (FIXType,FIXType)",
	"%SYSBLDUSER%",
	5, "NotEqual (FIXType,FIXType)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 0, "sysbldregistered",
	"%SYSBLDUSER%", 0,
	"insert into sysbldregistered
	(bld_id)
values
(
	""%SYSBLDNAME%""
);

",
	"f",
	"delete from sysbldregistered
	where bld_id = ""%SYSBLDNAME%"";

",
	"f"
);

