-- Generated by BladeSmith 4.00.TC1B2DO NOT MODIFY. --

execute procedure ifx_allow_newline('t');

begin work;

create function IDN_Debug (int)
returns int
external name "$INFORMIXDIR/extend/idn_sampler.1.5/idn_sampler.bld(IDN_Debug)" language c;

alter function IDN_Debug (int)
	with (Modify External Name = "$INFORMIXDIR/extend/idn_sampler.1.5/idn_sampler.bld(IDN_Debug)");

alter function IDN_Debug (int)
	with (add not variant);

grant execute on function IDN_Debug (int) to public;

create function IDN_FuncExec (integer,integer)
returns boolean
external name "$INFORMIXDIR/extend/idn_sampler.1.5/idn_sampler.bld(IDN_FuncExec)" language c;

alter function IDN_FuncExec (integer,integer)
	with (Modify External Name = "$INFORMIXDIR/extend/idn_sampler.1.5/idn_sampler.bld(IDN_FuncExec)");

alter function IDN_FuncExec (integer,integer)
	with (add not variant);

grant execute on function IDN_FuncExec (integer,integer) to public;

create function IDN_FuncCache (integer,integer)
returns boolean
external name "$INFORMIXDIR/extend/idn_sampler.1.5/idn_sampler.bld(IDN_FuncCache)" language c;

alter function IDN_FuncCache (integer,integer)
	with (Modify External Name = "$INFORMIXDIR/extend/idn_sampler.1.5/idn_sampler.bld(IDN_FuncCache)");

alter function IDN_FuncCache (integer,integer)
	with (add not variant);

grant execute on function IDN_FuncCache (integer,integer) to public;

create procedure IDN_LogMsg (lvarchar,lvarchar)
external name "$INFORMIXDIR/extend/idn_sampler.1.5/idn_sampler.bld(IDN_LogMsg)" language c;

alter procedure IDN_LogMsg (lvarchar,lvarchar)
	with (Modify External Name = "$INFORMIXDIR/extend/idn_sampler.1.5/idn_sampler.bld(IDN_LogMsg)");

grant execute on procedure IDN_LogMsg (lvarchar,lvarchar) to public;

create function IDN_Now ()
returns datetime year to second
external name "$INFORMIXDIR/extend/idn_sampler.1.5/idn_sampler.bld(IDN_Now)" language c;

alter function IDN_Now ()
	with (Modify External Name = "$INFORMIXDIR/extend/idn_sampler.1.5/idn_sampler.bld(IDN_Now)");

grant execute on function IDN_Now () to public;

create function IDN_EOT_Reg ()
returns lvarchar
external name "$INFORMIXDIR/extend/idn_sampler.1.5/idn_sampler.bld(IDN_EOT_Reg)" language c;

alter function IDN_EOT_Reg ()
	with (Modify External Name = "$INFORMIXDIR/extend/idn_sampler.1.5/idn_sampler.bld(IDN_EOT_Reg)");

grant execute on function IDN_EOT_Reg () to public;

create function IDN_SetNow (lvarchar)
returns datetime year to second
external name "$INFORMIXDIR/extend/idn_sampler.1.5/idn_sampler.bld(IDN_SetNow)" language c;

alter function IDN_SetNow (lvarchar)
	with (Modify External Name = "$INFORMIXDIR/extend/idn_sampler.1.5/idn_sampler.bld(IDN_SetNow)");

grant execute on function IDN_SetNow (lvarchar) to public;

create function IDN_SessionId ()
returns int
external name "$INFORMIXDIR/extend/idn_sampler.1.5/idn_sampler.bld(IDN_SessionId)" language c;

alter function IDN_SessionId ()
	with (Modify External Name = "$INFORMIXDIR/extend/idn_sampler.1.5/idn_sampler.bld(IDN_SessionId)");

grant execute on function IDN_SessionId () to public;

create procedure IDN_EasyTrace (lvarchar,int)
external name "$INFORMIXDIR/extend/idn_sampler.1.5/idn_sampler.bld(IDN_EasyTrace)" language c;

alter procedure IDN_EasyTrace (lvarchar,int)
	with (Modify External Name = "$INFORMIXDIR/extend/idn_sampler.1.5/idn_sampler.bld(IDN_EasyTrace)");

grant execute on procedure IDN_EasyTrace (lvarchar,int) to public;

create function IDN_Debug ()
returns int
external name "$INFORMIXDIR/extend/idn_sampler.1.5/idn_sampler.bld(IDN_Debug_GetLevel)" language c;

alter function IDN_Debug ()
	with (Modify External Name = "$INFORMIXDIR/extend/idn_sampler.1.5/idn_sampler.bld(IDN_Debug_GetLevel)");

grant execute on function IDN_Debug () to public;

create function IDN_Debug (lvarchar,int)
returns int
external name "$INFORMIXDIR/extend/idn_sampler.1.5/idn_sampler.bld(IDN_SetAnyLevel)" language c;

alter function IDN_Debug (lvarchar,int)
	with (Modify External Name = "$INFORMIXDIR/extend/idn_sampler.1.5/idn_sampler.bld(IDN_SetAnyLevel)");

grant execute on function IDN_Debug (lvarchar,int) to public;

create function IDN_Debug (lvarchar)
returns int
external name "$INFORMIXDIR/extend/idn_sampler.1.5/idn_sampler.bld(IDN_GetAnyLevel)" language c;

alter function IDN_Debug (lvarchar)
	with (Modify External Name = "$INFORMIXDIR/extend/idn_sampler.1.5/idn_sampler.bld(IDN_GetAnyLevel)");

grant execute on function IDN_Debug (lvarchar) to public;

commit work;

