-- Generated by BladeSmith 3.70.TC1  DO NOT MODIFY. --

execute procedure ifx_allow_newline('t');

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 0, "TraceClass",
	"%SYSBLDUSER%", 0,
	"insert into systraceclasses(name) values ('BWA');
create procedure TraceSet_BWA (lvarchar, int)
with (variant)
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(TraceSet_BWA)""
language c;

insert into systraceclasses(name) values ('BWAstats');
",
	"f",
	"delete from systraceclasses where name='BWA';
delete from systraceclasses where name='BWAstats';
drop procedure TraceSet_BWA (lvarchar, int);
",
	"f"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 7, "BWA",
	"%SYSBLDUSER%", 0,
	"create opaque type BWA(
	internallength = 136,
	alignment = 1
);

",
	"f",
	"drop type BWA restrict;

",
	"f"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 71, "BWA",
	"%SYSBLDUSER%", 0,
	"grant usage on type BWA to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	71, "BWA",
	"%SYSBLDUSER%",
	7, "BWA",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "BWAIn (lvarchar)",
	"%SYSBLDUSER%", 0,
	"create function BWAIn (lvarchar)
returns BWA
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWAInput)"" language c;

",
	"f",
	"drop function BWAIn (lvarchar);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	5, "BWAIn (lvarchar)",
	"%SYSBLDUSER%",
	7, "BWA",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-BWAIn (lvarchar)",
	"%SYSBLDUSER%", 0,
	"alter function BWAIn (lvarchar)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWAInput)"");

",
	"f",
	"alter function BWAIn (lvarchar)
	with (Modify External Name = ""BWAInput"");

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-BWAIn (lvarchar)",
	"%SYSBLDUSER%",
	5, "BWAIn (lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 37, "Alter-Parallelize-BWAIn (lvarchar)",
	"%SYSBLDUSER%", 0,
	"alter function BWAIn (lvarchar)
	with (add parallelizable);

",
	"f",
	"alter function BWAIn (lvarchar)
	with (drop parallelizable);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	37, "Alter-Parallelize-BWAIn (lvarchar)",
	"%SYSBLDUSER%",
	5, "BWAIn (lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 85, "Alter-Variant-BWAIn (lvarchar)",
	"%SYSBLDUSER%", 0,
	"alter function BWAIn (lvarchar)
	with (add not variant);

",
	"f",
	"alter function BWAIn (lvarchar)
	with (drop not variant);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	85, "Alter-Variant-BWAIn (lvarchar)",
	"%SYSBLDUSER%",
	5, "BWAIn (lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "BWAIn (lvarchar)",
	"%SYSBLDUSER%", 0,
	"grant execute on function BWAIn (lvarchar) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	69, "BWAIn (lvarchar)",
	"%SYSBLDUSER%",
	5, "BWAIn (lvarchar)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 3, "lvarchar->BWA",
	"%SYSBLDUSER%", 0,
	"create implicit cast 
(
	lvarchar as BWA
	with  BWAIn
);

",
	"f",
	"drop cast (lvarchar as BWA);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	3, "lvarchar->BWA",
	"%SYSBLDUSER%",
	7, "BWA",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "BWAOut (BWA)",
	"%SYSBLDUSER%", 0,
	"create function BWAOut (BWA)
returns lvarchar
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWAOutput)"" language c;

",
	"f",
	"drop function BWAOut (BWA);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	5, "BWAOut (BWA)",
	"%SYSBLDUSER%",
	7, "BWA",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-BWAOut (BWA)",
	"%SYSBLDUSER%", 0,
	"alter function BWAOut (BWA)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWAOutput)"");

",
	"f",
	"alter function BWAOut (BWA)
	with (Modify External Name = ""BWAOutput"");

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-BWAOut (BWA)",
	"%SYSBLDUSER%",
	5, "BWAOut (BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "BWAOut (BWA)",
	"%SYSBLDUSER%", 0,
	"grant execute on function BWAOut (BWA) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	69, "BWAOut (BWA)",
	"%SYSBLDUSER%",
	5, "BWAOut (BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 3, "BWA->lvarchar",
	"%SYSBLDUSER%", 0,
	"create cast 
(
	BWA as lvarchar
	with  BWAOut
);

",
	"f",
	"drop cast (BWA as lvarchar);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	3, "BWA->lvarchar",
	"%SYSBLDUSER%",
	7, "BWA",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "BWASend (BWA)",
	"%SYSBLDUSER%", 0,
	"create function BWASend (BWA)
returns sendrecv
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWASend)"" language c;

",
	"f",
	"drop function BWASend (BWA);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	5, "BWASend (BWA)",
	"%SYSBLDUSER%",
	7, "BWA",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-BWASend (BWA)",
	"%SYSBLDUSER%", 0,
	"alter function BWASend (BWA)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWASend)"");

",
	"f",
	"alter function BWASend (BWA)
	with (Modify External Name = ""BWASend"");

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-BWASend (BWA)",
	"%SYSBLDUSER%",
	5, "BWASend (BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "BWASend (BWA)",
	"%SYSBLDUSER%", 0,
	"grant execute on function BWASend (BWA) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	69, "BWASend (BWA)",
	"%SYSBLDUSER%",
	5, "BWASend (BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 3, "BWA->sendrecv",
	"%SYSBLDUSER%", 0,
	"create cast 
(
	BWA as sendrecv
	with  BWASend
);

",
	"f",
	"drop cast (BWA as sendrecv);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	3, "BWA->sendrecv",
	"%SYSBLDUSER%",
	7, "BWA",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "BWARecv (sendrecv)",
	"%SYSBLDUSER%", 0,
	"create function BWARecv (sendrecv)
returns BWA
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWAReceive)"" language c;

",
	"f",
	"drop function BWARecv (sendrecv);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	5, "BWARecv (sendrecv)",
	"%SYSBLDUSER%",
	7, "BWA",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-BWARecv (sendrecv)",
	"%SYSBLDUSER%", 0,
	"alter function BWARecv (sendrecv)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWAReceive)"");

",
	"f",
	"alter function BWARecv (sendrecv)
	with (Modify External Name = ""BWAReceive"");

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-BWARecv (sendrecv)",
	"%SYSBLDUSER%",
	5, "BWARecv (sendrecv)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "BWARecv (sendrecv)",
	"%SYSBLDUSER%", 0,
	"grant execute on function BWARecv (sendrecv) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	69, "BWARecv (sendrecv)",
	"%SYSBLDUSER%",
	5, "BWARecv (sendrecv)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 3, "sendrecv->BWA",
	"%SYSBLDUSER%", 0,
	"create implicit cast 
(
	sendrecv as BWA
	with  BWARecv
);

",
	"f",
	"drop cast (sendrecv as BWA);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	3, "sendrecv->BWA",
	"%SYSBLDUSER%",
	7, "BWA",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "BWAImpT (impexp)",
	"%SYSBLDUSER%", 0,
	"create function BWAImpT (impexp)
returns BWA
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWAImportText)"" language c;

",
	"f",
	"drop function BWAImpT (impexp);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	5, "BWAImpT (impexp)",
	"%SYSBLDUSER%",
	7, "BWA",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-BWAImpT (impexp)",
	"%SYSBLDUSER%", 0,
	"alter function BWAImpT (impexp)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWAImportText)"");

",
	"f",
	"alter function BWAImpT (impexp)
	with (Modify External Name = ""BWAImportText"");

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-BWAImpT (impexp)",
	"%SYSBLDUSER%",
	5, "BWAImpT (impexp)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "BWAImpT (impexp)",
	"%SYSBLDUSER%", 0,
	"grant execute on function BWAImpT (impexp) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	69, "BWAImpT (impexp)",
	"%SYSBLDUSER%",
	5, "BWAImpT (impexp)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 3, "impexp->BWA",
	"%SYSBLDUSER%", 0,
	"create implicit cast 
(
	impexp as BWA
	with  BWAImpT
);

",
	"f",
	"drop cast (impexp as BWA);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	3, "impexp->BWA",
	"%SYSBLDUSER%",
	7, "BWA",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "BWAExpT (BWA)",
	"%SYSBLDUSER%", 0,
	"create function BWAExpT (BWA)
returns impexp
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWAExportText)"" language c;

",
	"f",
	"drop function BWAExpT (BWA);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	5, "BWAExpT (BWA)",
	"%SYSBLDUSER%",
	7, "BWA",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-BWAExpT (BWA)",
	"%SYSBLDUSER%", 0,
	"alter function BWAExpT (BWA)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWAExportText)"");

",
	"f",
	"alter function BWAExpT (BWA)
	with (Modify External Name = ""BWAExportText"");

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-BWAExpT (BWA)",
	"%SYSBLDUSER%",
	5, "BWAExpT (BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "BWAExpT (BWA)",
	"%SYSBLDUSER%", 0,
	"grant execute on function BWAExpT (BWA) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	69, "BWAExpT (BWA)",
	"%SYSBLDUSER%",
	5, "BWAExpT (BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 3, "BWA->impexp",
	"%SYSBLDUSER%", 0,
	"create cast 
(
	BWA as impexp
	with  BWAExpT
);

",
	"f",
	"drop cast (BWA as impexp);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	3, "BWA->impexp",
	"%SYSBLDUSER%",
	7, "BWA",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "BWAImpB (impexpbin)",
	"%SYSBLDUSER%", 0,
	"create function BWAImpB (impexpbin)
returns BWA
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWAImportBinary)"" language c;

",
	"f",
	"drop function BWAImpB (impexpbin);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	5, "BWAImpB (impexpbin)",
	"%SYSBLDUSER%",
	7, "BWA",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-BWAImpB (impexpbin)",
	"%SYSBLDUSER%", 0,
	"alter function BWAImpB (impexpbin)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWAImportBinary)"");

",
	"f",
	"alter function BWAImpB (impexpbin)
	with (Modify External Name = ""BWAImportBinary"");

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-BWAImpB (impexpbin)",
	"%SYSBLDUSER%",
	5, "BWAImpB (impexpbin)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "BWAImpB (impexpbin)",
	"%SYSBLDUSER%", 0,
	"grant execute on function BWAImpB (impexpbin) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	69, "BWAImpB (impexpbin)",
	"%SYSBLDUSER%",
	5, "BWAImpB (impexpbin)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 3, "impexpbin->BWA",
	"%SYSBLDUSER%", 0,
	"create implicit cast 
(
	impexpbin as BWA
	with  BWAImpB
);

",
	"f",
	"drop cast (impexpbin as BWA);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	3, "impexpbin->BWA",
	"%SYSBLDUSER%",
	7, "BWA",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "BWAExpB (BWA)",
	"%SYSBLDUSER%", 0,
	"create function BWAExpB (BWA)
returns impexpbin
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWAExportBinary)"" language c;

",
	"f",
	"drop function BWAExpB (BWA);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	5, "BWAExpB (BWA)",
	"%SYSBLDUSER%",
	7, "BWA",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-BWAExpB (BWA)",
	"%SYSBLDUSER%", 0,
	"alter function BWAExpB (BWA)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWAExportBinary)"");

",
	"f",
	"alter function BWAExpB (BWA)
	with (Modify External Name = ""BWAExportBinary"");

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-BWAExpB (BWA)",
	"%SYSBLDUSER%",
	5, "BWAExpB (BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "BWAExpB (BWA)",
	"%SYSBLDUSER%", 0,
	"grant execute on function BWAExpB (BWA) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	69, "BWAExpB (BWA)",
	"%SYSBLDUSER%",
	5, "BWAExpB (BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 3, "BWA->impexpbin",
	"%SYSBLDUSER%", 0,
	"create cast 
(
	BWA as impexpbin
	with  BWAExpB
);

",
	"f",
	"drop cast (BWA as impexpbin);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	3, "BWA->impexpbin",
	"%SYSBLDUSER%",
	7, "BWA",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "Compare (BWA,BWA)",
	"%SYSBLDUSER%", 0,
	"create function Compare (BWA,BWA)
returns integer
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWACompare)"" language c;

",
	"f",
	"drop function Compare (BWA,BWA);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	5, "Compare (BWA,BWA)",
	"%SYSBLDUSER%",
	7, "BWA",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-Compare (BWA,BWA)",
	"%SYSBLDUSER%", 0,
	"alter function Compare (BWA,BWA)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWACompare)"");

",
	"f",
	"alter function Compare (BWA,BWA)
	with (Modify External Name = ""BWACompare"");

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-Compare (BWA,BWA)",
	"%SYSBLDUSER%",
	5, "Compare (BWA,BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 37, "Alter-Parallelize-Compare (BWA,BWA)",
	"%SYSBLDUSER%", 0,
	"alter function Compare (BWA,BWA)
	with (add parallelizable);

",
	"f",
	"alter function Compare (BWA,BWA)
	with (drop parallelizable);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	37, "Alter-Parallelize-Compare (BWA,BWA)",
	"%SYSBLDUSER%",
	5, "Compare (BWA,BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 85, "Alter-Variant-Compare (BWA,BWA)",
	"%SYSBLDUSER%", 0,
	"alter function Compare (BWA,BWA)
	with (add not variant);

",
	"f",
	"alter function Compare (BWA,BWA)
	with (drop not variant);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	85, "Alter-Variant-Compare (BWA,BWA)",
	"%SYSBLDUSER%",
	5, "Compare (BWA,BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "Compare (BWA,BWA)",
	"%SYSBLDUSER%", 0,
	"grant execute on function Compare (BWA,BWA) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	69, "Compare (BWA,BWA)",
	"%SYSBLDUSER%",
	5, "Compare (BWA,BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "Equal (BWA,BWA)",
	"%SYSBLDUSER%", 0,
	"create function Equal (BWA,BWA)
returns boolean
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWAEqual)"" language c;

",
	"f",
	"drop function Equal (BWA,BWA);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	5, "Equal (BWA,BWA)",
	"%SYSBLDUSER%",
	7, "BWA",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-Equal (BWA,BWA)",
	"%SYSBLDUSER%", 0,
	"alter function Equal (BWA,BWA)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWAEqual)"");

",
	"f",
	"alter function Equal (BWA,BWA)
	with (Modify External Name = ""BWAEqual"");

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-Equal (BWA,BWA)",
	"%SYSBLDUSER%",
	5, "Equal (BWA,BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 37, "Alter-Parallelize-Equal (BWA,BWA)",
	"%SYSBLDUSER%", 0,
	"alter function Equal (BWA,BWA)
	with (add parallelizable);

",
	"f",
	"alter function Equal (BWA,BWA)
	with (drop parallelizable);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	37, "Alter-Parallelize-Equal (BWA,BWA)",
	"%SYSBLDUSER%",
	5, "Equal (BWA,BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 85, "Alter-Variant-Equal (BWA,BWA)",
	"%SYSBLDUSER%", 0,
	"alter function Equal (BWA,BWA)
	with (add not variant);

",
	"f",
	"alter function Equal (BWA,BWA)
	with (drop not variant);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	85, "Alter-Variant-Equal (BWA,BWA)",
	"%SYSBLDUSER%",
	5, "Equal (BWA,BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "Equal (BWA,BWA)",
	"%SYSBLDUSER%", 0,
	"grant execute on function Equal (BWA,BWA) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	69, "Equal (BWA,BWA)",
	"%SYSBLDUSER%",
	5, "Equal (BWA,BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "NotEqual (BWA,BWA)",
	"%SYSBLDUSER%", 0,
	"create function NotEqual (BWA,BWA)
returns boolean
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWANotEqual)"" language c;

",
	"f",
	"drop function NotEqual (BWA,BWA);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	5, "NotEqual (BWA,BWA)",
	"%SYSBLDUSER%",
	7, "BWA",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-NotEqual (BWA,BWA)",
	"%SYSBLDUSER%", 0,
	"alter function NotEqual (BWA,BWA)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWANotEqual)"");

",
	"f",
	"alter function NotEqual (BWA,BWA)
	with (Modify External Name = ""BWANotEqual"");

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-NotEqual (BWA,BWA)",
	"%SYSBLDUSER%",
	5, "NotEqual (BWA,BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 37, "Alter-Parallelize-NotEqual (BWA,BWA)",
	"%SYSBLDUSER%", 0,
	"alter function NotEqual (BWA,BWA)
	with (add parallelizable);

",
	"f",
	"alter function NotEqual (BWA,BWA)
	with (drop parallelizable);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	37, "Alter-Parallelize-NotEqual (BWA,BWA)",
	"%SYSBLDUSER%",
	5, "NotEqual (BWA,BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 85, "Alter-Variant-NotEqual (BWA,BWA)",
	"%SYSBLDUSER%", 0,
	"alter function NotEqual (BWA,BWA)
	with (add not variant);

",
	"f",
	"alter function NotEqual (BWA,BWA)
	with (drop not variant);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	85, "Alter-Variant-NotEqual (BWA,BWA)",
	"%SYSBLDUSER%",
	5, "NotEqual (BWA,BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "NotEqual (BWA,BWA)",
	"%SYSBLDUSER%", 0,
	"grant execute on function NotEqual (BWA,BWA) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	69, "NotEqual (BWA,BWA)",
	"%SYSBLDUSER%",
	5, "NotEqual (BWA,BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "LessThan (BWA,BWA)",
	"%SYSBLDUSER%", 0,
	"create function LessThan (BWA,BWA)
returns boolean
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWALessThan)"" language c;

",
	"f",
	"drop function LessThan (BWA,BWA);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	5, "LessThan (BWA,BWA)",
	"%SYSBLDUSER%",
	7, "BWA",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-LessThan (BWA,BWA)",
	"%SYSBLDUSER%", 0,
	"alter function LessThan (BWA,BWA)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWALessThan)"");

",
	"f",
	"alter function LessThan (BWA,BWA)
	with (Modify External Name = ""BWALessThan"");

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-LessThan (BWA,BWA)",
	"%SYSBLDUSER%",
	5, "LessThan (BWA,BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 37, "Alter-Parallelize-LessThan (BWA,BWA)",
	"%SYSBLDUSER%", 0,
	"alter function LessThan (BWA,BWA)
	with (add parallelizable);

",
	"f",
	"alter function LessThan (BWA,BWA)
	with (drop parallelizable);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	37, "Alter-Parallelize-LessThan (BWA,BWA)",
	"%SYSBLDUSER%",
	5, "LessThan (BWA,BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 85, "Alter-Variant-LessThan (BWA,BWA)",
	"%SYSBLDUSER%", 0,
	"alter function LessThan (BWA,BWA)
	with (add not variant);

",
	"f",
	"alter function LessThan (BWA,BWA)
	with (drop not variant);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	85, "Alter-Variant-LessThan (BWA,BWA)",
	"%SYSBLDUSER%",
	5, "LessThan (BWA,BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "LessThan (BWA,BWA)",
	"%SYSBLDUSER%", 0,
	"grant execute on function LessThan (BWA,BWA) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	69, "LessThan (BWA,BWA)",
	"%SYSBLDUSER%",
	5, "LessThan (BWA,BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "GreaterThan (BWA,BWA)",
	"%SYSBLDUSER%", 0,
	"create function GreaterThan (BWA,BWA)
returns boolean
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWAGreaterThan)"" language c;

",
	"f",
	"drop function GreaterThan (BWA,BWA);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	5, "GreaterThan (BWA,BWA)",
	"%SYSBLDUSER%",
	7, "BWA",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-GreaterThan (BWA,BWA)",
	"%SYSBLDUSER%", 0,
	"alter function GreaterThan (BWA,BWA)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWAGreaterThan)"");

",
	"f",
	"alter function GreaterThan (BWA,BWA)
	with (Modify External Name = ""BWAGreaterThan"");

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-GreaterThan (BWA,BWA)",
	"%SYSBLDUSER%",
	5, "GreaterThan (BWA,BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 37, "Alter-Parallelize-GreaterThan (BWA,BWA)",
	"%SYSBLDUSER%", 0,
	"alter function GreaterThan (BWA,BWA)
	with (add parallelizable);

",
	"f",
	"alter function GreaterThan (BWA,BWA)
	with (drop parallelizable);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	37, "Alter-Parallelize-GreaterThan (BWA,BWA)",
	"%SYSBLDUSER%",
	5, "GreaterThan (BWA,BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 85, "Alter-Variant-GreaterThan (BWA,BWA)",
	"%SYSBLDUSER%", 0,
	"alter function GreaterThan (BWA,BWA)
	with (add not variant);

",
	"f",
	"alter function GreaterThan (BWA,BWA)
	with (drop not variant);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	85, "Alter-Variant-GreaterThan (BWA,BWA)",
	"%SYSBLDUSER%",
	5, "GreaterThan (BWA,BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "GreaterThan (BWA,BWA)",
	"%SYSBLDUSER%", 0,
	"grant execute on function GreaterThan (BWA,BWA) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	69, "GreaterThan (BWA,BWA)",
	"%SYSBLDUSER%",
	5, "GreaterThan (BWA,BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "LessThanOrEqual (BWA,BWA)",
	"%SYSBLDUSER%", 0,
	"create function LessThanOrEqual (BWA,BWA)
returns boolean
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWALessThanOrEqual)"" language c;

",
	"f",
	"drop function LessThanOrEqual (BWA,BWA);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	5, "LessThanOrEqual (BWA,BWA)",
	"%SYSBLDUSER%",
	7, "BWA",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-LessThanOrEqual (BWA,BWA)",
	"%SYSBLDUSER%", 0,
	"alter function LessThanOrEqual (BWA,BWA)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWALessThanOrEqual)"");

",
	"f",
	"alter function LessThanOrEqual (BWA,BWA)
	with (Modify External Name = ""BWALessThanOrEqual"");

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-LessThanOrEqual (BWA,BWA)",
	"%SYSBLDUSER%",
	5, "LessThanOrEqual (BWA,BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 37, "Alter-Parallelize-LessThanOrEqual (BWA,BWA)",
	"%SYSBLDUSER%", 0,
	"alter function LessThanOrEqual (BWA,BWA)
	with (add parallelizable);

",
	"f",
	"alter function LessThanOrEqual (BWA,BWA)
	with (drop parallelizable);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	37, "Alter-Parallelize-LessThanOrEqual (BWA,BWA)",
	"%SYSBLDUSER%",
	5, "LessThanOrEqual (BWA,BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 85, "Alter-Variant-LessThanOrEqual (BWA,BWA)",
	"%SYSBLDUSER%", 0,
	"alter function LessThanOrEqual (BWA,BWA)
	with (add not variant);

",
	"f",
	"alter function LessThanOrEqual (BWA,BWA)
	with (drop not variant);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	85, "Alter-Variant-LessThanOrEqual (BWA,BWA)",
	"%SYSBLDUSER%",
	5, "LessThanOrEqual (BWA,BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "LessThanOrEqual (BWA,BWA)",
	"%SYSBLDUSER%", 0,
	"grant execute on function LessThanOrEqual (BWA,BWA) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	69, "LessThanOrEqual (BWA,BWA)",
	"%SYSBLDUSER%",
	5, "LessThanOrEqual (BWA,BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "GreaterThanOrEqual (BWA,BWA)",
	"%SYSBLDUSER%", 0,
	"create function GreaterThanOrEqual (BWA,BWA)
returns boolean
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWAGreaterThanOrEqual)"" language c;

",
	"f",
	"drop function GreaterThanOrEqual (BWA,BWA);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	5, "GreaterThanOrEqual (BWA,BWA)",
	"%SYSBLDUSER%",
	7, "BWA",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-GreaterThanOrEqual (BWA,BWA)",
	"%SYSBLDUSER%", 0,
	"alter function GreaterThanOrEqual (BWA,BWA)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWAGreaterThanOrEqual)"");

",
	"f",
	"alter function GreaterThanOrEqual (BWA,BWA)
	with (Modify External Name = ""BWAGreaterThanOrEqual"");

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-GreaterThanOrEqual (BWA,BWA)",
	"%SYSBLDUSER%",
	5, "GreaterThanOrEqual (BWA,BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 37, "Alter-Parallelize-GreaterThanOrEqual (BWA,BWA)",
	"%SYSBLDUSER%", 0,
	"alter function GreaterThanOrEqual (BWA,BWA)
	with (add parallelizable);

",
	"f",
	"alter function GreaterThanOrEqual (BWA,BWA)
	with (drop parallelizable);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	37, "Alter-Parallelize-GreaterThanOrEqual (BWA,BWA)",
	"%SYSBLDUSER%",
	5, "GreaterThanOrEqual (BWA,BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 85, "Alter-Variant-GreaterThanOrEqual (BWA,BWA)",
	"%SYSBLDUSER%", 0,
	"alter function GreaterThanOrEqual (BWA,BWA)
	with (add not variant);

",
	"f",
	"alter function GreaterThanOrEqual (BWA,BWA)
	with (drop not variant);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	85, "Alter-Variant-GreaterThanOrEqual (BWA,BWA)",
	"%SYSBLDUSER%",
	5, "GreaterThanOrEqual (BWA,BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "GreaterThanOrEqual (BWA,BWA)",
	"%SYSBLDUSER%", 0,
	"grant execute on function GreaterThanOrEqual (BWA,BWA) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	69, "GreaterThanOrEqual (BWA,BWA)",
	"%SYSBLDUSER%",
	5, "GreaterThanOrEqual (BWA,BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "Contains (BWA,BWA)",
	"%SYSBLDUSER%", 0,
	"create function Contains (BWA,BWA)
returns boolean
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWAContains)"" language c;

",
	"f",
	"drop function Contains (BWA,BWA);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	5, "Contains (BWA,BWA)",
	"%SYSBLDUSER%",
	7, "BWA",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-Contains (BWA,BWA)",
	"%SYSBLDUSER%", 0,
	"alter function Contains (BWA,BWA)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWAContains)"");

",
	"f",
	"alter function Contains (BWA,BWA)
	with (Modify External Name = ""BWAContains"");

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-Contains (BWA,BWA)",
	"%SYSBLDUSER%",
	5, "Contains (BWA,BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 37, "Alter-Parallelize-Contains (BWA,BWA)",
	"%SYSBLDUSER%", 0,
	"alter function Contains (BWA,BWA)
	with (add parallelizable);

",
	"f",
	"alter function Contains (BWA,BWA)
	with (drop parallelizable);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	37, "Alter-Parallelize-Contains (BWA,BWA)",
	"%SYSBLDUSER%",
	5, "Contains (BWA,BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 85, "Alter-Variant-Contains (BWA,BWA)",
	"%SYSBLDUSER%", 0,
	"alter function Contains (BWA,BWA)
	with (add not variant);

",
	"f",
	"alter function Contains (BWA,BWA)
	with (drop not variant);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	85, "Alter-Variant-Contains (BWA,BWA)",
	"%SYSBLDUSER%",
	5, "Contains (BWA,BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "Contains (BWA,BWA)",
	"%SYSBLDUSER%", 0,
	"grant execute on function Contains (BWA,BWA) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	69, "Contains (BWA,BWA)",
	"%SYSBLDUSER%",
	5, "Contains (BWA,BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "GetCategory (BWA)",
	"%SYSBLDUSER%", 0,
	"create function GetCategory (BWA)
returns varchar (32)
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWACategory)"" language c;

",
	"f",
	"drop function GetCategory (BWA);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	5, "GetCategory (BWA)",
	"%SYSBLDUSER%",
	7, "BWA",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-GetCategory (BWA)",
	"%SYSBLDUSER%", 0,
	"alter function GetCategory (BWA)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWACategory)"");

",
	"f",
	"alter function GetCategory (BWA)
	with (Modify External Name = ""BWACategory"");

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-GetCategory (BWA)",
	"%SYSBLDUSER%",
	5, "GetCategory (BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 37, "Alter-Parallelize-GetCategory (BWA)",
	"%SYSBLDUSER%", 0,
	"alter function GetCategory (BWA)
	with (add parallelizable);

",
	"f",
	"alter function GetCategory (BWA)
	with (drop parallelizable);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	37, "Alter-Parallelize-GetCategory (BWA)",
	"%SYSBLDUSER%",
	5, "GetCategory (BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 85, "Alter-Variant-GetCategory (BWA)",
	"%SYSBLDUSER%", 0,
	"alter function GetCategory (BWA)
	with (add not variant);

",
	"f",
	"alter function GetCategory (BWA)
	with (drop not variant);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	85, "Alter-Variant-GetCategory (BWA)",
	"%SYSBLDUSER%",
	5, "GetCategory (BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "GetCategory (BWA)",
	"%SYSBLDUSER%", 0,
	"grant execute on function GetCategory (BWA) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	69, "GetCategory (BWA)",
	"%SYSBLDUSER%",
	5, "GetCategory (BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "GetFamily (BWA)",
	"%SYSBLDUSER%", 0,
	"create function GetFamily (BWA)
returns varchar (32)
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWAFamily)"" language c;

",
	"f",
	"drop function GetFamily (BWA);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	5, "GetFamily (BWA)",
	"%SYSBLDUSER%",
	7, "BWA",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-GetFamily (BWA)",
	"%SYSBLDUSER%", 0,
	"alter function GetFamily (BWA)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWAFamily)"");

",
	"f",
	"alter function GetFamily (BWA)
	with (Modify External Name = ""BWAFamily"");

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-GetFamily (BWA)",
	"%SYSBLDUSER%",
	5, "GetFamily (BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 37, "Alter-Parallelize-GetFamily (BWA)",
	"%SYSBLDUSER%", 0,
	"alter function GetFamily (BWA)
	with (add parallelizable);

",
	"f",
	"alter function GetFamily (BWA)
	with (drop parallelizable);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	37, "Alter-Parallelize-GetFamily (BWA)",
	"%SYSBLDUSER%",
	5, "GetFamily (BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 85, "Alter-Variant-GetFamily (BWA)",
	"%SYSBLDUSER%", 0,
	"alter function GetFamily (BWA)
	with (add not variant);

",
	"f",
	"alter function GetFamily (BWA)
	with (drop not variant);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	85, "Alter-Variant-GetFamily (BWA)",
	"%SYSBLDUSER%",
	5, "GetFamily (BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "GetFamily (BWA)",
	"%SYSBLDUSER%", 0,
	"grant execute on function GetFamily (BWA) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	69, "GetFamily (BWA)",
	"%SYSBLDUSER%",
	5, "GetFamily (BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "GetGroup (BWA)",
	"%SYSBLDUSER%", 0,
	"create function GetGroup (BWA)
returns varchar (32)
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWAGroup)"" language c;

",
	"f",
	"drop function GetGroup (BWA);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	5, "GetGroup (BWA)",
	"%SYSBLDUSER%",
	7, "BWA",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-GetGroup (BWA)",
	"%SYSBLDUSER%", 0,
	"alter function GetGroup (BWA)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWAGroup)"");

",
	"f",
	"alter function GetGroup (BWA)
	with (Modify External Name = ""BWAGroup"");

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-GetGroup (BWA)",
	"%SYSBLDUSER%",
	5, "GetGroup (BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 37, "Alter-Parallelize-GetGroup (BWA)",
	"%SYSBLDUSER%", 0,
	"alter function GetGroup (BWA)
	with (add parallelizable);

",
	"f",
	"alter function GetGroup (BWA)
	with (drop parallelizable);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	37, "Alter-Parallelize-GetGroup (BWA)",
	"%SYSBLDUSER%",
	5, "GetGroup (BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 85, "Alter-Variant-GetGroup (BWA)",
	"%SYSBLDUSER%", 0,
	"alter function GetGroup (BWA)
	with (add not variant);

",
	"f",
	"alter function GetGroup (BWA)
	with (drop not variant);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	85, "Alter-Variant-GetGroup (BWA)",
	"%SYSBLDUSER%",
	5, "GetGroup (BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "GetGroup (BWA)",
	"%SYSBLDUSER%", 0,
	"grant execute on function GetGroup (BWA) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	69, "GetGroup (BWA)",
	"%SYSBLDUSER%",
	5, "GetGroup (BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "GetIdentity (BWA)",
	"%SYSBLDUSER%", 0,
	"create function GetIdentity (BWA)
returns varchar (32)
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWAIdentity)"" language c;

",
	"f",
	"drop function GetIdentity (BWA);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	5, "GetIdentity (BWA)",
	"%SYSBLDUSER%",
	7, "BWA",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-GetIdentity (BWA)",
	"%SYSBLDUSER%", 0,
	"alter function GetIdentity (BWA)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWAIdentity)"");

",
	"f",
	"alter function GetIdentity (BWA)
	with (Modify External Name = ""BWAIdentity"");

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-GetIdentity (BWA)",
	"%SYSBLDUSER%",
	5, "GetIdentity (BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 37, "Alter-Parallelize-GetIdentity (BWA)",
	"%SYSBLDUSER%", 0,
	"alter function GetIdentity (BWA)
	with (add parallelizable);

",
	"f",
	"alter function GetIdentity (BWA)
	with (drop parallelizable);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	37, "Alter-Parallelize-GetIdentity (BWA)",
	"%SYSBLDUSER%",
	5, "GetIdentity (BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 85, "Alter-Variant-GetIdentity (BWA)",
	"%SYSBLDUSER%", 0,
	"alter function GetIdentity (BWA)
	with (add not variant);

",
	"f",
	"alter function GetIdentity (BWA)
	with (drop not variant);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	85, "Alter-Variant-GetIdentity (BWA)",
	"%SYSBLDUSER%",
	5, "GetIdentity (BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "GetIdentity (BWA)",
	"%SYSBLDUSER%", 0,
	"grant execute on function GetIdentity (BWA) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	69, "GetIdentity (BWA)",
	"%SYSBLDUSER%",
	5, "GetIdentity (BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "Empty (BWA)",
	"%SYSBLDUSER%", 0,
	"create function Empty (BWA)
returns boolean
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWAEmpty)"" language c;

",
	"f",
	"drop function Empty (BWA);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	5, "Empty (BWA)",
	"%SYSBLDUSER%",
	7, "BWA",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-Empty (BWA)",
	"%SYSBLDUSER%", 0,
	"alter function Empty (BWA)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWAEmpty)"");

",
	"f",
	"alter function Empty (BWA)
	with (Modify External Name = ""BWAEmpty"");

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-Empty (BWA)",
	"%SYSBLDUSER%",
	5, "Empty (BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 37, "Alter-Parallelize-Empty (BWA)",
	"%SYSBLDUSER%", 0,
	"alter function Empty (BWA)
	with (add parallelizable);

",
	"f",
	"alter function Empty (BWA)
	with (drop parallelizable);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	37, "Alter-Parallelize-Empty (BWA)",
	"%SYSBLDUSER%",
	5, "Empty (BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 85, "Alter-Variant-Empty (BWA)",
	"%SYSBLDUSER%", 0,
	"alter function Empty (BWA)
	with (add not variant);

",
	"f",
	"alter function Empty (BWA)
	with (drop not variant);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	85, "Alter-Variant-Empty (BWA)",
	"%SYSBLDUSER%",
	5, "Empty (BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 95, "Alter-Negator-Empty (BWA)",
	"%SYSBLDUSER%", 0,
	"alter function Empty (BWA)
	with (add negator=NotEmpty);

",
	"f",
	"alter function Empty (BWA)
	with (drop negator);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	95, "Alter-Negator-Empty (BWA)",
	"%SYSBLDUSER%",
	5, "Empty (BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "Empty (BWA)",
	"%SYSBLDUSER%", 0,
	"grant execute on function Empty (BWA) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	69, "Empty (BWA)",
	"%SYSBLDUSER%",
	5, "Empty (BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "Empty (BWA,int)",
	"%SYSBLDUSER%", 0,
	"create function Empty (BWA,int)
returns boolean
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWAEmptyPart)"" language c;

",
	"f",
	"drop function Empty (BWA,int);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	5, "Empty (BWA,int)",
	"%SYSBLDUSER%",
	7, "BWA",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-Empty (BWA,int)",
	"%SYSBLDUSER%", 0,
	"alter function Empty (BWA,int)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWAEmptyPart)"");

",
	"f",
	"alter function Empty (BWA,int)
	with (Modify External Name = ""BWAEmptyPart"");

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-Empty (BWA,int)",
	"%SYSBLDUSER%",
	5, "Empty (BWA,int)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 37, "Alter-Parallelize-Empty (BWA,int)",
	"%SYSBLDUSER%", 0,
	"alter function Empty (BWA,int)
	with (add parallelizable);

",
	"f",
	"alter function Empty (BWA,int)
	with (drop parallelizable);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	37, "Alter-Parallelize-Empty (BWA,int)",
	"%SYSBLDUSER%",
	5, "Empty (BWA,int)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 85, "Alter-Variant-Empty (BWA,int)",
	"%SYSBLDUSER%", 0,
	"alter function Empty (BWA,int)
	with (add not variant);

",
	"f",
	"alter function Empty (BWA,int)
	with (drop not variant);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	85, "Alter-Variant-Empty (BWA,int)",
	"%SYSBLDUSER%",
	5, "Empty (BWA,int)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 95, "Alter-Negator-Empty (BWA,int)",
	"%SYSBLDUSER%", 0,
	"alter function Empty (BWA,int)
	with (add negator=NotEmpty);

",
	"f",
	"alter function Empty (BWA,int)
	with (drop negator);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	95, "Alter-Negator-Empty (BWA,int)",
	"%SYSBLDUSER%",
	5, "Empty (BWA,int)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "Empty (BWA,int)",
	"%SYSBLDUSER%", 0,
	"grant execute on function Empty (BWA,int) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	69, "Empty (BWA,int)",
	"%SYSBLDUSER%",
	5, "Empty (BWA,int)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "NotEmpty (BWA)",
	"%SYSBLDUSER%", 0,
	"create function NotEmpty (BWA)
returns boolean
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWANotEmpty)"" language c;

",
	"f",
	"drop function NotEmpty (BWA);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	5, "NotEmpty (BWA)",
	"%SYSBLDUSER%",
	7, "BWA",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-NotEmpty (BWA)",
	"%SYSBLDUSER%", 0,
	"alter function NotEmpty (BWA)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWANotEmpty)"");

",
	"f",
	"alter function NotEmpty (BWA)
	with (Modify External Name = ""BWANotEmpty"");

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-NotEmpty (BWA)",
	"%SYSBLDUSER%",
	5, "NotEmpty (BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 37, "Alter-Parallelize-NotEmpty (BWA)",
	"%SYSBLDUSER%", 0,
	"alter function NotEmpty (BWA)
	with (add parallelizable);

",
	"f",
	"alter function NotEmpty (BWA)
	with (drop parallelizable);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	37, "Alter-Parallelize-NotEmpty (BWA)",
	"%SYSBLDUSER%",
	5, "NotEmpty (BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 85, "Alter-Variant-NotEmpty (BWA)",
	"%SYSBLDUSER%", 0,
	"alter function NotEmpty (BWA)
	with (add not variant);

",
	"f",
	"alter function NotEmpty (BWA)
	with (drop not variant);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	85, "Alter-Variant-NotEmpty (BWA)",
	"%SYSBLDUSER%",
	5, "NotEmpty (BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 95, "Alter-Negator-NotEmpty (BWA)",
	"%SYSBLDUSER%", 0,
	"alter function NotEmpty (BWA)
	with (add negator=Empty);

",
	"f",
	"alter function NotEmpty (BWA)
	with (drop negator);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	95, "Alter-Negator-NotEmpty (BWA)",
	"%SYSBLDUSER%",
	5, "NotEmpty (BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "NotEmpty (BWA)",
	"%SYSBLDUSER%", 0,
	"grant execute on function NotEmpty (BWA) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	69, "NotEmpty (BWA)",
	"%SYSBLDUSER%",
	5, "NotEmpty (BWA)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "NotEmpty (BWA,int)",
	"%SYSBLDUSER%", 0,
	"create function NotEmpty (BWA,int)
returns boolean
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWANotEmptyPart)"" language c;

",
	"f",
	"drop function NotEmpty (BWA,int);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	5, "NotEmpty (BWA,int)",
	"%SYSBLDUSER%",
	7, "BWA",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-NotEmpty (BWA,int)",
	"%SYSBLDUSER%", 0,
	"alter function NotEmpty (BWA,int)
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWANotEmptyPart)"");

",
	"f",
	"alter function NotEmpty (BWA,int)
	with (Modify External Name = ""BWANotEmptyPart"");

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-NotEmpty (BWA,int)",
	"%SYSBLDUSER%",
	5, "NotEmpty (BWA,int)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 37, "Alter-Parallelize-NotEmpty (BWA,int)",
	"%SYSBLDUSER%", 0,
	"alter function NotEmpty (BWA,int)
	with (add parallelizable);

",
	"f",
	"alter function NotEmpty (BWA,int)
	with (drop parallelizable);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	37, "Alter-Parallelize-NotEmpty (BWA,int)",
	"%SYSBLDUSER%",
	5, "NotEmpty (BWA,int)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 85, "Alter-Variant-NotEmpty (BWA,int)",
	"%SYSBLDUSER%", 0,
	"alter function NotEmpty (BWA,int)
	with (add not variant);

",
	"f",
	"alter function NotEmpty (BWA,int)
	with (drop not variant);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	85, "Alter-Variant-NotEmpty (BWA,int)",
	"%SYSBLDUSER%",
	5, "NotEmpty (BWA,int)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 95, "Alter-Negator-NotEmpty (BWA,int)",
	"%SYSBLDUSER%", 0,
	"alter function NotEmpty (BWA,int)
	with (add negator=Empty);

",
	"f",
	"alter function NotEmpty (BWA,int)
	with (drop negator);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	95, "Alter-Negator-NotEmpty (BWA,int)",
	"%SYSBLDUSER%",
	5, "NotEmpty (BWA,int)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "NotEmpty (BWA,int)",
	"%SYSBLDUSER%", 0,
	"grant execute on function NotEmpty (BWA,int) to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	69, "NotEmpty (BWA,int)",
	"%SYSBLDUSER%",
	5, "NotEmpty (BWA,int)",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 6, "BWAInitStats ()",
	"%SYSBLDUSER%", 0,
	"create procedure BWAInitStats ()
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWAInitStats)"" language c;

",
	"f",
	"drop procedure BWAInitStats ();

",
	"f"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 182, "Alter-ExternalName-BWAInitStats ()",
	"%SYSBLDUSER%", 0,
	"alter procedure BWAInitStats ()
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWAInitStats)"");

",
	"f",
	"alter procedure BWAInitStats ()
	with (Modify External Name = ""BWAInitStats"");

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	182, "Alter-ExternalName-BWAInitStats ()",
	"%SYSBLDUSER%",
	6, "BWAInitStats ()",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 86, "Alter-Variant-BWAInitStats ()",
	"%SYSBLDUSER%", 0,
	"alter procedure BWAInitStats ()
	with (add not variant);

",
	"f",
	"alter procedure BWAInitStats ()
	with (drop not variant);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	86, "Alter-Variant-BWAInitStats ()",
	"%SYSBLDUSER%",
	6, "BWAInitStats ()",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 70, "BWAInitStats ()",
	"%SYSBLDUSER%", 0,
	"grant execute on procedure BWAInitStats () to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	70, "BWAInitStats ()",
	"%SYSBLDUSER%",
	6, "BWAInitStats ()",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 5, "BWAPrintStats ()",
	"%SYSBLDUSER%", 0,
	"create function BWAPrintStats ()
returns lvarchar
external name ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWAPrintStats)"" language c;

",
	"f",
	"drop function BWAPrintStats ();

",
	"f"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 181, "Alter-ExternalName-BWAPrintStats ()",
	"%SYSBLDUSER%", 0,
	"alter function BWAPrintStats ()
	with (Modify External Name = ""$INFORMIXDIR/extend/%SYSBLDDIR%/BWA.bld(BWAPrintStats)"");

",
	"f",
	"alter function BWAPrintStats ()
	with (Modify External Name = ""BWAPrintStats"");

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	181, "Alter-ExternalName-BWAPrintStats ()",
	"%SYSBLDUSER%",
	5, "BWAPrintStats ()",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 111, "Alter-Iterator-BWAPrintStats ()",
	"%SYSBLDUSER%", 0,
	"alter function BWAPrintStats ()
	with (add iterator);

",
	"f",
	"alter function BWAPrintStats ()
	with (drop iterator);

",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	111, "Alter-Iterator-BWAPrintStats ()",
	"%SYSBLDUSER%",
	5, "BWAPrintStats ()",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 69, "BWAPrintStats ()",
	"%SYSBLDUSER%", 0,
	"grant execute on function BWAPrintStats () to public;

",
	"f",
	"",
	"f"
);

insert into sysbldobjdepends
	(bld_id, obj_kind, obj_signature, obj_owner,
	    need_obj_kind, need_obj_signature, need_obj_owner)
values
(
	"%SYSBLDNAME%",
	69, "BWAPrintStats ()",
	"%SYSBLDUSER%",
	5, "BWAPrintStats ()",
	"%SYSBLDUSER%"
);

insert into sysbldobjects
	(bld_id, obj_kind, obj_signature, obj_owner, sequence, create_sql,
	    create_can_fail, drop_sql, drop_can_fail)
values
(
	"%SYSBLDNAME%", 0, "sysbldregistered",
	"%SYSBLDUSER%", 0,
	"insert into sysbldregistered
	(bld_id)
values
(
	""%SYSBLDNAME%""
);

",
	"f",
	"delete from sysbldregistered
	where bld_id = ""%SYSBLDNAME%"";

",
	"f"
);

